### ISSUE TITLE
Hyperparams for VOT2018

### ISSUE THREAD

**Issue by StrangerZhang** [visionml/pytracking#1]
Hi, 

Is the default params of ATOM for VOT-2018?
By the way, solid work!

**Comment by martin-danelljan** [comment]
As described in the readme, there are different parameters for VOT. They will be up shortly.

**Comment by goutamgmb** [comment]
Hi,

The VOT settings have been uploaded now. You can find them at pytracking/parameter/atom/default_vot.py
