### ISSUE TITLE
Multiple Object Detection and Augmentation

### ISSUE THREAD

**Issue by skh0619** [visionml/pytracking#101]
Thank you very much for sharing your valuable research results and codes.
I have two questions.
1. Can I have multiple tracking using pytracking method? (ex. person1, person2, Tree..)
2. Could you give some Idea implementing augmentation at the pytracking method?

Thank you in advance.

**Comment by martin-danelljan** [comment]
Hi. Thank you!

1. Support for multi object tracking is one of the things we hope to integrate in the coming months. Although that is not the focus of our research.
2. I'm not sure what kind of augmentation you mean. Data augmentation for what purpose?

**Comment by skh0619** [comment]
Thank you for your prompt reply!
1. I hope it will be developed for various scenarios in the near future.
2 .As you know, learning data augmentation (rotation, translation, flip, etc.) will improve performance of model, so it seems necessary before training step.
3. Can I put another backbone model at the DiMP? (example: efficient, LeNet, AlexNet, VGG, GoogLeNet, ResNet and more..) 
Please explain briefly how, if possible.

Thank you again.

**Comment by martin-danelljan** [comment]
2. We are doing quite limited data augmentation for training. While having a random cropping strategy is clearly important, we haven't observed a significant effect from other augmentations. But we have not tested this much at all. So feel free to explore. I would be curious of any interesting findings :)

3. Integrating other backbones should be easy. Just check how it is currently done in the code and replicate that.

**Comment by skh0619** [comment]
Thank you again. 
I will consider your valuable comments.
