### ISSUE TITLE
sample_memory_size

### ISSUE THREAD

**Issue by zlj199502** [visionml/pytracking#102]
Hi,
Thanks for your excellent work. I have a question. In your code sample_memory_size seems to be 250. But the paper says that the size is set to 50.

**Comment by martin-danelljan** [comment]
Hi.
For DiMP, we only use a memory size of 250 **only** for VOT (though i dont think it is particularly important):

https://github.com/visionml/pytracking/blob/031a478c5d132500ef55a08419e8ae86257e3e47/pytracking/parameter/dimp/dimp50_vot.py#L16

The standard setting, which is used for all other datasets have a memory size of 50:

https://github.com/visionml/pytracking/blob/031a478c5d132500ef55a08419e8ae86257e3e47/pytracking/parameter/dimp/dimp50.py#L16

For ATOM, we always used 250.

**Comment by zlj199502** [comment]
Thank you for your reply!
