### ISSUE TITLE
Which one has better performance? ATOM? DiMP? SiamRPN++?

### ISSUE THREAD

**Issue by skh0619** [visionml/pytracking#103]
I think the DiMP has higher performance score. Am I right?
Also, the DiMP performance looks similar SiamRPN++ according to Table 3 in the paper.
So, my question is which one is best?

Thank you in advance.

**Comment by martin-danelljan** [comment]
Please check the DiMP paper for a thorough experimental comparison with SiamRPN++ and ATOM on 7 datasets. DiMP is better on 6 datasets. You can also find a new independent analysis here: https://arxiv.org/abs/1911.07959
DiMP has much lower failure rate in particular.
