### ISSUE TITLE
Choose optimizer 

### ISSUE THREAD

**Issue by skh0619** [visionml/pytracking#104]
In your paper, you used GD, SGD optimizer.
You already know that, now a days, many paper used Adam optimizer for performance and speed.
I think Adam optimizer has also good performance/speed comparing GD, SGD.
So, I wondering that are there any reason for choose GD/SGD in your research?

**Comment by martin-danelljan** [comment]
Hi. DiMP is actually using Adam for training:

https://github.com/visionml/pytracking/blob/031a478c5d132500ef55a08419e8ae86257e3e47/ltr/train_settings/dimp/dimp50.py#L110

Steepest descent is performed by the network architecture itself to predict the target model weights.
