### ISSUE TITLE
Diff between paper and code?

### ISSUE THREAD

**Issue by songdejia** [visionml/pytracking#105]
hi martin,
   In ATOM，for reference branch, why use layer2 and layer3 to modulation in code but layer3 and layer4 in paper？

**Comment by HengLan** [comment]
In fact, there is a 'conv1' in the ResNet, and this 'conv1' is actually the 1st block of ResNet. The second to the fifth block is named 'layer1' to 'layer4', accordingly (['conv1', 'layer1', 'layer2', 'layer3', 'layer4'] = ['block1', 'block2', 'block3', 'block4', 'block5']). Thus, 'layer2' and 'layer3' are the 3rd and 4th block, as claimed in their paper. You can check the forward pass of ResNet for details (line 135 in ltr/models/backbone/resnet.py)

**Comment by martin-danelljan** [comment]
@HengLan Thank you for the answer. This is completely correct.
