### ISSUE TITLE
Runing problem in win10 platform

### ISSUE THREAD

**Issue by Erissonleo** [visionml/pytracking#108]
Thanks for your great job. I want run the program in win10 with cuda10.0, Anaconda3. I have installed the third module needed. I also build ninja.exe and add it to the system path. But I still can't running the AtomNet program. It raise the error " Error building extension '_prroi_pooling' ". Can you help me? Thanks!
![Q1](https://user-images.githubusercontent.com/17607584/71346810-b41e4100-25a3-11ea-875c-b446b9689039.png)
![Q2](https://user-images.githubusercontent.com/17607584/71346814-b5e80480-25a3-11ea-811e-9bf039ce5d63.png)

**Comment by martin-danelljan** [comment]
Hi. Thank you!

This is a problem with building the [prroi pooling module](https://github.com/vacancy/PreciseRoIPooling). I doubt they support building it on Windows, but you need to refer to [their repo](https://github.com/vacancy/PreciseRoIPooling) for this. We have never, and will most likely never aim to make this work on Windows, so you are on your own unfortunately. I would advice against it.

If you do manage to make it work on Windows, please report back here so we can perhaps integrate this.

Regards,
Martin

**Comment by lcsama** [comment]
> Hi. Thank you!
> 
> This is a problem with building the [prroi pooling module](https://github.com/vacancy/PreciseRoIPooling). I doubt they support building it on Windows, but you need to refer to [their repo](https://github.com/vacancy/PreciseRoIPooling) for this. We have never, and will most likely never aim to make this work on Windows, so you are on your own unfortunately. I would advice against it.
> 
> If you do manage to make it work on Windows, please report back here so we can perhaps integrate this.
> 
> Regards,
> Martin

Hi! 
I have the same problem working with windows10. I can't make it work with `ninja`, but thanks to your advise, I made it work with VS2015. The key is to compile the [prroi pooling module](https://github.com/vacancy/PreciseRoIPooling) with Visual Studio. If you have the plan to integrate it, I am glad to help.
Best Wishes.

**Comment by martin-danelljan** [comment]
> Hi!
> I have the same problem working with windows10. I can't make it work with `ninja`, but thanks to your advise, I made it work with VS2015. The key is to compile the [prroi pooling module](https://github.com/vacancy/PreciseRoIPooling) with Visual Studio. If you have the plan to integrate it, I am glad to help.
> Best Wishes.

Hi! This sounds very nice! We would very much appreciate if you can help us writing a short guide for this. You could either do a pull request extending the [INSTALL.md](https://github.com/visionml/pytracking/blob/master/INSTALL.md) (or a new INSTALL_WIN.md). Or you could send me (or post here) some step-by-step instructions, and I will add it to the README myself.

Regards,
Martin

**Comment by lcsama** [comment]
> 
> Hi! This sounds very nice! We would very much appreciate if you can help us writing a short guide for this. You could either do a pull request extending the [INSTALL.md](https://github.com/visionml/pytracking/blob/master/INSTALL.md) (or a new INSTALL_WIN.md). Or you could send me (or post here) some step-by-step instructions, and I will add it to the README myself.
> 
> Regards,
> Martin

Hi! I have made the pull request. And I added a pre-build package for prroi pooling module on windows. So I believe others can get rid of building it from source, which is pretty troublesome. 

Best Wishes.
