### ISSUE TITLE
ATOMSampler when dataset is not video_dataset

### ISSUE THREAD

**Issue by dongfangduoshou123** [visionml/pytracking#11]
**In ATOMSampler __getitem__(self, index) function
  when select a dataset which is not a video_dataset,
  the sampled train_frame_ids and test_frame_ids are
generated as follows:
            train_frame_ids = [1]*self.num_train_frames
            test_frame_ids = [1]*self.num_test_frames

Problem: I have test for example [1] * 5 in python3.5, which result is a list [1, 1, 1, 1, 1] , so if self.num_test_frames = 5, then test_frame_ids will be always [1, 1, 1, 1, 1], so the result
of all 5 test_frames are always equal to the first frame of the sequence,has not any Randomness,   train_frames is the same, is it a bug?   
**
`

> class

 ATOMSampler(torch.utils.data.Dataset):

    def __getitem__(self, index):
        # Select a dataset
       ........
       ........

        if is_video_dataset:
           .......
        else:
            train_frame_ids = [1]*self.num_train_frames
            test_frame_ids = [1]*self.num_test_frames

        # Get frames
        train_frames, train_anno, _ = dataset.get_frames(seq_id, train_frame_ids, anno)
        test_frames, test_anno, _ = dataset.get_frames(seq_id, test_frame_ids, anno)

        # Prepare data
        data = TensorDict({'train_images': train_frames,
                           'train_anno': train_anno,
                           'test_images': test_frames,
                           'test_anno': test_anno,
                           'dataset': dataset.get_name()})

        # Send for processing
        return self.processing(data)
`

**Comment by goutamgmb** [comment]
Hi,

This is not a bug. When using object detection datasets like COCO, we cannot sample multiple train or test frames, as only a single image is available. Hence train_frame_ids  and test_frame_ids are all set to 1. The processing function will however apply augmentations to this single image, so that the train and test samples are not identical.
