### ISSUE TITLE
mutigpus

### ISSUE THREAD

**Issue by YM-P51** [visionml/pytracking#110]
Can you shell me how to use mutigpus when training?
Thanks a lot!

**Comment by martin-danelljan** [comment]
Hi. Check the train settings:

https://github.com/visionml/pytracking/blob/031a478c5d132500ef55a08419e8ae86257e3e47/ltr/train_settings/dimp/dimp50.py#L19

https://github.com/visionml/pytracking/blob/031a478c5d132500ef55a08419e8ae86257e3e47/ltr/train_settings/dimp/dimp50.py#L100-L101

**Comment by YM-P51** [comment]
Found it!
Thank you very much!
