### ISSUE TITLE
IoU Predictor Network Training Dataset

### ISSUE THREAD

**Issue by khaghanijavad** [visionml/pytracking#111]
Hi, in paper you have mentioned that "Target estimation is performed by the IoU-predictor network. This network is trained offline on large-scale video tracking and object detection datasets, and its weights are frozen during online tracking." 
Could you please let me know that the current implementation is trained on which datasets? 

Thanks.

**Comment by martin-danelljan** [comment]
Hi. The training sets are specified in the respective train settings files.

For DiMP (LaSOT, GOT10k, TrackingNet, and COCO):
https://github.com/visionml/pytracking/blob/031a478c5d132500ef55a08419e8ae86257e3e47/ltr/train_settings/dimp/dimp50.py#L33-L37

For ATOM (LaSOT, TrackingNet and COCO):
https://github.com/visionml/pytracking/blob/031a478c5d132500ef55a08419e8ae86257e3e47/ltr/train_settings/bbreg/atom_default.py#L30-L33

**Comment by khaghanijavad** [comment]
Thank you very much.
