### ISSUE TITLE
parameters for VOT2019

### ISSUE THREAD

**Issue by 594422814** [visionml/pytracking#116]
Hi,
Thanks for sharing this excellent framework.
Can you share the hyperparameters for the VOT2019 chanllenge?

**Comment by goutamgmb** [comment]
Hi,

You can find the vot19 setting (https://github.com/visionml/pytracking/blob/master/pytracking/parameter/dimp/dimp50_vot19.py) in the latest commit.

**Comment by 594422814** [comment]
Thank you very much!
