### ISSUE TITLE
Q: Data Augmentation

### ISSUE THREAD

**Issue by MMarvasti** [visionml/pytracking#117]
Hi @martin-danelljan,

As you've mentioned in your paper, data augmentation is only performed in the first frame for online tracking. Please let me know the reason that you didn't use this strategy for offline training.  Also, did you investigate training performance when these samples are considered in offline training?
Thank you in advance.

**Comment by martin-danelljan** [comment]
Hi. Please see [this answer](https://github.com/visionml/pytracking/issues/101#issuecomment-562923510). Also, we did not investigate the effect of including such samples during offline training.

**Comment by MMarvasti** [comment]
Thank you for your reply.
Best Regards.
