### ISSUE TITLE
Code inconsistency with network architecture

### ISSUE THREAD

**Issue by MMarvasti** [visionml/pytracking#118]
Hi @martin-danelljan and @goutamgmb,

Although PrPool layers are applied to the resulted feature maps in the test branch (i.e., c3_t and c4_t) according to your paper, you used these pooling layers after Modulation in your codes (c3_t_att and c4_t_att, atom_iou_net.py). Please let me know about the mentioned inconsistency between the network architecture in the paper and your codes. 
Thank you in advance.

![Predict_IoU](https://user-images.githubusercontent.com/24586420/72659661-64ebe600-3980-11ea-97c3-779051d7f6ce.jpg)
![nework](https://user-images.githubusercontent.com/24586420/72659672-b09e8f80-3980-11ea-9adc-b99d149ea31a.jpg)

**Comment by martin-danelljan** [comment]
Hi. This is explained [in this previous reply](https://github.com/visionml/pytracking/issues/51#issuecomment-513486343).

**Comment by MMarvasti** [comment]
Thank you for your reply.
Best Regards.
