### ISSUE TITLE
training time too long and GPU-util is low possible due to file i/o

### ISSUE THREAD

**Issue by rambleramble** [visionml/pytracking#121]
Hi,
when I am doing the training. I am facing a typical GPU-Util too low and memory-usage high issue.
I suspect the issue is that the data is in a HDD drive, not SSD.  My training is single-gpu on GTX1080. The training time is multiple days for 50 iteration of the Dimp-18 model.

I saw your other thread talking about the total training uses 5 hours.  
https://github.com/visionml/pytracking/issues/54
Could you share the specifics of the training specs, especially the file i/o handling? Is there any specific filesystem or special handling?

Thanks so much in advance!

**Comment by goutamgmb** [comment]
The training time is 5 hours for the ATOM-18 model. For DiMP-18, it is usually around 1 day. However, these timings are obtained when using a SSD, without any special handling (i.e. pre-processing of data). The training time is expected to be much longer if you are using a HDD.

**Comment by rambleramble** [comment]
Great, thanks very much for this prompt answer!

**Comment by martin-danelljan** [comment]
Buy an SSD. You will get 10x :rocket: more value :heavy_dollar_sign: from your 1080 then :smile:

**Comment by rambleramble** [comment]
@martin-danelljan  Thanks a lot, any particular brand suggestion? PCIe or SATA?
Thanks very much again!

**Comment by martin-danelljan** [comment]
A SATA drive is enough, from my experience. But it depends on how many GPUs you plan to put in your computer. I think most standard brands are ok. I have mostly used Samsung SSDs, and they have always been fine for me.

Good luck with your setup!
