### ISSUE TITLE
Model Selection

### ISSUE THREAD

**Issue by MMarvasti** [visionml/pytracking#122]
Hi @martin-danelljan ,

According to your paper, you used LaSOT and TrackingNet datasets for training. Could you please let me know how you selected the best-trained model, among other ones? Did you use specific criteria to choose the best model? Did you evaluate your training process by some validation sets (if yes, which datasets)?
Thank you in advance.

**Comment by martin-danelljan** [comment]
Hi. We did not evaluate different models. We simply selected the final model (usually the 50th epoch) obtained in our training. We have a GOT10k validation set during training (see the train setting files), but this is only to monitor the training process. We did not use it for any model selection. So, to put it clearly, we never "tuned" the checkpoint number.

Regards,
Martin

**Comment by MMarvasti** [comment]
Thanks a lot.

Kind regards,
Mojtaba
