### ISSUE TITLE
Running trackers on custom dataset

### ISSUE THREAD

**Issue by AvivSham** [visionml/pytracking#123]
Is it possible to run the trackers on a custom dataset? If so can you please guide me on how can it be done?
I will make myself clear, I want to inference some videos I have using these trackers how can I do so? How do I select the tracked object does it done manually or an initial bounding box should be given?

**Comment by martin-danelljan** [comment]
You can check the documentation about [running a tracker](https://github.com/visionml/pytracking/tree/master/pytracking#running-a-tracker). Seems you should use the `run_video` function. You need to give it a bounding box, yes.

**Comment by AvivSham** [comment]
Ok, I will look into it.
*) Just to be clear the tracking head does not have any learnable parameters right? (this is why you use parameter file which holds the tracker config)
*) I didn't see any output path as one of the argparses, where does the output video save to?

**Comment by martin-danelljan** [comment]
* https://arxiv.org/pdf/1904.07220v1.pdf
* run_video does not save the result. You can easily edit the code to do that. Or integrate the dataset and use `run_Tracker`. Check the local.py to set the path as generated by the instructions linked above.
