### ISSUE TITLE
impact of the depth of the backbone resnet?

### ISSUE THREAD

**Issue by rambleramble** [visionml/pytracking#124]
Great work!
Have you tried resnet-34  and resnet-101 as backbone by any chance?
How the balance was evaluated between accuracy and speed when designing and choosing the backbone network depth?

Thanks a lot!

**Comment by martin-danelljan** [comment]
Hi. Thanks.

We have not investigated the backbone much. We have just tried ResNet18 and 50. Feel free to try. Should be extremely easy in the framework. For DiMP, ResNet50 is not that much slower, just 30% or so.

Regards,
Martin

**Comment by rambleramble** [comment]
Thanks for sharing, sure will test out different backbone and share if any interesting discoveries.
