### ISSUE TITLE
VOT 2018 robustness calculation

### ISSUE THREAD

**Issue by rambleramble** [visionml/pytracking#127]
Wondering how did you calculate the robustness score of VOT2018 through the vot-toolkit. It seems the toolkit generate reports only showing the Failures.

Did you use your own or 3rd party such as pysot-toolkit to calculate the robustness and the accuracy?

Thanks in advance!

**Comment by goutamgmb** [comment]
Hi,

Yes, the VOT toolkit only provides the number of failures. However you can compute the robustness score by dividing the number of pooled failures with a scaling factor of 213.6752. I obtained the scaling factors using the robustness values provided in VOT2018 report and the number of failures reported by the toolkit.
