### ISSUE TITLE
Running this on mac

### ISSUE THREAD

**Issue by adityak2920** [visionml/pytracking#128]
I am trying to use this repo on mac but as I am running on the mac I want to run this on CPU. So, when I am trying to run this on the CPU. I found that precise roi pooling layer is only implemented for GPU so how can I run this on CPU?
I am trying to run DiMP.

**Comment by martin-danelljan** [comment]
Right now, there is no way to run the PrROIPool layer on CPU that I know of. However, you can run the tracker without the IoUNet part (although it wont be nearly as good).

Try for example using [this ATOM parameter file](https://github.com/visionml/pytracking/blob/master/pytracking/parameter/atom/multiscale_no_iounet.py) or set `params.use_iou_net = False` in any DiMP parameter file.
