### ISSUE TITLE
'ImagenetVID' object has no attribute '_get_class_name_from_id'

### ISSUE THREAD

**Issue by beyondpzk** [visionml/pytracking#13]
'ImagenetVID' object has no attribute '_get_class_name_from_id',

when I use imagenet VID 2015.

**Comment by xyc2690** [comment]
Missing the function as well.
I comment this line and use 'class_name = class_name_id ' instead.

**Comment by beyondpzk** [comment]
thanks ,I do this also

**Comment by goutamgmb** [comment]
Thanks for notifying the problem. We have fixed it in the latest commit.
