### ISSUE TITLE
where is the classifier in the ATOM?

### ISSUE THREAD

**Issue by fguney** [visionml/pytracking#131]
I see it for the DiMP but where is the online classifier for ATOM in the code?

**Comment by martin-danelljan** [comment]
The optimizer for first frame:
https://github.com/visionml/pytracking/blob/ea6d9e3b1211bc451e5616523a16ddee17984d5c/pytracking/tracker/atom/atom.py#L164

Rest of frames:
https://github.com/visionml/pytracking/blob/ea6d9e3b1211bc451e5616523a16ddee17984d5c/pytracking/tracker/atom/atom.py#L197

Apply classifier:
https://github.com/visionml/pytracking/blob/ea6d9e3b1211bc451e5616523a16ddee17984d5c/pytracking/tracker/atom/atom.py#L240
