### ISSUE TITLE
Hello,martin! Could you tell me which grawing tool was used in Fig.2(overview of target classification branch) in the paper?

### ISSUE THREAD

**Issue by Jack-zhangluyao** [visionml/pytracking#135]
Hello, martin!  thanks for your excellent work!  the Fig.2 is so beautiful and I want to design a similar graph for my work, could you tell me which drawing tool did you use? thanks in advance!

**Comment by martin-danelljan** [comment]
Hi! Thank you. The credit actually goes to @goutamgmb, who made the figure. It is made using PowerPoint.

**Comment by Jack-zhangluyao** [comment]
> Hi! Thank you. The credit actually goes to @goutamgmb, who made the figure. It is made using PowerPoint.

Get it! Thanks a lot!

**Comment by goutamgmb** [comment]
Hi @Jack-zhangluyao 

I realized that most of the figure was actually made in google drawings. Here is the link to the figure https://drive.google.com/open?id=1yZAigWhUYBDxLh9zSNuieDGOi12oqhje_NdDbmi9758. I used PowerPoint to apply 3D rotation to the input images. Although you can make the complete figure using PowerPoint as well.

**Comment by Jack-zhangluyao** [comment]
Get it! Thanks for reply!


| |
张路遥
|
|
jack_zhangluyao@163.com
|
签名由网易邮箱大师定制
On 4/25/2020 20:22，Goutam Bhat<notifications@github.com> wrote：

Hi @Jack-zhangluyao

I realized that most of the figure was actually made in google drawings. Here is the link to the figure https://drive.google.com/open?id=1yZAigWhUYBDxLh9zSNuieDGOi12oqhje_NdDbmi9758. I used PowerPoint to apply 3D rotation to the input images. Although you can make the complete figure using PowerPoint as well.
