### ISSUE TITLE
Can the same result be obtained using random seeds?

### ISSUE THREAD

**Issue by Wenju-Huang** [visionml/pytracking#136]
I add the follow code in the begining, but the outputs still are random. How can I get a fixed outputs? thanks
`  random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    mx.random.seed(seed)`

**Comment by martin-danelljan** [comment]
Hi. I have not tried around with that. Can you check if you are evaluating on zero threads? I.e. that you are not doing the parallel processing.

**Comment by meimeixu520** [comment]
Hi，@martin-danelljanI  also meet the same problems,every test  results is diffierent,can you tell the reason?thanks,look foward your reply!

**Comment by martin-danelljan** [comment]
I would strongly advise not trying to use fix seeds. In the end you might end up tuning for a particular seed, and dont see the actual impact of the performance. If you fix the seed, it will be much more difficult to evaluate and develop the tracker.

If you want stable performance, take the average over 3 runs on the combined OTB+NFS+UAV datasets. This usually gives very good and stable indication of the performance before going on to other datasets.
