### ISSUE TITLE
Is there any bug in ltr/data/sampler.py?

### ISSUE THREAD

**Issue by sherlockedlee** [visionml/pytracking#137]
Thx for you brilliant work.But I think the code below might not be right(in DIMPsampler)
```
            seq_info_dict = dataset.get_sequence_info(seq_id)
            visible = seq_info_dict['visible']

            enough_visible_frames = visible.type(torch.int64).sum().item() > 2 * (
                    self.num_test_frames + self.num_train_frames) and len(visible) >= 20

            enough_visible_frames = enough_visible_frames or not is_video_dataset
```

Because in image dataset, `not is_video_dataset `is always True,no matter `enough_visible_frames` is True or not,it will break the loop anyway.If there is any invisible object in dataset,it will raise the error: too small bounding box.I wonder if it should be written like Atom:
`enough_visible_frames = ((not is_video_dataset) and num_visible > 0) or (num_visible > min_visible_frames and len(visible) >= 20)`

**Comment by martin-danelljan** [comment]
Hi.
Thanks for posting. We are soon releasing new code, including modified samplers. I will check if this might cause an issue and include it in the new version.
