### ISSUE TITLE
Bounding box results

### ISSUE THREAD

**Issue by sluke17** [visionml/pytracking#138]
Hi,

I am using dimp 50 to track the object in my video but i cannot seem to find where the bounding boxes are. Really cool tracker by the way! Does the application provide the tracked bounding boxes?

**Comment by martin-danelljan** [comment]
Hi. Thank you!

You set the path where results are saved using the `result_path` variable in `pytracking/evaluation/local.py`. Bounding boxes are only saved if the debug flag is set to zero. Please tell me if you have any problems or more questions regarding this.

**Comment by goutamgmb** [comment]
Hi @sluke17 

In case you are trying to run the tracker on a video using the run_video.py script, you can now save the bounding boxes by passing the --save_results flag. See https://github.com/visionml/pytracking/issues/142#issuecomment-619904430 for more details.
