### ISSUE TITLE
Draw a Figure like DiMP

### ISSUE THREAD

**Issue by MasterBin-IIAU** [visionml/pytracking#139]
Hi Goutam @goutamgmb 
I want to consult how to draw feature maps as shown in figure2 of DiMP using Power Point.
Could you please share the original Power Point file for figure2 in DiMP?
My email is yan_bin@mail.dlut.edu.cn
Thank you.

**Comment by goutamgmb** [comment]
Hi,

It seems I made the figure in google drawings actually.  Here is the link for the google drawing https://drive.google.com/open?id=1yZAigWhUYBDxLh9zSNuieDGOi12oqhje_NdDbmi9758.

**Comment by MasterBin-IIAU** [comment]
Thank you ! ! !
But I still wonder how to draw a feature map in google drawings.
Could u give me some advise? Thank you

**Comment by goutamgmb** [comment]
The feature maps are drawn using the 'cube' shape (Insert -> Shape -> Shapes -> Cube (third row, last column)). It will require some trial and error to get a nice looking figure :)

**Comment by MasterBin-IIAU** [comment]
Thank you for your patience!
With your help, I find the reason why I failed before and now I make it!
It feels so good, thank you so much :)
