### ISSUE TITLE
tracker on the VOT2018 

### ISSUE THREAD

**Issue by hfutwujingjing** [visionml/pytracking#14]
Thanks for releasing  the code of such excellent paper！
Does the test on the VOT2018 directly put the tracking results generated by this code into the ‘run analysis. m’ of the vot-toolkit to get the final result?

**Comment by martin-danelljan** [comment]
Thank you!
No unfortunately not. Since the vot-toolkit does not yet support pytorch version >0.3, we have yet released an official VOT integration. We hope to do that in the near future, as soon as the issues in the vot-toolkit has been solved by them. Until then, you will need to write a work-around yourself.

**Comment by DeepBrainsMe** [comment]
I have test your code(atom_default.pth from your google drive) use pysot_toolkit(https://github.com/StrangerZhang/pysot-toolkit) .
However  I didn't get the same EAO score as your paper ,only  0.361  average 15 times.
 The details code  I have sent to Goutam，I wonder where the bugs stay.

**Comment by ZekuiQin** [comment]
> I have test your code(atom_default.pth from your google drive) use pysot_toolkit(https://github.com/StrangerZhang/pysot-toolkit) .
> However I didn't get the same EAO score as your paper ,only 0.361 average 15 times.
> The details code I have sent to Goutam，I wonder where the bugs stay.

Hi, what is your discuss results? I test ATOM on VOT2018 using pysot_toolkit, only get EAO=0.346 average score over 15 runs.

**Comment by salt-fisher** [comment]
@DeepBrainsMe @ZekuiQin  I have just tested the atom on vot2018 over 15 runs, but only get 0.385 average score(with the released trained model and parameter file 'default_vot.py')

**Comment by xiaolin13** [comment]
> @DeepBrainsMe @ZekuiQin I have just tested the atom on vot2018 over 15 runs, but only get 0.385 average score(with the released trained model and parameter file 'default_vot.py')
I only got 0.331 average score when using pysot-toolkit, it's far from paper 0.401.
