### ISSUE TITLE
Trouble about VOT Integration

### ISSUE THREAD

**Issue by sherlockedlee** [visionml/pytracking#140]
Thanks for you great work.I have installed the vot-python-toolkit and set up the workspace,but when I type` vot evaluate --workspace <workspace-path> DiMP`,the error occurs.In log file,it says
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_vot' is not defined
Process not alive anymore, unable to retrieve return code.
```
And in terminal,it says` Tracker DiMP encountered an error: Unable to connect to tracker`
And when I run run_vot.py,it froze at` handle = vot.VOT("polygon") `in evaluation/tracker.py while gpu is occupied.Can you tell me what's happening?thanks a lot.

**Comment by DeepBrainsMe** [comment]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/adminer/CODE/NewStage/NewState/pytracking/run_vot.py", line 17, in run_vot
    tracker.run_vot()
  File "/home/adminer/CODE/NewStage/NewState/pytracking/evaluation/tracker.py", line 599, in run_vot
    handle = vot.VOT("polygon")
  File "/home/adminer/CODE/NewStage/NewState/pytracking/evaluation/vot.py", line 92, in __init__
    options = trax.server.ServerOptions(region_format, trax.image.PATH)
AttributeError: module 'trax.server' has no attribute 'ServerOptions'
Exception ignored in: <bound method VOT.__del__ of <pytracking.evaluation.vot.VOT object at 0x7ff831be22b0>>
Traceback (most recent call last):
  File "/home/adminer/CODE/NewStage/NewState/pytracking/evaluation/vot.py", line 173, in __del__
    self.quit()
  File "/home/adminer/CODE/NewStage/NewState/pytracking/evaluation/vot.py", line 165, in quit
    self._trax.quit()
AttributeError: 'VOT' object has no attribute '_trax'
 

I got this error , when I test  dimp with vottoolkit.

**Comment by goutamgmb** [comment]
Hi,

Thanks for notifying the issues. I have pushed a fix now. Can you verify if the integration works now? You will have to copy the trackers.ini file again.

**Comment by sherlockedlee** [comment]
> Hi,
> 
> Thanks for notifying the issues. I have pushed a fix now. Can you verify if the integration works now? You will have to copy the trackers.ini file again.

Thanks,it worked,but took too long time to evaluate,is it normal?
```
Loading dataset: 100%|████████████████████████████████████████████████████████| 60/60 [00:00<00:00, 80.17sequences/s]
DiMP/baseline:  11%|████▍                                  | 6.733333333333333/60 [56:03<17:04:17, 1153.78s/sequence]
```

**Comment by goutamgmb** [comment]
@sherlockedlee  Yes, that is normal. VOT2020 performs multi-start evaluation, so the tracker is run multiple times on each sequence leading to longer evaluation time.

**Comment by DeepBrainsMe** [comment]
I am sorry to trouble you. When I test   run_vot.py  with official vot-toolkit with trax  evaluated on vot2018 benchmark，I came across this bug :

pytracking/evaluation/vot.py", line 165, in quit   self._trax.quit()
AttributeError: 'VOT' object has no attribute '_trax'
 
Could you tell me what's happening?thanks a lot.

**Comment by DeepBrainsMe** [comment]
> I am sorry to trouble you. When I test run_vot.py with official vot-toolkit with trax evaluated on vot2018 benchmark，I came across this bug :
> 
> pytracking/evaluation/vot.py", line 165, in quit self._trax.quit()
> AttributeError: 'VOT' object has no attribute '_trax'
> 
> Could you tell me what's happening?thanks a lot.

I have find the solution for this bug .  In your code 

https://github.com/visionml/pytracking/blob/b1bbbe94cac86cd04049e94c5773037eb78e2a61/pytracking/evaluation/tracker.py#L586
  import vot.py error,It will output AttributeError. 
# import pytracking.evaluation.vot as vot  # AttributeError.
   import pytracking.VOT.vot as vot   # It will be Ok

**Comment by sherlockedlee** [comment]
> > I am sorry to trouble you. When I test run_vot.py with official vot-toolkit with trax evaluated on vot2018 benchmark，I came across this bug :
> > pytracking/evaluation/vot.py", line 165, in quit self._trax.quit()
> > AttributeError: 'VOT' object has no attribute '_trax'
> > Could you tell me what's happening?thanks a lot.
> 
> I have find the solution for this bug . In your code
> 
> https://github.com/visionml/pytracking/blob/b1bbbe94cac86cd04049e94c5773037eb78e2a61/pytracking/evaluation/tracker.py#L586
> 
> import vot.py error,It will output AttributeError.
> 
> # import pytracking.evaluation.vot as vot # AttributeError.
> 
> import pytracking.VOT.vot as vot # It will be Ok

Yes,I use this script as well for python toolkit.I guess pytracking.evaluation.vot may be used for matlab cause I don't install TraX.

**Comment by sherlockedlee** [comment]
Sorry to bother you again.The results of python-toolkit as follows:
```

{
  "baseline": [
    {
      "tracker_name": "DiMP",
      "vot.analysis.measures.AccuracyRobustness": [
        0.584819703641844,
        0.8304020727976527,
        21356
      ],
      "vot.analysis.measures.EAO": 0.403071790933609
    }
  ],
  "unsupervised": [
    {
      "tracker_name": "DiMP",
      "vot.analysis.measures.AverageAccuracy": [
        0.4561690706823326,
        21356
      ]
    }
  ],
  "realtime": [
    {
      "tracker_name": "DiMP",
      "vot.analysis.measures.AccuracyRobustness": [
        0.5679649140410385,
        1.0720640569395017,
        21356
      ],
      "vot.analysis.measures.EAO": 0.36817267537117004
    }
  ]
}
```

The parameter I use is dimp50_vot.py,dataset is vot2018,I don't change the code,is it stricter for lower performance? @goutamgmb

**Comment by goutamgmb** [comment]
Hi @sherlockedlee 

We haven't run on vot2018 using the new vot evaluation method, however the results you get seems reasonable.

**Comment by sherlockedlee** [comment]
> Hi @sherlockedlee
> 
> We haven't run on vot2018 using the new vot evaluation method, however the results you get seems reasonable.

Thanks for your patience,but eao of dimp50 in your model zoo is 0.440.I notice the performance of dimp is not stable,is it the best performance not the average?

**Comment by goutamgmb** [comment]
The vot python toolkit uses a different criteria to compute the EAO, as compared to the old matlab toolkit. See https://data.votchallenge.net/vot2020/vot-2020-protocol.pdf for details. The results reported in the model zoo were obtained using the matlab toolkit. In general, the results of dimp varies between different runs. Hence the result (0.44) reported in the model zoo is an average over 15 runs.

**Comment by sherlockedlee** [comment]
> The vot python toolkit uses a different criteria to compute the EAO, as compared to the old matlab toolkit. See https://data.votchallenge.net/vot2020/vot-2020-protocol.pdf for details. The results reported in the model zoo were obtained using the matlab toolkit. In general, the results of dimp varies between different runs. Hence the result (0.44) reported in the model zoo is an average over 15 runs.

Thanks a lot!

**Comment by DeepBrainsMe** [comment]
I have run vot2020 with the new python-vot-toolkit and protocal. 
Here is the result of the model **dimp dimp50_vot19**, Does it reasonable?
{
  "baseline": [
    {
      "tracker_name": "DiMP",
      "vot.analysis.measures.AccuracyRobustnessMultiStart": [
        0.4447502491826599,
        0.7506665235090043,
        19945
      ],
      "vot.analysis.measures.EAOMultiStart": 0.28651943802833557
    }
  ],
  "unsupervised": [
    {
      "tracker_name": "DiMP",
      "vot.analysis.measures.AverageAccuracy": [
        0.34874575999800517,
        19945
      ]
    }
  ],
  "realtime": [
    {
      "tracker_name": "DiMP",
      "vot.analysis.measures.AccuracyRobustnessMultiStart": [
        0.44455629534424274,
        0.7592114061509256,
        19945
      ],
      "vot.analysis.measures.EAOMultiStart": 0.29136037826538086
    }
  ]
}

**Comment by goutamgmb** [comment]
@DeepBrainsMe Yes, that is similar to what we get.

**Comment by xiaolin13** [comment]
> Sorry to bother you again.The results of python-toolkit as follows:
> 
> ```
> 
> {
>   "baseline": [
>     {
>       "tracker_name": "DiMP",
>       "vot.analysis.measures.AccuracyRobustness": [
>         0.584819703641844,
>         0.8304020727976527,
>         21356
>       ],
>       "vot.analysis.measures.EAO": 0.403071790933609
>     }
>   ],
>   "unsupervised": [
>     {
>       "tracker_name": "DiMP",
>       "vot.analysis.measures.AverageAccuracy": [
>         0.4561690706823326,
>         21356
>       ]
>     }
>   ],
>   "realtime": [
>     {
>       "tracker_name": "DiMP",
>       "vot.analysis.measures.AccuracyRobustness": [
>         0.5679649140410385,
>         1.0720640569395017,
>         21356
>       ],
>       "vot.analysis.measures.EAO": 0.36817267537117004
>     }
>   ]
> }
> ```
> 
> The parameter I use is dimp50_vot.py,dataset is vot2018,I don't change the code,is it stricter for lower performance? @goutamgmb

Hello, how do you run in python toolkit. When I run with vot-toolkit-python, it will core dumped.

**Comment by xiaolin13** [comment]
> Sorry to bother you again.The results of python-toolkit as follows:
> 
> ```
> 
> {
>   "baseline": [
>     {
>       "tracker_name": "DiMP",
>       "vot.analysis.measures.AccuracyRobustness": [
>         0.584819703641844,
>         0.8304020727976527,
>         21356
>       ],
>       "vot.analysis.measures.EAO": 0.403071790933609
>     }
>   ],
>   "unsupervised": [
>     {
>       "tracker_name": "DiMP",
>       "vot.analysis.measures.AverageAccuracy": [
>         0.4561690706823326,
>         21356
>       ]
>     }
>   ],
>   "realtime": [
>     {
>       "tracker_name": "DiMP",
>       "vot.analysis.measures.AccuracyRobustness": [
>         0.5679649140410385,
>         1.0720640569395017,
>         21356
>       ],
>       "vot.analysis.measures.EAO": 0.36817267537117004
>     }
>   ]
> }
> ```
> 
> The parameter I use is dimp50_vot.py,dataset is vot2018,I don't change the code,is it stricter for lower performance? @goutamgmb

Hello, how do you run in python toolkit. When I run with vot-toolkit-python, it will core dumped. @sherlockedlee

**Comment by sherlockedlee** [comment]
> > Sorry to bother you again.The results of python-toolkit as follows:
> > ```
> > 
> > {
> >   "baseline": [
> >     {
> >       "tracker_name": "DiMP",
> >       "vot.analysis.measures.AccuracyRobustness": [
> >         0.584819703641844,
> >         0.8304020727976527,
> >         21356
> >       ],
> >       "vot.analysis.measures.EAO": 0.403071790933609
> >     }
> >   ],
> >   "unsupervised": [
> >     {
> >       "tracker_name": "DiMP",
> >       "vot.analysis.measures.AverageAccuracy": [
> >         0.4561690706823326,
> >         21356
> >       ]
> >     }
> >   ],
> >   "realtime": [
> >     {
> >       "tracker_name": "DiMP",
> >       "vot.analysis.measures.AccuracyRobustness": [
> >         0.5679649140410385,
> >         1.0720640569395017,
> >         21356
> >       ],
> >       "vot.analysis.measures.EAO": 0.36817267537117004
> >     }
> >   ]
> > }
> > ```
> > 
> > 
> > The parameter I use is dimp50_vot.py,dataset is vot2018,I don't change the code,is it stricter for lower performance? @goutamgmb
> 
> Hello, how do you run in python toolkit. When I run with vot-toolkit-python, it will core dumped. @sherlockedlee

Hi,can you provide more details about your problem? I just follow the tuturial https://www.votchallenge.net/howto/tutorial_python.html

**Comment by DeepBrainsMe** [comment]
"tracker_name": "DiMP",
      "vot.analysis.measures.AccuracyRobustness": [
      A  0.584819703641844,
      B  0.8304020727976527,
      C  21356
Here are there index. I wonder  know what the above three indicators  A,B,Crepresent?

**Comment by goutamgmb** [comment]
@xiaolin13  I have also encountered the core dumped issue once, but the evaluation worked on trying again. I do not have any idea about what is causing the core dump.

**Comment by goutamgmb** [comment]
@DeepBrainsMe A is the accuracy, i.e. average overlap over the tracked frames. B is the robustness which is computed as the fraction of sequence tracked before failure. e.g. if a tracker fails on the 80th frame in a sequence of length 100, then the robustness is 0.8. C is the total number of frames in the evaluation. So it only depends on the dataset, and is independent of the tracker.
