### ISSUE TITLE
How long does it  take to test in test dateset about ATOM?

### ISSUE THREAD

**Issue by meimeixu520** [visionml/pytracking#141]
HI,thanks for you brilliant work,can you tell me how long does the tracker called ATOM test will take in every test dataset?I  need much time to test in UAV,Lasot and other datasets.Does it  have some problem?

**Comment by martin-danelljan** [comment]
On a single machine, 5 complete runs take about 8 hours on UAV and ~20 hours on LaSOT on an 1080ti. You can run 5 trackers in parallell with the `--threads 5` option.

**Comment by meimeixu520** [comment]
Thanks  for  your reply!How many gpu  do you use when you test?I was very slow to test,Is this because I'm using HDDS instead of SSDS?
I also meet  a problem,the test process is correct,but the result about Lasot and TrackingNet  is wrong,specifically,Data chaos, fewer lines of data, more lines of data,such as:
![Uploading X]43%6)D9Z(S_4EP%CJP_3R.jpg…]()
![Y_7@NS~ZB8N4 UPQN{_IIY5](https://user-images.githubusercontent.com/37978749/80311157-96424080-8810-11ea-9940-49b145727a85.jpg)

Can you tell me the reason?
Best regards!

**Comment by martin-danelljan** [comment]
I have never seen these issues. There might be something wrong with your file system or your hard drive.

Regarding slow speed, this I cannot help you with. From this respect, PyTracking is not much different from other deep learning frameworks. So just use common sense and look around for information.
