### ISSUE TITLE
I have test your code(atom_default.pth from your google drive) use pysot_toolkit(https://github.com/StrangerZhang/pysot-toolkit) .

### ISSUE THREAD

**Issue by xiaolin13** [visionml/pytracking#143]
I have test your code(atom_default.pth from your google drive) use pysot_toolkit(https://github.com/StrangerZhang/pysot-toolkit) .
However  I didn't get the same EAO score as your paper ,only  0.361  average 15 times.
 The details code  I have sent to Goutam，I wonder where the bugs stay.

_Originally posted by @DeepBrainsMe in https://github.com/visionml/pytracking/issues/14#issuecomment-504718118_

**Comment by xiaolin13** [comment]
I only got 0.331 average score when using pysot-toolkit. It's far from paper 0.401.

**Comment by martin-danelljan** [comment]
Hi. We have never tried running the VOT evaluation on the pysot toolkit. We always use the *official* VOT toolkit. However, even that is difficult since the python/pytorch support for the old (pre-2020) VOT toolkit has been limited, and due to constant changes in the official toolkit.
