### ISSUE TITLE
sub pixel bounding box estimates?

### ISSUE THREAD

**Issue by aakif1996-blip** [visionml/pytracking#145]
Hi,

would it be possible to get the bounding box estimates that are accurate to sub-pixel limit for the atom/dimp tracker ?

**Comment by martin-danelljan** [comment]
Hi. The tracker returns sub-pixel box estimates yes. We havent analyzed the sub-pixel accuracy, but this really depends on the data. In many scenarios, for instance when you have even slight motion blur, a sub-pixel definition of the bounding box does not really makes sense.

**Comment by aakif1996-blip** [comment]
Thank you @martin-danelljan  for the prompt reply and yes your reason makes perfect sense to me to have an integer level precison. But i  would still be interested to see the results with actual sub-pixel estimates in my sub-pixel precise data. 

Will modifications in pytracking/pytracking/evaluation/tracker.py  suffice in that that case ?
(at Lines 307, 349 and 351 to be precise. Lines 307 is quite problematic to modify due to the fact that the estimates are used to plot the frame while visualizing )
and if it isn't too much of a trouble could you tell me the needed modifications.

Thanks in advance!

**Comment by aakif1996-blip** [comment]
Well, I figured it out myself. Thank you very much for all the help and useful insights.

**Comment by martin-danelljan** [comment]
The bounding boxes directly output by the DiMP or ATOM tracker classes are floating point.

If you want the most accurate boxes, then use the SuperDiMP setting, as those boxes are much more accurate.
