### ISSUE TITLE
Can we run the dimp without having GPU in my laptop

### ISSUE THREAD

**Issue by shah0nawaz** [visionml/pytracking#146]
HI sir,

I have corei5 5th gen laptop I want to run dimp my customized dataset of video.
is it possible without having  GPU.

**Comment by goutamgmb** [comment]
Unfortunately not as the PreciseRoI pooling layer cannot be compiled for CPU. Check https://github.com/visionml/pytracking/issues/128#issuecomment-599211927 for more information.

**Comment by shah0nawaz** [comment]
In the vot2019 paper for dimp, they have mentioned that SPC means stochastic, python and CPU then what does it means by that.

**Comment by goutamgmb** [comment]
That is an error in the vot19 paper. It should be SPG.
