### ISSUE TITLE
ninja: build stopped: subcommand failed. Error building extension '_prroi_pooling'

### ISSUE THREAD

**Issue by zhuyabin** [visionml/pytracking#149]
prroi_pooling_gpu_impl.cuh:1:1: error: expected unqualified-id before ‘.’ token
 ../../../src/prroi_pooling_gpu_impl.cuh
 ^
ninja: build stopped: subcommand failed.
Error building extension '_prroi_pooling'

**Comment by zhuyabin** [comment]
My code environment:
ubuntu16.04
python3.7
pytorch1.0 (1.2,1.4,1.5 are tested)
cuda10.0

**Comment by martin-danelljan** [comment]
Hi, check [this answer](https://github.com/visionml/pytracking/issues/151#issuecomment-632370461).
