### ISSUE TITLE
Seq KiteSurf etx error in otb

### ISSUE THREAD

**Issue by xyc2690** [visionml/pytracking#15]
In the file pytracking/pytracking/evaluation/otbdataset.py 
 line: 123
 {"name": "KiteSurf", "path": "KiteSurf/img", "startFrame": 1, "endFrame": 84, "nz": 4, "ext": "png", "anno_path": "KiteSurf/groundtruth_rect.txt"},

The 'ext' should be "jpg" instead of "png" for the latest version of OTB dataset.

**Comment by goutamgmb** [comment]
With the latest code, both "jpg" and "png" extensions should work. Thanks for notifying the issue!
