### ISSUE TITLE
Results on OTB-100, UAV-123, VOT-2019

### ISSUE THREAD

**Issue by MMarvasti** [visionml/pytracking#152]
Hi @martin-danelljan , @goutamgmb ,

I couldn't find your results for ATOM and DiMP trackers on OTB-100 and UAV-123 datasets, although you compared them according to their precision and success curves. Could you please provide them on your GitHub or google drive?
Thanks in advance,

Mojtaba

**Comment by goutamgmb** [comment]
The results are available here https://drive.google.com/drive/folders/1sajCOYU_dIILS0gP0RPLVfXSW_mo4rMi. Check https://github.com/visionml/pytracking/blob/master/MODEL_ZOO.md#raw-results for more details.

**Comment by MMarvasti** [comment]
Thanks for your reply, @goutamgmb 
I have a question. We used your codes to test the ATOM and DiMP trackers on the VOT-2019 dataset. But, there is a difference between the reported results on the VOT-results paper and the results produced by your codes with default parameters. Please let me know what the problem is.
Thank you in advance.

**Comment by goutamgmb** [comment]
How large is the difference? What results do you obtain?

**Comment by MMarvasti** [comment]
![PyTracking_VOT2019](https://user-images.githubusercontent.com/24586420/82834977-ec41ec80-9e7f-11ea-8bd1-335ee69adcff.jpg)

**Comment by goutamgmb** [comment]
That is strange. To be clear, you ran with the parameters dimp50_vot19.py, for 15 runs?
