### ISSUE TITLE
Could you supply the results(.txt) of different trackers on UAV123 dataset?

### ISSUE THREAD

**Issue by Jack-zhangluyao** [visionml/pytracking#154]
Hi! Thank you for your wonderful work!  I want to test my tracker and DiMP tracker on UAV123 dataset. For generating plots, could you supply some famous tracking results of different trackers  on UAV123 or where can I look for these tracking results? Thanks in advance!

**Comment by goutamgmb** [comment]
Hi,

Apologies for delayed response. We have uploaded the results for a number of trackers at https://drive.google.com/drive/folders/1bwD0unt4cvVROat_yjBp4OPkdJEIyGpz. You can download and unpack these results using the download_results script https://github.com/visionml/pytracking/blob/master/pytracking/util_scripts/download_results.py.
