### ISSUE TITLE
RuntimeError: CUDA out of memory. 

### ISSUE THREAD

**Issue by missyoudaisy** [visionml/pytracking#155]
Hello! When I test DiMP on the vot 2019rgbt dataset, the problem "RuntimeError: CUDA out of memory. Tried to allocate 66.00 MiB" occurred, what should I do to solve this problem?
Thanks~

**Comment by goutamgmb** [comment]
The memory usage of the tracker can be reduced by either reducing the parameters 'sample_memory_size', or 'image_sample_size'. This can of course lead to a decrease in tracker performance.

**Comment by missyoudaisy** [comment]
Thanks for your kind reply
