### ISSUE TITLE
KeyError: 'Nf1aqv5Fg5o_0'

### ISSUE THREAD

**Issue by meimeixu520** [visionml/pytracking#156]
Hi,thanks your excellent work. When I train ATOM using the setting 'atom_paper.py',it uses the dataset TrackingNet,then  shows the KeyError,but the dataset is correct.Can you tell me why?Look foward your reply!
Best regards!

**Comment by meimeixu520** [comment]
![image](https://user-images.githubusercontent.com/37978749/83344871-252a0780-a33f-11ea-9ea1-9727f1eec230.png)

**Comment by meimeixu520** [comment]
the  error is as follows:

Training:  bbreg  atom_paper
Traceback (most recent call last):
  File "run_training.py", line 56, in <module>
    main()
  File "run_training.py", line 51, in main
    run_training(args.train_module, args.train_name, args.cudnn_benchmark)
  File "run_training.py", line 40, in run_training
    expr_func(settings)
  File "../ltr/train_settings/bbreg/atom_paper.py", line 27, in run
    trackingnet_train = TrackingNet(settings.env.trackingnet_dir, set_ids=list(range(11)))
  File "../ltr/dataset/tracking_net.py", line 71, in __init__
    self.seq_to_class_map, self.seq_per_class = self._load_class_info()
  File "../ltr/dataset/tracking_net.py", line 86, in _load_class_info
    class_name = seq_to_class_map[seq[1]]
KeyError: 'Nf1aqv5Fg5o_0'

**Comment by goutamgmb** [comment]
Hi,

Thanks for notifying the issue. I am not entirely sure why the class name is missing for that sequence. Anyways I have pushed a fix for the issue. Could you try again with the latest commit?

**Comment by meimeixu520** [comment]
Great，it  works!But  I  account for another error,for example:
![image](https://user-images.githubusercontent.com/37978749/83769202-27c78c80-a6b2-11ea-8cf5-5295e8e094b5.png)
I check the parameters ,it is correct,so I don't know why it is wrong.Can you tell me?
Best regards!

**Comment by goutamgmb** [comment]
It was another bug introduced in the latest release :(. I have fixed it now. Can you check again?

**Comment by meimeixu520** [comment]
OK,it starts trainning!Thanks for your reply! 
I have another question,in the tracking prase,pytracking/pytracking/tracker/base/basetracker.py,it changes a lot,there is no previous initialization process.So how  does it initialize?

**Comment by meimeixu520** [comment]
when it run through the seventh epoch,it produces the following error:
![image](https://user-images.githubusercontent.com/37978749/83828575-94bf3e80-a713-11ea-8061-74dc245e8296.png)

**Comment by goutamgmb** [comment]
Regarding the first question, I am not sure what do you mean. Could you please clarify?

Regarding the "too small bounding box" issue, yes we have seen this issue before. We will try to fix it.

**Comment by danielism97** [comment]
Hi,

The commit to fix this issue seems to have missed out other parts of the code that can raise the key error. E.g. in the same file (tracking_net.py) line 126 in function `_get_class`:

```
def _get_class(self, seq_id):
    seq_name = self.sequence_list[seq_id][1]
    return self.seq_to_class_map[seq_name]
```

Thanks

**Comment by lerohiso** [comment]
you can fix the "KeyError" by adding "Nf1aqv5Fg5o_0 airplane" line in trackingnet_classmap.txt file

**Comment by meimeixu520** [comment]
Thank your reply,can you add my wechat,19966519787,then can you send me the picture or the way of solving the problem!Thanks very much!
Best wishes!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "visionml/pytracking"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月10日(星期四) 下午3:38
收件人:&nbsp;"visionml/pytracking"<pytracking@noreply.github.com&gt;;
抄送:&nbsp;"别做白日梦了??"<1398629150@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [visionml/pytracking] KeyError: 'Nf1aqv5Fg5o_0' (#156)





 
you can fix the "KeyError" by adding "Nf1aqv5Fg5o_0 airplane" line in trackingnet_classmap.txt file

**Comment by martin-danelljan** [comment]
@lerohiso Thank you very much for giving the solution! It should be fixed now.

**Comment by zj717754140** [comment]
I clone repo on Aug,I also meet the same problem KeyError: 'Nf1aqv5Fg5o_0' in Training.

`KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jzhang/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jzhang/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jzhang/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jzhang/VisualTracking/pytracking/ltr/data/sampler.py", line 159, in __getitem__
    train_frames, train_anno, meta_obj_train = dataset.get_frames(seq_id, train_frame_ids, seq_info_dict)
  File "/home/jzhang/VisualTracking/pytracking/ltr/dataset/tracking_net.py", line 143, in get_frames
    obj_class = self._get_class(seq_id)
  File "/home/jzhang/VisualTracking/pytracking/ltr/dataset/tracking_net.py", line 126, in _get_class
    return self.seq_to_class_map[seq_name]
KeyError: 'Nf1aqv5Fg5o_0'`

**Comment by martin-danelljan** [comment]
@zj717754140 When was "recently" exactly? Can you try pulling first?
