### ISSUE TITLE
I also want to run the vot 2020 but I feel confuse about the trackers.ini

### ISSUE THREAD

**Issue by chenlyuzhao** [visionml/pytracking#158]
Can you please explain how does "command " in trackers.ini works? Thank you very much.

**Comment by goutamgmb** [comment]
The command is called from the vot-toolkit. You need to set the tracker name and the parameter name.

`command = import pytracking.run_vot as run_vot; run_vot.run_vot2020('dimp', 'dimp50')`

For instance, here dimp50 parameter setting from the dimp tracker will be run.
