### ISSUE TITLE
mutiobject tracking with dimp

### ISSUE THREAD

**Issue by shah0nawaz** [visionml/pytracking#159]
HI sir,
I want to use run_video.py file with dimp tracker in multi object mode.
I mean, how can I track multiple targets in single frame or frames of a video.
Please guide me how can i do this.

Many Thanks

**Comment by goutamgmb** [comment]
Hi,

Unfortunately multi object mode is not enabled currently with run_video.py. It should be easy to implement it, similar to the way it is done in run_webcam. We hope to add this functionality soon.

**Comment by shah0nawaz** [comment]
> Hi,
> 
> Unfortunately multi object mode is not enabled currently with run_video.py. It should be easy to implement it, similar to the way it is done in run_webcam. We hope to add this functionality soon.

How can I use it in run_webcam.py ?
Please help

**Comment by goutamgmb** [comment]
You can select multiple regions to track in run_webcam (by drawing bounding boxes in the GUI).

**Comment by shah0nawaz** [comment]
> You can select multiple regions to track in run_webcam (by drawing bounding boxes in the GUI).

Thank you sir

**Comment by PhenomenalOnee** [comment]
Add this function inside tracker.py Trcaker class
def run_video_multi(self, videofilepath, optional_box=None, debug=None, visdom_info=None, save_results=False):
        """Run the tracker with the vieofile.
        args:
            debug: Debug level.
        """

        params = self.get_parameters()

        debug_ = debug
        if debug is None:
            debug_ = getattr(params, 'debug', 0)
        params.debug = debug_

        params.tracker_name = self.name
        params.param_name = self.parameter_name
        self._init_visdom(visdom_info, debug_)

        multiobj_mode = getattr(params, 'multiobj_mode', getattr(self.tracker_class, 'multiobj_mode', 'default'))

        if multiobj_mode == 'default':
            tracker = self.create_tracker(params)
            if hasattr(tracker, 'initialize_features'):
                tracker.initialize_features()

        elif multiobj_mode == 'parallel':
            tracker = MultiObjectWrapper(self.tracker_class, params, self.visdom, fast_load=True)
        else:
            raise ValueError('Unknown multi object mode {}'.format(multiobj_mode))

        assert os.path.isfile(videofilepath), "Invalid param {}".format(videofilepath)
        ", videofilepath must be a valid videofile"

        output_boxes = []

        cap = cv.VideoCapture(videofilepath)
        cap.set(cv.CAP_PROP_POS_FRAMES, 60-1)
        display_name = 'Display: ' + tracker.params.tracker_name
        cv.namedWindow(display_name, cv.WINDOW_NORMAL | cv.WINDOW_KEEPRATIO)
        cv.resizeWindow(display_name, 960, 720)
        success, frame = cap.read()
        cv.imshow(display_name, frame)

        def _build_init_info(boxes):
            info = OrderedDict()
            prev_output = OrderedDict()
            info['previous_output'] = prev_output
            info['init_bbox'] = OrderedDict()
            info['init_object_ids'] = []
            info['object_ids'] = []
            info['sequence_object_ids'] = []
            for i,box in enumerate(boxes):
                i+=1
                info['init_bbox'][i] = list(box)
                info['init_object_ids'].append(i)
                info['object_ids'].append(i)
                info['sequence_object_ids'].append(i)
          

               
            #return {'init_bbox': OrderedDict({1: box}), 'init_object_ids': [1, ], 'object_ids': [1, ],
            #        'sequence_object_ids': [1, ]}
            #print('Info',info)
            return info

        if success is not True:
            print("Read frame from {} failed.".format(videofilepath))
            exit(-1)
        if optional_box is not None:
            assert isinstance(optional_box, (list, tuple))
            assert len(optional_box) == 4, "valid box's foramt is [x,y,w,h]"
            tracker.initialize(frame, _build_init_info(optional_box))
            #output_boxes.append(optional_box)
        else:
            while True:
                # cv.waitKey()
                frame_disp = frame.copy()

                cv.putText(frame_disp, 'Select target ROI and press ENTER', (20, 30), cv.FONT_HERSHEY_COMPLEX_SMALL,
                           1.5, (0, 0, 0), 1)

                rois = cv.selectROIs(display_name, frame_disp, False,False)
                init_state = rois
                int_state = _build_init_info(init_state)
                #tracker.initialize(frame, int_state)
                #output_boxes.append(init_state)
                break

        firstint = True
        prev_output = OrderedDict()
        sequence_object_ids = []
        while True:
            ret, frame = cap.read()

            if frame is None:
                break

            if self.initwriter:
                fourcc = cv.VideoWriter_fourcc(*"MJPG")
                writer = cv.VideoWriter("OUTPUT.avi", fourcc, 25,(frame.shape[1], frame.shape[0]), True)
                self.initwriter = False


            frame_disp = frame.copy()

            info = OrderedDict()
            info['previous_output'] = prev_output
            if firstint:
                info = int_state
                sequence_object_ids = info['sequence_object_ids']
                firstint=False

            if len(sequence_object_ids) > 0:
                info['sequence_object_ids'] = sequence_object_ids

            # Draw box
            #out = tracker.track(frame)
            #print('input info',info)
            out = tracker.track(frame, info)
            #print('output info',out)
            prev_output = OrderedDict(out)

            if 'target_bbox' in out:
                for obj_id, state in out['target_bbox'].items():
                    state = [int(s) for s in state]
                    cv.rectangle(frame_disp, (state[0], state[1]), (state[2] + state[0], state[3] + state[1]),_tracker_disp_colors[obj_id], 5)

            # Put text
            font_color = (0, 0, 0)
            cv.putText(frame_disp, 'Select target', (20, 30), cv.FONT_HERSHEY_COMPLEX_SMALL, 1, font_color, 2)
            cv.putText(frame_disp, 'Press q to quit', (20, 85), cv.FONT_HERSHEY_COMPLEX_SMALL, 1,
                       font_color, 2)
            cv.putText(frame_disp, 'Press r to reset', (20, 150), cv.FONT_HERSHEY_COMPLEX_SMALL, 1,
                       font_color, 2)

            # Display the resulting frame
            cv.imshow(display_name, frame_disp)
            writer.write(frame_disp)
            key = cv.waitKey(1)
            if key == ord('q'):
                break
            if key == ord('r'):
                while True:
                    cv.imshow(display_name, frame)
                    frame_disp = frame.copy()
                    cv.putText(frame_disp, 'Select target ROI and press ENTER', (20, 30), cv.FONT_HERSHEY_COMPLEX_SMALL,
                           1.5, (0, 0, 0), 1)

                    rois = cv.selectROIs(display_name, frame_disp, False,False)
                    init_state = rois
                    int_state = _build_init_info(init_state)
                    break
                
                sequence_object_ids = []
                prev_output = OrderedDict()

                info = OrderedDict()

                info['object_ids'] = []
                info['init_object_ids'] = []
                info['init_bbox'] = OrderedDict()
                tracker.initialize(frame, info)
                firstint = True
                
        # When everything done, release the capture
        cap.release()
        writer.release()
        cv.destroyAllWindows()

Note: Add class variable self.initwriter=True to write the output video. 

Enjoy

**Comment by shah0nawaz** [comment]
Thank you sir
