### ISSUE TITLE
Can I run a tracker on a video?

### ISSUE THREAD

**Issue by swchaipat** [visionml/pytracking#16]
I saw a python file named run_video.py, which I guess it allows me to test the tracker on a video. 
So, I run the following command in the command line: 

**python run_video.py atom default ~/Videos/PETS09-S2L1.mp4**

But, I got the following error

I investigated the error and found that it failed to load a feature extractor network in 
**/pytracking/features/deep.py** and returns the following error:

**_pickle.UnpicklingError: invalid load key, '<'.**

Could you please tell me what am I missing here?

**Comment by goutamgmb** [comment]
Hi,
Which version of PyTorch are you using? 0.4.1 or 1.0?

**Comment by dongfangduoshou123** [comment]
run with web cam is ok？I think your model is downloaded wrong or pytorch version is not ok.

**Comment by swchaipat** [comment]
My PyTorch version is 0.4.1. I installed it using the provided script from this repository named **install.sh**. , which contains the following command: 

**conda install -y pytorch=0.4.1 torchvision cuda92 -c pytorch** 

I haven't tried with a webcam yet, because my camera is broken.

**Comment by swchaipat** [comment]
I have already fixed the problem. The link for downloading the ATOM model in the shell script is incorrect, so the loaded model was broken. I obtain the working model from **"detailed installation instruction"**

**Comment by goutamgmb** [comment]
Great! Thanks for notifying. I think the link in the shell script should be fine, but probably there was some issue while downloading. We also encountered this issue once. We will try to modify the download script so that it can notify in case of failures.
