### ISSUE TITLE
The structure of NFS dataset is different from it described in NFSDataset.py.

### ISSUE THREAD

**Issue by iminfine** [visionml/pytracking#160]
I download the NFS dataset from the official website. The structure of NFS dataset is:

---NFS
------airboard_1
---------30
------------airboard_1
---------------airboard_1.txt
---------240
------------airboard_1
---------------airboard_1.txt

which is different from the structure described in NFSDataset.py. And the ground truth
files of 30FPS and 240FPS versions are the same with x1y1x2y2 structure. Your code read them as xywh and do not ship the frames that do not exist in the 30FPS version.

I guess you did some preprocessing. Could you please provide the script?

**Comment by goutamgmb** [comment]
Hi,

I have uploaded the processed dataset  at https://drive.google.com/file/d/1VgA-iJV8HMLm8Yn4ntMPF19RajugxgbW/view?usp=sharing. We generated the groundtruth for the 30 FPS version using the results available on the NFS website. The tracker result mat files contains the annotation, although we have observed that there are some syncing issues in some cases.

**Comment by iminfine** [comment]
Thanks,
Please give me permission to download the dataset.

**Comment by goutamgmb** [comment]
You should be able to download now!

**Comment by iminfine** [comment]
Got it, thanks.
