### ISSUE TITLE
No module named 'ltr.external.PreciseRoIPooling.pytorch'

### ISSUE THREAD

**Issue by frankie-chan-ck** [visionml/pytracking#163]
I am new to this. After run the test command: python run_webcam.py dimp dimp50,  a problem occoured  : "No module named ltr.external.PreciseRoIPooling.pytorch" . The path of "/ltr/external/PreciseRoIPooling/"  has  no files at all, I confirmed. How to get rid of this?

**Comment by martin-danelljan** [comment]
You will find the [instruction here](https://github.com/visionml/pytracking#clone-the-submodules).

**Comment by frankie-chan-ck** [comment]
> You will find the [instruction here](https://github.com/visionml/pytracking#clone-the-submodules).

Thank you very much. I have solved this problem with help to the question at https://github.com/visionml/pytracking/issues/144. Many thanks to your work!

**Comment by TANGBAISUI** [comment]
> （pytracking-master） gtx1080@gtx1080：~/pytracking-master/pytracking$ python run_webcam.py dimp dimp50回溯（最近一次调用）：文件 “run_webcam.py”，第 41 行，在 main（）File “run_webcam.py” 中，第 37 行，在mainrun_webcam（args.tracker_name， args.tracker_param， args.debug， visdom_info）File “run_webcam.py”， 第 21 行， in run_webcamtracker = Tracker（tracker_name， tracker_param）文件“../pytracking/evaluation/tracker.py“，第 64 行，**init**tracker_module = importlib.import_module（'pytracking.tracker.{}'.format（self.name））文件 “/home/gtx1080/anaconda3/lib/python3.7/importlib/**init**.py”，第 127 行，import_module返回 _bootstrap._gcd_import（name[level：]， package， level）File “”， 第 1006 行，在_gcd_import文件 “”中，第 983 行，在_find_and_load文件 “”中，第 967 行，在_find_and_load_unlocked文件 “” 中，第 677 行，在_load_unlocked文件 “” 中，第 728 行，在 exec_module 中文件 “”，第 219 行，在_call_with_frames_removed文件 “../pytracking/tracker/dimp/**init**.py“，第 1 行，来自.dimp import DiMP文件 ”../pytracking/tracker/dimp/dimp.py“，第 12 行，从ltr.models.target_classifier.initializer import FilterInitializerZeroFile ”../ltr/models/target_classifier/initializer.py“，第 4 行，从ltr.external.PreciseRoIPooling.pytorch.prroi_pool导入 PrRoIPool2DModuleNotFoundError：没有名为”ltr.external.PreciseRoIPooling.pytorch“的模块
> 
> pytorch==1.5.0 ，CUDA 版本 10.0.130，#define CUDNN_MAJOR 7 和 ubuntu 16.04



> > You will find the [instruction here](https://github.com/visionml/pytracking#clone-the-submodules).
> 
> Thank you very much. I have solved this problem with help to the question at #144. Many thanks to your work!

How do you do it?

**Comment by TANGBAISUI** [comment]
> > You will find the [instruction here](https://github.com/visionml/pytracking#clone-the-submodules).
> 
> Thank you very much. I have solved this problem with help to the question at #144. Many thanks to your work!

How do you do it?Thank you very much.
