### ISSUE TITLE
Difference between run_vot() and run_vot2020()

### ISSUE THREAD

**Issue by HubHop** [visionml/pytracking#165]
Hi, I was wondering if there is any difference between the two evaluation functions. I trained DiMP-18 on the four datasets(COCO, GOT10k, LaSot, TrackingNet) with batch size = 13 on a single GPU. After training, I evaluated the model with vot-toolkit-python on VOT2018 dataset.

Here are my results after evaluating the final model with run_vot2020():
```
{
    "baseline": [
      {
        "tracker_name": "DiMP",
        "vot.analysis.measures.AccuracyRobustness": [
          0.5569516403031995,
          0.9598988574639445,
          21356
        ],
        "vot.analysis.measures.EAO": 0.34218350052833557
      }
    ],
    "unsupervised": [
      {
        "tracker_name": "DiMP",
        "vot.analysis.measures.AverageAccuracy": [
          0.46796157142173855,
          21356
        ]
      }
    ],
    "realtime": [
      {
        "tracker_name": "DiMP",
        "vot.analysis.measures.AccuracyRobustness": [
          0.5562728603002569,
          1.655412998688893,
          21356
        ],
        "vot.analysis.measures.EAO": 0.23850557208061218
      }
    ]
  }
```

Evaluating the final model with run_vot():
```
{
    "baseline": [
      {
        "tracker_name": "DiMP",
        "vot.analysis.measures.AccuracyRobustness": [
          0.5660411504820083,
          0.8341574577011924,
          21356
        ],
        "vot.analysis.measures.EAO": 0.37420332431793213
      }
    ],
    "unsupervised": [
      {
        "tracker_name": "DiMP",
        "vot.analysis.measures.AverageAccuracy": [
          0.4789336216261096,
          21356
        ]
      }
    ],
    "realtime": [
      {
        "tracker_name": "DiMP",
        "vot.analysis.measures.AccuracyRobustness": [
          0.5514909944237275,
          2.0626053568083913,
          21356
        ],
        "vot.analysis.measures.EAO": 0.2046097069978714
      }
    ]
  }
```
I can't reproduce the same results of the original paper, where the EAO for DiMP-18  on the VOT2018 dataset is 0.402. I notice that the default batch size is 26, which is beyond my GPU capacity (NVIDIA TESLA V100), so I halve the batch size into 13. Is the training process sensitive to batch size or something else?

**Comment by goutamgmb** [comment]
Hi,

The run_vot() script evaluates the model using the old vot toolkit, while the run_vot2020 script evaluates the model using the new python toolkit. Note that the python toolkit (vot2020) uses a different evaluation criteria compared to the old vot toolkits (see https://data.votchallenge.net/vot2020/vot-2020-protocol.pdf for details). Thus, you need to use the old vot toolkit to run the tracker as well as compute EAO score. 

Regarding the batch size, we haven't tried training a model with smaller batch size, but I do not think the batch size should have such a big impact on performance.

**Comment by xiaotian3** [comment]
> Hi, I was wondering if there is any difference between the two evaluation functions. I trained DiMP-18 on the four datasets(COCO, GOT10k, LaSot, TrackingNet) with batch size = 13 on a single GPU. After training, I evaluated the model with vot-toolkit-python on VOT2018 dataset.
> 
> Here are my results after evaluating the final model with run_vot2020():
> 
> ```
> {
>     "baseline": [
>       {
>         "tracker_name": "DiMP",
>         "vot.analysis.measures.AccuracyRobustness": [
>           0.5569516403031995,
>           0.9598988574639445,
>           21356
>         ],
>         "vot.analysis.measures.EAO": 0.34218350052833557
>       }
>     ],
>     "unsupervised": [
>       {
>         "tracker_name": "DiMP",
>         "vot.analysis.measures.AverageAccuracy": [
>           0.46796157142173855,
>           21356
>         ]
>       }
>     ],
>     "realtime": [
>       {
>         "tracker_name": "DiMP",
>         "vot.analysis.measures.AccuracyRobustness": [
>           0.5562728603002569,
>           1.655412998688893,
>           21356
>         ],
>         "vot.analysis.measures.EAO": 0.23850557208061218
>       }
>     ]
>   }
> ```
> 
> Evaluating the final model with run_vot():
> 
> ```
> {
>     "baseline": [
>       {
>         "tracker_name": "DiMP",
>         "vot.analysis.measures.AccuracyRobustness": [
>           0.5660411504820083,
>           0.8341574577011924,
>           21356
>         ],
>         "vot.analysis.measures.EAO": 0.37420332431793213
>       }
>     ],
>     "unsupervised": [
>       {
>         "tracker_name": "DiMP",
>         "vot.analysis.measures.AverageAccuracy": [
>           0.4789336216261096,
>           21356
>         ]
>       }
>     ],
>     "realtime": [
>       {
>         "tracker_name": "DiMP",
>         "vot.analysis.measures.AccuracyRobustness": [
>           0.5514909944237275,
>           2.0626053568083913,
>           21356
>         ],
>         "vot.analysis.measures.EAO": 0.2046097069978714
>       }
>     ]
>   }
> ```
> 
> I can't reproduce the same results of the original paper, where the EAO for DiMP-18 on the VOT2018 dataset is 0.402. I notice that the default batch size is 26, which is beyond my GPU capacity (NVIDIA TESLA V100), so I halve the batch size into 13. Is the training process sensitive to batch size or something else?

why I can only run_vot2020?when I run use run_vot , it will enconut a problem? how can you use run_vot?
