### ISSUE TITLE
parameter file  for PrDiMP on VOT

### ISSUE THREAD

**Issue by chenfsjz** [visionml/pytracking#169]
HI, I try to test the PrDiMP on vot2018 dataset, and there is only prdimp50.py. Does this parameter is used for both the vot and other datasets?

**Comment by martin-danelljan** [comment]
Hi. Thanks for notifying that I had forgot.

Pushed now!

We will soon also push VOT2020 parameter files for all trackers.

Regards,
Martin

**Comment by chenfsjz** [comment]
Thank you for your new uploaded parameter files! One more question, does the prdimp50_vot2018 can also be used to vot2016 dataset? Because we want to test the model on vot2016.
Thank your attention!
