### ISSUE TITLE
PyTracking on AMD Radeons

### ISSUE THREAD

**Issue by xQsM3** [visionml/pytracking#170]
Hello,

I now figured that CUDA is only supported by NVIDIA gpu's. Is there any way for me to run the pytracker without CUDA or to translate the CUDA kernels to C++ with for example HIP (https://github.com/ROCm-Developer-Tools/HIP) ? Does someone has experience with it and could explain me how to set it up? Unfortunately, my knowledge is not enough to do so.

Thank you for help

**Comment by martin-danelljan** [comment]
Hi. Basically, you need to implement a new backend for PyTorch ...

My advice is: spare yourself of weeks or months of work, and simply buy an NVIDIA GPU. If you are only interested in inference, then even a low-end one is enough (4 GB memory minimum). For training, at least 8 GB is good though (the 1080 or 2080 series).

Regards,
Martin
