### ISSUE TITLE
Pytorch 1.5.0+ unsupported: Integer division using div is deprecated/unsupported (DiMP)

### ISSUE THREAD

**Issue by karlHolmquist** [visionml/pytracking#172]
Hi,

I encountered a problem regarding using the run_webcam.py script with pytorch 1.6.
Pytorch seems to have deprecated integer division in 1.5 and removed it completely in 1.6 that makes the preprocessing done (for dimp at least) crash. (see [https://pytorch.org/docs/stable/generated/torch.div.html](https://pytorch.org/docs/stable/generated/torch.div.html))

**Comment by martin-danelljan** [comment]
Hi Karl! :D

Thanks for the issue. I did not have time to try it on 1.6 yet. Should be simple to fix. We will try to do it ASAP!

Regards,
Martin

**Comment by goutamgmb** [comment]
Hey Karl!

I have fixed the issue with integer division in preprocessing. The run_webcam.py script should work with pytorch 1.6 now.

**Comment by karlHolmquist** [comment]
Awesome, 
Thanks Martin and Goutam! :D
