### ISSUE TITLE
Does got10k_vot_train_split.txt  include the vot video or not?

### ISSUE THREAD

**Issue by sallymmx** [visionml/pytracking#173]
Hi I'm not sure about this:
    Does got10k_vot_train_split.txt  include the vot video or not? If I want to do the experiment of vot datasets, should I use this or got10k_train_split.txt?

Thank you!

**Comment by martin-danelljan** [comment]
Hi.

Sorry for the confusion. It is the GOT10k training set, but excluding the 1k videos that are prohibited for training according to the VOT rules. See https://www.votchallenge.net/vot2020/participation.html for more info.

Regards,
Martin
