### ISSUE TITLE
Are there some mistakes with 'trackingnet_classmap.txt'?

### ISSUE THREAD

**Issue by shuida** [visionml/pytracking#175]
the sequence 'TrackingNet/TRAIN_1/frames/Nf1aqv5Fg5o_0' can't be found in 
'ltr/data_specs/trackingnet_classmap.txt'.

**Comment by goutamgmb** [comment]
Hi,

Thanks for the issue. Yes, there seems to be mistake here. We will try to fix it soon.

**Comment by lerohiso** [comment]
"Nf1aqv5Fg5o_0" is an airplane class.
you can just add "Nf1aqv5Fg5o_0 airplane" in trackingnet_classmap.txt file

**Comment by lerohiso** [comment]
"Nf1aqv5Fg5o_0" is the airplane class.
you can just add "Nf1aqv5Fg5o_0 airplane" in trackingnet_classmap.txt file

**Comment by martin-danelljan** [comment]
@lerohiso Thank you very much for giving the solution! It should be fixed now.
