### ISSUE TITLE
Fine-tuning LWL on custom VOS dataset

### ISSUE THREAD

**Issue by pvoigtlaender** [visionml/pytracking#176]
Hi,

I'd like to fine-tune LWL on a custom VOS dataset starting from the provided checkpoint (lwl_stage2.pth).
When I do
`python ltr/run_training.py lwl lwl_stage2`
it wants to load the checkpoint ltr/lwl/lwl_stage1/LWTLNet_ep0070.pth.tar which I couldn't find. But maybe I don't actually need it since the weights for this should also be in the lwl_stage2.pth checkpoint?
Can you please give me a pointer on how to handle the weight loading for my setup?

**Comment by goutamgmb** [comment]
Hi,

I would suggest making a separate training setting for your task. So copy the lwl_stage2.py file to e.g. lwl_stage2_finetune.py, change the datasets as needed, and copy the weights from lwl_stage2.pth checkpoint to initialize the network. 

You can copy the weights as done in lwl_stage1.py,
```
weights_path = os.path.join(settings.env.pretrained_networks, 'lwl_stage2.pth')
pretrained_weights = torch.load(weights_path)
net.load_state_dict(pretrained_weights)
```

**Comment by pvoigtlaender** [comment]
Thx, it's working now :)
