### ISSUE TITLE
How did you evaluate trackers on the combined datasets?

### ISSUE THREAD

**Issue by shuida** [visionml/pytracking#177]
Thanks for your great work and the well-desinged framework. Could you please share the toolkit for evaluating the trackers on combined OTB-100, NFS and UAV123 as well as other datasets with us?

**Comment by martin-danelljan** [comment]
Hi. This functionality is already present. Both in the [experiment file](https://github.com/visionml/pytracking/blob/master/pytracking/experiments/myexperiments.py) and the [evaluation script](https://github.com/visionml/pytracking/blob/master/pytracking/notebooks/analyze_results.ipynb) you can simply do, for example

`dataset = get_dataset('otb', 'nfs', 'uav')`

to get a combined dataset.

**Comment by shuida** [comment]
Sorry to disturb you. I only read the previous README.md and ignored the newest one. I'll read it carefully. Thanks for you reply.
