### ISSUE TITLE
weight regularization for the backbone of DiMP

### ISSUE THREAD

**Issue by shuida** [visionml/pytracking#179]
https://github.com/visionml/pytracking/blob/06d5d99c9a0265ee8e936db8698f5934c2a46ad2/ltr/train_settings/dimp/dimp18.py#L107
It's well known that weight regularization is the routine in deep learning. You only add regularization in training the model f in DiMP. Why don't you add regularization for the backbone? Have you ever tried that?

**Comment by martin-danelljan** [comment]
No, but this could be tried yes. I guess the risk is that it could start forgetting good imagenet features faster, which can be beneficial for generalization.

I would be interested to hear about your findings.

**Comment by shuida** [comment]
OK. I'll try it and share the findings with you. Thanks for your reply.
