### ISSUE TITLE
optimization of iounet boxes

### ISSUE THREAD

**Issue by shuida** [visionml/pytracking#188]
https://github.com/visionml/pytracking/blob/06d5d99c9a0265ee8e936db8698f5934c2a46ad2/pytracking/tracker/dimp/dimp.py#L745
Hello! I have a question about the optimization of iounet boxes. In your code, the bb_init is the absolute coordinate. It seems that the correct iteration is 
> output_boxes = bb_init + step_length * bb_init.grad

Why do you multiply the last item by bb_init[:, :, 2:]?

**Comment by martin-danelljan** [comment]
We adopted this formula from the IoUNet. The PrDiMP uses a different bounding box parametrization which is more intuitive and seems to give better results. Please check that function as well.
