### ISSUE TITLE
the problems of deploying pytracking on TX2

### ISSUE THREAD

**Issue by shenwenxiao** [visionml/pytracking#189]
Dear， I have meet a heavy problem when I try to deploy pytracking on TX2. when I run "python webcam dimp dimp50" on tx2, I got the error: Do you have any suggestion to solve the problem?

Using /tmp/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /tmp/torch_extensions/_prroi_pooling/build.ninja...
Building extension module _prroi_pooling...
[1/3] /usr/local/cuda-10.0/bin/nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/nvidia/.local/lib/python3.6/site-packages/torch/include -isystem /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/nvidia/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/nvidia/.local/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_62,code=sm_62 --compiler-options '-fPIC' -std=c++11 -c /home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o
FAILED: prroi_pooling_gpu_impl.cuda.o 
/usr/local/cuda-10.0/bin/nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/nvidia/.local/lib/python3.6/site-packages/torch/include -isystem /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/nvidia/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/nvidia/.local/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_62,code=sm_62 --compiler-options '-fPIC' -std=c++11 -c /home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu(1): error: expected a declaration

1 error detected in the compilation of "/tmp/tmpxft_00003452_00000000-6_prroi_pooling_gpu_impl.cpp1.ii".
[2/3] c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/nvidia/.local/lib/python3.6/site-packages/torch/include -isystem /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/nvidia/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/nvidia/.local/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++11 -c /home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o
FAILED: prroi_pooling_gpu.o 
c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/nvidia/.local/lib/python3.6/site-packages/torch/include -isystem /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/nvidia/.local/lib/python3.6/site-packages/torch/include/TH -isystem /home/nvidia/.local/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++11 -c /home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o
In file included from /home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:19:0:
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cuh:1:1: error: expected unqualified-id before ‘.’ token
 ../../../src/prroi_pooling_gpu_impl.cuh
 ^
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c: In function ‘at::Tensor prroi_pooling_backward_cuda(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, int, int, float)’:
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:68:30: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated [-Wdeprecated-declarations]
         features.data<float>(), rois.data<float>(), output.data<float>(), output_diff.data<float>(),
                              ^
In file included from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:12:
/home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:303:7: note: declared here
   T * data() const {
       ^~~~
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:68:50: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated [-Wdeprecated-declarations]
         features.data<float>(), rois.data<float>(), output.data<float>(), output_diff.data<float>(),
                                                  ^
In file included from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:12:
/home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:303:7: note: declared here
   T * data() const {
       ^~~~
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:68:72: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated [-Wdeprecated-declarations]
         features.data<float>(), rois.data<float>(), output.data<float>(), output_diff.data<float>(),
                                                                        ^
In file included from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:12:
/home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:303:7: note: declared here
   T * data() const {
       ^~~~
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:68:99: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated [-Wdeprecated-declarations]
         features.data<float>(), rois.data<float>(), output.data<float>(), output_diff.data<float>(),
                                                                                                   ^
In file included from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:12:
/home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:303:7: note: declared here
   T * data() const {
       ^~~~
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:69:35: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated [-Wdeprecated-declarations]
         features_diff.data<float>(),
                                   ^
In file included from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:12:
/home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:303:7: note: declared here
   T * data() const {
       ^~~~
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:66:5: error: ‘PrRoIPoolingBackwardGpu’ was not declared in this scope
     PrRoIPoolingBackwardGpu(
     ^~~~~~~~~~~~~~~~~~~~~~~
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:66:5: note: suggested alternative: ‘prroi_pooling_backward_cuda’
     PrRoIPoolingBackwardGpu(
     ^~~~~~~~~~~~~~~~~~~~~~~
     prroi_pooling_backward_cuda
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c: In function ‘at::Tensor prroi_pooling_coor_backward_cuda(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, int, int, float)’:
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:99:30: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated [-Wdeprecated-declarations]
         features.data<float>(), rois.data<float>(), output.data<float>(), output_diff.data<float>(),
                              ^
In file included from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:12:
/home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:303:7: note: declared here
   T * data() const {
       ^~~~
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:99:50: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated [-Wdeprecated-declarations]
         features.data<float>(), rois.data<float>(), output.data<float>(), output_diff.data<float>(),
                                                  ^
In file included from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:12:
/home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:303:7: note: declared here
   T * data() const {
       ^~~~
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:99:72: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated [-Wdeprecated-declarations]
         features.data<float>(), rois.data<float>(), output.data<float>(), output_diff.data<float>(),
                                                                        ^
In file included from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:12:
/home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:303:7: note: declared here
   T * data() const {
       ^~~~
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:99:99: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated [-Wdeprecated-declarations]
         features.data<float>(), rois.data<float>(), output.data<float>(), output_diff.data<float>(),
                                                                                                   ^
In file included from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:12:
/home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:303:7: note: declared here
   T * data() const {
       ^~~~
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:100:31: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated [-Wdeprecated-declarations]
         coor_diff.data<float>(),
                               ^
In file included from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:11:0,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4,
                 from /home/nvidia/.local/lib/python3.6/site-packages/torch/include/torch/extension.h:4,
                 from /home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:12:
/home/nvidia/.local/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:303:7: note: declared here
   T * data() const {
       ^~~~
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:97:5: error: ‘PrRoIPoolingCoorBackwardGpu’ was not declared in this scope
     PrRoIPoolingCoorBackwardGpu(
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:97:5: note: suggested alternative: ‘prroi_pooling_coor_backward_cuda’
     PrRoIPoolingCoorBackwardGpu(
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
     prroi_pooling_coor_backward_cuda
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c: In function ‘void pybind11_init__prroi_pooling(pybind11::module&)’:
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:110:42: error: ‘prroi_pooling_forward_cuda’ was not declared in this scope
     m.def("prroi_pooling_forward_cuda", &prroi_pooling_forward_cuda, "PRRoIPooling_forward");
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nvidia/1/pytracking/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:110:42: note: suggested alternative: ‘prroi_pooling_backward_cuda’
     m.def("prroi_pooling_forward_cuda", &prroi_pooling_forward_cuda, "PRRoIPooling_forward");
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                          prroi_pooling_backward_cuda
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1030, in _build_extension_module
    check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_webcam.py", line 41, in <module>
    main()
  File "run_webcam.py", line 37, in main
    run_webcam(args.tracker_name, args.tracker_param, args.debug, visdom_info)
  File "run_webcam.py", line 22, in run_webcam
    tracker.run_UAV(debug, visdom_info)
  File "../pytracking/evaluation/tracker.py", line 388, in run_UAV
    tracker.initialize(frame, _build_init_info(init_rect))
  File "../pytracking/tracker/dimp/dimp.py", line 84, in initialize
    self.init_classifier(init_backbone_feat)
  File "../pytracking/tracker/dimp/dimp.py", line 586, in init_classifier
    compute_losses=plot_loss)
  File "../ltr/models/target_classifier/linear_filter.py", line 97, in get_filter
    weights = self.filter_initializer(feat, bb)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "../ltr/models/target_classifier/initializer.py", line 164, in forward
    weights = self.filter_pool(feat, bb)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "../ltr/models/target_classifier/initializer.py", line 45, in forward
    return self.prroi_pool(feat, roi1)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/prroi_pool.py", line 28, in forward
    return prroi_pool2d(features, rois, self.pooled_height, self.pooled_width, self.spatial_scale)
  File "../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 44, in forward
    _prroi_pooling = _import_prroi_pooling()
  File "../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 33, in _import_prroi_pooling
    verbose=True
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 661, in load
    is_python_module)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 830, in _jit_compile
    with_cuda=with_cuda)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 883, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1043, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension '_prroi_pooling'

**Comment by martin-danelljan** [comment]
Hi. The issue is with the compilation of [PreciseRoIPooling](https://github.com/vacancy/PreciseRoIPooling). Please refer to their github. I have never tried deploying on TX2.
