### ISSUE TITLE
Running the tracker part in colab

### ISSUE THREAD

**Issue by amil-rp-work** [visionml/pytracking#190]
Hey @goutamgmb & @martin-danelljan,
Thanks a lot for providing such a wonderful repo hosting all the updated models and providing inference for object tracking.
I am trying to run the `lwl` model on **Google colab** and have set up the environment successfully. 
I used the following command for inference
`!cd /content/pytracking && python3 pytracking/run_video.py lwl lwl_ytvos /content/test.mp4 --optional_box 395.0 131.0 48.0 31.0 --save_results --debug 0`

However i am facing the following error
```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/usr/local/lib/python3.6/dist-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
```

Please help me in running inference models on colab and this would help other users of the repo in getting started for inference 👍

**Comment by martin-danelljan** [comment]
Hi. Thank you very much for your appreciation. 

Your issue is most likely due to the visualization since the error involves QT. But its a bit strange since `--debug 0` should turn of all visualization. Since the `run_video.py` is less tested, it could be that it activates the opencv visualization anyway. Please have a look there, otherwise me or @goutamgmb will do it when we get time.

In any case, I would like to create a Colab integration for PyTracking at some point. So I would be interested to hear any other issues you encountered and had to solve when you tried to set it up.

Thanks,
Martin

**Comment by amil-rp-work** [comment]
@martin-danelljan  I have been able to successfully run the `super_dimp` model. This was just done by simply commenting out the `cv2.window... & cv2.imshow` functions. Ofcourse, I had to set `--debug 0`, which you mentioned. 
I had a few doubts that I faced - 
- Which model is generally best in tracking signboards etc - **SuperDimp, PrDiMP-50, KYS or LWL ?**
- I faced trouble in using the **LWL** models. I have created masks for each frame of my video. How do I leverage it here

**Comment by martin-danelljan** [comment]
Hi.
- Please check the integration of the DAVIS dataset to see an example of how to integrate the masks.
- I have never tried this application. But SuperDimp should be strictly better than PrDiMP, and is robust for long sequences. KYS could have an advantage for short sequences with distractors. LWL will give you output masks.
- Right now, the tracker always returns an output. It is easy to extend the output with a confidence score. We will probably do this in future versions.

**Comment by sdamadi** [comment]
Hi,
I am also trying to run LWL on Google colab but when I execute `! bash install.sh conda_install_path pytrackingy` in a cell, I will get the following error:

```
****************** Setting up environment ******************
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/content/pytracking/pytracking/__init__.py", line 7, in <module>
    from pytracking.run_tracker import run_tracker
  File "/content/pytracking/pytracking/run_tracker.py", line 9, in <module>
    from pytracking.evaluation import get_dataset
  File "/content/pytracking/pytracking/evaluation/__init__.py", line 1, in <module>
    from .data import Sequence
  File "/content/pytracking/pytracking/evaluation/data.py", line 3, in <module>
    from ltr.data.image_loader import imread_indexed
  File "/content/pytracking/ltr/data/__init__.py", line 1, in <module>
    from .loader import LTRLoader
  File "/content/pytracking/ltr/data/loader.py", line 5, in <module>
    from torch._six import string_classes, int_classes
ImportError: cannot import name 'int_classes' from 'torch._six' (/usr/local/lib/python3.7/dist-packages/torch/_six.py)
```

Can you please help with the above?
