### ISSUE TITLE
gtk_widget_new: assertion 'g_type_is_a (type, GTK_TYPE_WIDGET)' failed

### ISSUE THREAD

**Issue by wtmsfw** [visionml/pytracking#194]
when I use the command 
python3 run_video.py dimp dimp50 ./myvideo.mp4 
to run the video demo on ubuntu, I get this error:
(run_video.py:11611): Gtk-CRITICAL **: 16:01:24.012: gtk_widget_new: assertion 'g_type_is_a (type, GTK_TYPE_WIDGET)' failed
I can see on google some people with same error, but I can't see the reply with how to fix this..
How to fix this? Thanks in advance.

**Comment by goutamgmb** [comment]
I seems the issue is in the installation of opencv. Are you able to run the rub_webcam script?
