### ISSUE TITLE
cannot deploy on a Ubuntu Server

### ISSUE THREAD

**Issue by JasperRice** [visionml/pytracking#195]
When I am trying to run `CUDA_VISIBLE_DEVICES=6 python run_tracker.py dimp dimp50`.
I get this error (only shows the first Sequence):
`Evaluating    1 trackers on   100 sequences
Tracker: dimp dimp50 None ,  Sequence: Basketball
/home/sifan/anaconda3/envs/TEST/lib/python3.7/site-packages/torch/nn/functional.py:3121: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Using /home/sifan/.cache/torch_extensions as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/sifan/.cache/torch_extensions/_prroi_pooling/build.ninja...
Building extension module _prroi_pooling...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module _prroi_pooling...
Can not compile Precise RoI Pooling library.`

Does anyone tried to run this on a server and met a similar issue?

**Comment by JianqiuChen** [comment]
How did you fix this problem?
