### ISSUE TITLE
A problem about kys when i runing the code

### ISSUE THREAD

**Issue by Mr-doraemon** [visionml/pytracking#196]
when i run run_tracker.py kys kys_default --dataset otb --debug 0 --threads 4, an error will exists. 

The error is libtorch_cpu.so: cannot open shared object file: No such file or directory. 

My PyTorch is 1.4.0, cuda 10.1, opencv 4.4.0.44.How can I solve this problem?

**Comment by martin-danelljan** [comment]
Could you print the full error? Did you install pytorch with cuda support?

**Comment by Mr-doraemon** [comment]
#

> 
> 
> Could you print the full error? Did you install pytorch with cuda support?

Thank you for your reply.  I'm confirm that my pytorch was supported by cuda, because when I run troch.cuda.is_available(), the result is True.  And below are all the errors shown

**Evaluating    1 trackers on   234 sequences
Tracker: kys kys_default None ,  Sequence: afterrain
Tracker: kys kys_default None ,  Sequence: boundaryandfast
Tracker: kys kys_default None ,  Sequence: carred
Tracker: kys kys_default None ,  Sequence: diamond
libtorch_cpu.so: cannot open shared object file: No such file or directory
Tracker: kys kys_default None ,  Sequence: aftertree
libtorch_cpu.so: cannot open shared object file: No such file or directory
Tracker: kys kys_default None ,  Sequence: bus6
libtorch_cpu.so: cannot open shared object file: No such file or directory
Tracker: kys kys_default None ,  Sequence: baby
libtorch_cpu.so: cannot open shared object file: No such file or directory
Tracker: kys kys_default None ,  Sequence: call
libtorch_cpu.so: cannot open shared object file: No such file or directory
Tracker: kys kys_default None ,  Sequence: baginhand
...
Done
**
