### ISSUE TITLE
I have some IOU-net questions

### ISSUE THREAD

**Issue by wzh-870700802** [visionml/pytracking#197]
Hello, the forward function in your IOU-net framework should only receive one picture, right, how do you realize that it accepts multiple picture pairs? Is there no for loop?

**Comment by martin-danelljan** [comment]
Hi. You can give it multiple pairs in the batch dimensions.

**Comment by wzh-870700802** [comment]
OK，thanks, and I have some prroipooling questions?
1、your self.prroi_pool3r function only receive one feature and one anchor?
2、If only one anchor can be received, is it necessary to make a loop on many anchor?

**Comment by martin-danelljan** [comment]
No, you can (and we are) doing multiple predictions in parallel. Please just check how its done in our code, and the documentation of the PrROIPool module.
