### ISSUE TITLE
Error of Multi-GPUs training?

### ISSUE THREAD

**Issue by yxxxqqq** [visionml/pytracking#198]
I have modify the `settings.multi_gpu = True` in `dimp50.py` , but I got an error, ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1]), what's it mean?

The training is works on a single GPU.

**Comment by yxxxqqq** [comment]
The training is works on a single GPU.

**Comment by sfchen94** [comment]
how did this issue solved?
