### ISSUE TITLE
Why is this version of ECO so fast, much faster than the matlab version

### ISSUE THREAD

**Issue by fanminhao** [visionml/pytracking#199]
Why is this version of ECO so fast, much faster than the matlab version？

**Comment by martin-danelljan** [comment]
Because PyTorch is nice.

**Comment by fanminhao** [comment]
https://github.com/StrangerZhang/pyECO  This version is about the same speed as matlab. I didn't expect the pytorch version to be so fast, so cool!!!

**Comment by martin-danelljan** [comment]
:) Keep in mind though that the ECO in this repo is not an exact reimplementation of the official Matlab version. The most important components (and some additional ones) are there, but it does not use exactly the same settings etc. For example, we have not integrated any hand-crafted features.

**Comment by fanminhao** [comment]
Okay, and the initial frame data augmentation in UPDT is also very important, but it is really amazing to be able to increase such a high speed. By the way, is the lack of implementation of the GMM module also a factor in increasing the speed?

**Comment by martin-danelljan** [comment]
No, probably, the GMM would make it even faster if it existed. Now we have to run with a larger memory which makes it slower.

**Comment by fanminhao** [comment]
It turned out to be like this, but removing the HoG feature and using pytorch can actually increase the speed so much. Can Dr. Martin tell me about several factors that may increase the speed, thank you for your advice

**Comment by martin-danelljan** [comment]
I think in ECO we were able to do much to speed up the online learning side. To speed it up even further, i think the best is to look into learning or using more efficient deep features.

**Comment by fanminhao** [comment]
Great, thank you very much for your answer, I have benefited a lot!!

**Comment by fanminhao** [comment]
Dr. Martin, when the ECO tracker in pytracking uses visdom to view the score map, why is the maximum response value all around the score map, shouldn't it be in the center of the target prediction?

**Comment by goutamgmb** [comment]
Could you post an example response map to show what exactly you mean? The tracker is trained to predict a Gaussian centered at the target center as output, as learning to output a binary response with just 1 at target center and 0 everywhere is hard.

**Comment by fanminhao** [comment]
![response](https://user-images.githubusercontent.com/22663545/100471206-bf171500-3114-11eb-9acb-4d57cf914c28.PNG)
What I mean is, the values around the calculated response graph are relatively large, and the value in the middle is relatively low. After visualization, like the graph in this attachment, why is the point with the largest response value around? Shouldn’t it be Gaussian distribution in the middle? ?

**Comment by goutamgmb** [comment]
Aha, that is because the response map is shifted. So the (0, 0) co-ordinate corresponds to the center of the patch.

**Comment by fanminhao** [comment]
Well, that's the problem. Is this related to the circulating sample? What's the specific operation of moving? Is this related to the Fourier transform?

**Comment by goutamgmb** [comment]
Yes. You can just shift the scores to the right and down directions by (size / 2) to center the scores.

**Comment by fanminhao** [comment]
Thank you for your reply. I still want to ask the eco in pytracking still uses the initial frame augmentation similar to UPDT. Why is the speed so much faster than that of the matlab version of ECO, and even can achieve real-time speed. Just because you didn't use hand-crafted features?

**Comment by goutamgmb** [comment]
The data augmentation is only performed in the initial frame, so it doesn't add much computational overhead, specially on long sequences. The matlab version of ECO used matconvnet library to extract deep features. The python version on the other hand uses PyTorch, which is much more optimized and can better utilize the gpus, compared to matconvnet.

**Comment by fanminhao** [comment]
Thank you for your patient reply! I understand and I learned a lot! I'm a graduate student from NWPU in China. I'm learning about object tracking with DCF. I'll ask you if I have questions in the future!
