### ISSUE TITLE
multiprocessing

### ISSUE THREAD

**Issue by github-aaliu** [visionml/pytracking#201]
if  main function have 'multiprocessing.set_start_method('spawn', force=True)'
The program would obstruct in 'for i, data in enumerate(loader, 1):'
more details obstruct in processing.start() in _MultiProcessingDataLoaderIter
when i remove 'multiprocessing.set_start_method('spawn', force=True)' from main function,everthing is ok,but get the type of batch data is tensordict.
anyone know how to deal with it

**Comment by github-aaliu** [comment]
also if i set the num_works=0,The program would be ok, but is too slow

**Comment by martin-danelljan** [comment]
Hi. What PyTorch version do you have. The only reason we had `multiprocessing.set_start_method('spawn', force=True)` was an old bug/conflict with opencv. I think this have been solved by now, and unless you experience any issues you can safely remove that line (probably we will also do it in the next update).

The TensorDict just overloads the standard python dict, but it also support pytorch operations applied to it globally for convenience.

**Comment by github-aaliu** [comment]
thank for reply, my  PyTorch version is 1.6, the tensordict error in data.to(device) because i add the data.to(device,non_block=true),when i remove it , the program would be ok. i have another problem ,when i use mult-gpu,i have got nothing improve than single gpu,maybe the limit of I/O?(but i use ssd)

**Comment by github-aaliu** [comment]
i mean the mult-gpu  not faster than single gpu

**Comment by goutamgmb** [comment]
Could you check how many GPU's are actually being used? And also their utilization using nvidia-smi?
