### ISSUE TITLE
KYS multiple initialization

### ISSUE THREAD

**Issue by tekeburak** [visionml/pytracking#204]
Hi, thank you for PyTracking framework. I have a question about KYS tracker.
KYS currently allows me to initialize one object on an image, How can I use multiple initialization in order to track multiple object using KYS tracker?

**Comment by goutamgmb** [comment]
Hi,

You can use the MultiObjectWrapper class to wrap a single object tracker to perform multi-object tracking. You can check the run_webcam function in [tracker.py](https://github.com/visionml/pytracking/blob/master/pytracking/evaluation/tracker.py) for an example on how to track multiple objects using any PyTracking tracker.
