### ISSUE TITLE
VOT 2018 evaluation

### ISSUE THREAD

**Issue by Flowerfan** [visionml/pytracking#207]
Hi, I have tested the dimp50 model on VOT2018. However, using run_vot2020 evaluation code, I got the result as shown in the following image.
![image](https://user-images.githubusercontent.com/7525070/98207828-5f53a100-1f90-11eb-8954-20f8afaf92f3.png)

There are two EAO results (0.395, 0.407). However, both of them are lower than 0.44 (reported in dimp). 
I have noticed that the evaluation metric in 2020 vot toolkit is changed.
But when I test the model with run_vot,  I got the error "_Evaluation interrupted by tracker error: Server terminated the session_".
Do you have any suggestions for reproducing the result? Thanks.

**Comment by goutamgmb** [comment]
Hi,

Yes, the evaluation metric in vot2020 is different, as compared to vot2018. Thus I am not sure how the scores which you posted are being computed.

Regarding the termination error, please check the log files generated in the vot-workspace in order to debug the code.

Regards
Goutam

**Comment by xiaotian3** [comment]
> Hi, I have tested the dimp50 model on VOT2018. However, using run_vot2020 evaluation code, I got the result as shown in the following image. ![image](https://user-images.githubusercontent.com/7525070/98207828-5f53a100-1f90-11eb-8954-20f8afaf92f3.png)
> 
> There are two EAO results (0.395, 0.407). However, both of them are lower than 0.44 (reported in dimp). I have noticed that the evaluation metric in 2020 vot toolkit is changed. But when I test the model with run_vot, I got the error "_Evaluation interrupted by tracker error: Server terminated the session_". Do you have any suggestions for reproducing the result? Thanks.

Have you solver this problem?
