### ISSUE TITLE
Tracking after detection

### ISSUE THREAD

**Issue by berkantay** [visionml/pytracking#209]
I am aiming to track my custom object after detection. I use yolov5 with pytorch. Can I use any of these trackers after the detection is completed.

**Comment by martin-danelljan** [comment]
Yes, that should be easy to integrate.

**Comment by tornadoslims** [comment]
Great project!   Re: the above question - I have used basic centroid tracking before where i run the object detector every X frames, and then use the tracker the rest of the frames.   Are there any examples on how to send a set of bounding boxes from the object detector and have them properly merged with the existing objects that are being tracked/added as a new object if the object has not previously existed?

**Comment by berkantay** [comment]
Hello @martin-danelljan, can we just initialize the tracker without any trained network. Is it possible to just pass the coordinates and initiate the tracker?

Best Regards

**Comment by goutamgmb** [comment]
@tornadoslims Please check the reply to issue  #213 for an example code on how to reset the tracker with new position.

@berkantay Yes, you can initialize the network by passing an input bounding box, as is done in [run_webcam](https://github.com/visionml/pytracking/blob/master/pytracking/run_webcam.py) and [run_video](https://github.com/visionml/pytracking/blob/master/pytracking/run_video.py) scripts. Please check these scripts for details.

**Comment by berkantay** [comment]
I could not even make the pytracking work I opened an issue for that. #220
