### ISSUE TITLE
How can we speed up the network　Dimp

### ISSUE THREAD

**Issue by charles-str** [visionml/pytracking#210]
Ｈi,Ｉwant to achieve real-time effect with Dimp in tx2, How can I do?　Can you give me some advice.

**Comment by goutamgmb** [comment]
Hi,

You can achieve speed up using the pre-trained network by modifying the inference parameters, e.g. decrease image_sample_size (i.e. operate on lower resolution image), decrease sample_memory_size, net_opt_iter, net_opt_update_iter, net_opt_hn_iter, num_init_random_boxes, box_refinement_iter, increase train_skipping. For further speed up, you can train a dimp model using the lighter backbone network, e.g. mobilenet.

Regards
Goutam

**Comment by twilight-09** [comment]
> Ｈi,Ｉwant to achieve real-time effect with Dimp in tx2, How can I do?　Can you give me some advice.

Hi, I encounter the same problem, could you give me some advices?
