### ISSUE TITLE
Annotaion Directory Mismatch when Read nfs Datasets

### ISSUE THREAD

**Issue by Suri-Feng** [visionml/pytracking#211]
I am running trackers on the nfs dataset. But cannot found the annotations directory '/pytracking/pytracking/datasets/nfs/anno/nfs_Gymnastics.txt' specified in 'nfsdataset.py'. In the version of the dataset I have downloaded, the file is in '/pytracking/pytracking/datasets/nfs/Gymnastics/30/Gymnastics.txt'. It looks like there is no 'anno' folder under 'nfs'. Did I download a mismatching dataset for the data sorting python file?

**Comment by goutamgmb** [comment]
Hi,

We re-organized the NFS dataset in a different directory structure. This PyTracking expects the NFS dataset to be organized in the following manner,

nfs_root
    - anno
        - nfs_airboard_1.txt
        - nfs_airplane_landing.txt
        -  ........
        -  ........
    - sequences
        - airboard_1
        - airplane_landing
        - .....
        - ......

You can download the nfs dataset packed in this format using the link https://drive.google.com/file/d/1VgA-iJV8HMLm8Yn4ntMPF19RajugxgbW/view?usp=sharing

Regards
Goutam

**Comment by Suri-Feng** [comment]
Thank you!
