### ISSUE TITLE
Error running LWL

### ISSUE THREAD

**Issue by mylifeasazucchini** [visionml/pytracking#215]
Hi! I encountered the following error while running the LWL tracker: 

The call:
_python run_video.py lwl lwl_ytvos Copex_002_Block-02_Trial-02_0000047.avi --optional_box 755 442 22 27_

The error:
_Traceback (most recent call last):
  File "run_video.py", line 38, in <module>
    main()
  File "run_video.py", line 34, in main
    run_video(args.tracker_name, args.tracker_param,args.videofile, args.optional_box, args.debug, args.save_results)
  File "run_video.py", line 20, in run_video
    tracker.run_video(videofilepath=videofile, optional_box=optional_box, debug=debug, save_results=save_results)
  File "..\pytracking\evaluation\tracker.py", line 281, in run_video
    tracker.initialize(frame, _build_init_info(optional_box))
  File "..\pytracking\evaluation\multi_object_wrapper.py", line 117, in initialize
    out = self.trackers[obj_id].initialize(image, init_info_split[obj_id])
  File "..\pytracking\tracker\lwl\lwl.py", line 71, in initialize
    raise Exception('No mask provided')
Exception: No mask provided_

After snooping around a bit, I found out that the error primarily arise from Line 60 in pytracking/pytracking/tracker/lwl/lwl.py
(it does not generate the initial mask from the bbox coordinates as I would expect but rather jumps to the else part of the condition)

It will be awesome if you can provide some insights/help on this issue!
Thanks) 

P.S: I think a similar issue was raised here in #187

**Comment by goutamgmb** [comment]
Hi,

The default lwl model expects a segmentation mask as input, and hence cannot work with only bounding box input. However you can use the parameter setting 'lwl_boxinit', which can operate with just input bounding box. 

So try with the call
python run_video.py lwl lwl_boxinit Copex_002_Block-02_Trial-02_0000047.avi --optional_box 755 442 22 27

Note: lwl_boxinit uses a different network https://drive.google.com/file/d/1aAsj_N1LAMpmmcb1iOxo2z66tJM6MEuM/view?usp=sharing. This network is same as the one used by lwl_ytvos with the only difference that it has an additional module which can convert the input box to a mask.

**Comment by mylifeasazucchini** [comment]
Sorry for the late reply but now I have an error similar to #217 so I will close this issue and follow the updates from there, Thanks!
