### ISSUE TITLE
Some questions about code implement of algorithm1 of dimp

### ISSUE THREAD

**Issue by laisimiao** [visionml/pytracking#216]
https://github.com/visionml/pytracking/blob/b2ace27087a0428389ef3700001a1abbe79c74c1/ltr/models/target_classifier/optimizer.py#L150-L157
![image](https://user-images.githubusercontent.com/37405764/100399505-0908e800-308e-11eb-95d1-019f271c887f.png)
Hi@martin-danelljan could I ask two questions about `alpha_den`?
- In line4 of  algorithm1, we need to calculate ![image](https://user-images.githubusercontent.com/37405764/100400031-03ac9d00-3090-11eb-9ebf-206cf012b491.png) that is the Jacobian of the **residuals** at f(i) multiply **weights_grad**, so why can `filter_layer.apply_filter(feat, weights_grad)` do that, I don't quite understand this part code?
- Another point confuse me is that why we need add **alpha_num** in **alpha_den** as above code line156?

My regards,
Simiao Lai

**Comment by martin-danelljan** [comment]
Hi Simiao,

* For a detailed answer to the first question, please check the derivation and text in [Section S2 of the DiMP paper (supplementary)](https://arxiv.org/pdf/1904.07220.pdf). Basically, the Jacobian of a linear operation is the same as the linear operation it self. And the convolution is just a linear operation.
* The term `reg_weight * alpha_num` stems from the regularization term in the objective. `alpha_num` is just the squared norm of the gradient, and it appears here for the regularization term again (see the supplementary again).

Regards,
Martin

**Comment by laisimiao** [comment]
thanks, I would try to understand according to supplementary materials
