### ISSUE TITLE
no module named pytracking.parameter.dimp

### ISSUE THREAD

**Issue by berkantay** [visionml/pytracking#220]
```python3.6 run_video.py dimp ../<some_path>/parameter/dimp/dimp50.py /home/user/Downloads/2.mp4``` is the command I run for tracking on a video file.

I get no module named pytracking.parameter.dimp

**Comment by goutamgmb** [comment]
You should provide the name of the parameter setting, not it's path. Please try running

`python3.6 run_video.py dimp dimp50 /home/user/Downloads/2.mp4`

**Comment by berkantay** [comment]
Again, I get no module named pytracking.parameter.dimp. May something be wrong at setup? Since I am trying to use these trackers on NVIDIA Jetson TX2 there might be some conflicts.

**Comment by goutamgmb** [comment]
That is strange. I don't think the hardware you are using should be the issue. Can you post the full error trace? Also, are you able to run other scripts, e.g. run_webcam?

**Comment by berkantay** [comment]
Now I think I have problems about opencv installation, not sure?
```
Traceback (most recent call last):
  File "run_video.py", line 38, in <module>
    main()
  File "run_video.py", line 34, in main
    run_video(args.tracker_name, args.tracker_param,args.videofile, args.optional_box, args.debug, args.save_results)
  File "run_video.py", line 20, in run_video
    tracker.run_video(videofilepath=videofile, optional_box=optional_box, debug=debug, save_results=save_results)
  File "../pytracking/evaluation/tracker.py", line 266, in run_video
    cv.namedWindow(display_name, cv.WINDOW_NORMAL | cv.WINDOW_KEEPRATIO)
cv2.error: OpenCV(4.4.0) /tmp/pip-install-u_48sbgy/opencv-python/opencv/modules/highgui/src/window.cpp:634: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvNamedWindow'

```

**Comment by goutamgmb** [comment]
Yes, it seems the issue is with opencv. Please check if the solutions mentioned [here](https://stackoverflow.com/questions/14655969/opencv-error-the-function-is-not-implemented) work for you.
