### ISSUE TITLE
run_video.py:  TypeError: `__cuda_array_interface__` must be a dict but can't downgrade PyTorch version due to compatibility with GPU drivers

### ISSUE THREAD

**Issue by DavideDaz** [visionml/pytracking#223]
Hi,

I am running on Pytorch 1.8 nightly version that it looks to be the only compatible version  for the GeForce RTX 3090 but getting the above mentioned TypeError. Any workaround?

Thank you!

**Comment by goutamgmb** [comment]
Could you post the full error trace?

**Comment by DavideDaz** [comment]
> Could you post the full error trace?

Dear goutamgmb, sorry for the late reply, here is the complete errortrace:

`Traceback (most recent call last):
  File "run_video.py", line 36, in <module>
    main()
  File "run_video.py", line 32, in main
    run_video(args.tracker_name, args.tracker_param,args.videofile, args.optional_box, args.debug)
  File "run_video.py", line 20, in run_video
    tracker.run_video(videofilepath=videofile, optional_box=optional_box, debug=debug)
  File "../pytracking/evaluation/tracker.py", line 77, in run_video
    tracker.track_videofile(videofilepath, optional_box)
  File "../pytracking/tracker/base/basetracker.py", line 91, in track_videofile
    self.initialize(frame, init_state)
  File "../pytracking/tracker/segm/segm.py", line 96, in initialize
    feat_max_stride = max(self.params.features_filter.stride())
  File "../pytracking/features/extractor.py", line 66, in stride
    return torch.Tensor(TensorList([f.stride() for f in self.features if self._return_feature(f)]).unroll())
TypeError: `__cuda_array_interface__` must be a dict
`

**Comment by ReedZyd** [comment]
I am running on Pytorch 1.7.0 and the GeForce RTX 3090, but it seems that they are not compatible with spatial_correlation_sampler and Precise ROI pooling module.

**Comment by DavideDaz** [comment]
> I am running on Pytorch 1.7.0 and the GeForce RTX 3090, but it seems that they are not compatible with spatial_correlation_sampler and Precise ROI pooling module.

Hi ReedZyd,

but could you make it run anyway?

Thanks,

Davide

**Comment by ReedZyd** [comment]
> > I am running on Pytorch 1.7.0 and the GeForce RTX 3090, but it seems that they are not compatible with spatial_correlation_sampler and Precise ROI pooling module.
> 
> Hi ReedZyd,
> 
> but could you make it run anyway?
> 
> Thanks,
> 
> Davide

No, Pytorch1.7.0 is not compatible with some modules.

**Comment by jiaqinxu** [comment]
I change the pytorch version to
# CUDA 10.0
conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch
and successfully solve the problem in D3S
