### ISSUE TITLE
A question about PrDiMP test on Got10k

### ISSUE THREAD

**Issue by DEQDON** [visionml/pytracking#224]
Hi, I'm running tracking with PrDiMP on Got10k dataset. I downloaded the already trained `prdimp50.pth.tar` network from Google Drive. I use the following code to test:
```
python run_tracker.py dimp prdimp50 --dataset_name got10k_test --sequence 5 --debug 8 --threads 8
```

The output in visdom seems odd:

![Tracking (2)](https://user-images.githubusercontent.com/26454204/101172818-a2329280-367c-11eb-9781-fc68244383d5.png)

And the output file is this:

```
948     361     217     371
936     380     215     360
909     389     216     351
894     408     196     349
847     472     220     287
847     472     220     287
207     711     260     273
207     711     260     273
207     711     260     273
649     584     320     194
105     709     247     262
105     709     247     262
30      683     276     276
26      666     280     287
6       663     309     282
15      686     296     269
743     451     249     294
782     475     186     296
793     436     254     337
830     468     240     328
870     475     198     336
870     486     238     317
870     486     238     317
870     486     238     317
843     615     266     224
871     633     231     188
822     653     194     179
822     653     194     179
822     653     194     179
822     653     194     179
822     653     194     179
822     653     194     179
822     653     194     179
822     653     194     179
822     653     194     179
822     653     194     179
822     653     194     179
822     653     194     179
665     650     202     165
663     616     241     185
710     583     195     227
663     560     208     250
538     503     196     309
616     485     228     341

```

If the red box the output result and the green box is the groundtruth?
The target center of the output seems fine, but the resulting bounding box seems too large?

Do you have any idea on why this might happen? Thanks for your precious time!

**Comment by goutamgmb** [comment]
Hi,

The green box is the actual output of the tracker. The red box denotes the 'search region', i.e. the local region around the previous target location on which we apply the tracker. The search region is usually set to have an area 5^2 times the area of the target box. We do not visualize the ground truth box during tracking.

Regards
Goutam

**Comment by DEQDON** [comment]
I see. Thanks!
