### ISSUE TITLE
tracking accuracy score

### ISSUE THREAD

**Issue by berkantay** [visionml/pytracking#227]
hello, I want to display tracking accuracy on the screen. Which variable corresponds to that value?

Best

**Comment by goutamgmb** [comment]
Hi, 

I am not sure what you mean. By tracking accuracy, do you mean how well the tracker prediction fits the actual target? If so, you will ofc need to have ground truth annotations for your sequence. Currently we do not have support for displaying the tracking accuracy during tracking.

Instead if you want to visualize the 2D localization scores predicted by the tracker, you can run tracker in the debug mode, with debug level set to 1.  e.g. `python run_webcam.py tracker_name parameter_name  --debug 1`

Regards
Goutam

**Comment by eliafranc** [comment]
Hey @goutamgmb 

Do the localization scores actually represent probabilities? 

Thanks!
