### ISSUE TITLE
No module named 'ltr.external.PreciseRoIPooling.pytorch'

### ISSUE THREAD

**Issue by berkantay** [visionml/pytracking#229]
I understand that I need to compile precise Roi pooling layer but I could not find how to compile it from https://github.com/vacancy/PreciseRoIPooling

**Comment by chetanpandey1266** [comment]
@berkantay did you find out how to compile it?

**Comment by chetanpandey1266** [comment]
![atom_test](https://user-images.githubusercontent.com/55939332/122514826-2d2c1680-d02a-11eb-9d5d-77f6b5adab29.png)
I am getting something like this. Were you also getting the same?

**Comment by berkantay** [comment]
hello @chetanpandey1266 i had also same error message. what I did was just copy the `https://github.com/vacancy/PreciseRoIPooling` repository under external directory. then it should work. unless please let me know

**Comment by chetanpandey1266** [comment]
Yeah that worked fine but now its showing this:

Using /root/.cache/torch_extensions as PyTorch extensions root...
No modifications detected for re-loaded extension module _prroi_pooling, skipping build step...
Loading extension module _prroi_pooling...
Can not compile Precise RoI Pooling library.

**Comment by chetanpandey1266** [comment]
It worked finally. I was able to print the results. Thanks for your help @berkantay
