### ISSUE TITLE
multiple object tracking using ATOM

### ISSUE THREAD

**Issue by grablerm** [visionml/pytracking#234]
hi,

is there the possibility to track multiple objects using ATOM using a COCO dataset?
thanks

**Comment by martin-danelljan** [comment]
Hi. Yes, the framework supports multi-object tracking. Any single object tracker, like ATOM, can be run for multiple objects in a "naive" way where the framework instantiates several trackers. You can check how the DAVIS or YouTubeVOS datasets are integrated.

**Comment by grablerm** [comment]
thanks.
