### ISSUE TITLE
Confused by SuperDimp model

### ISSUE THREAD

**Issue by Soarkey** [visionml/pytracking#237]
What means `SuperDimp `, Counld you please provide the corresponding paper?
thx!  : )

**Comment by martin-danelljan** [comment]
Hi. Essentially, SuperDimp is based on these two papers:

Our CVPR 2020 (PrDimp): http://openaccess.thecvf.com/content_CVPR_2020/papers/Danelljan_Probabilistic_Regression_for_Visual_Tracking_CVPR_2020_paper.pdf 
Our BMVC 2020: https://www.bmvc2020-conference.com/conference/papers/paper_0154.html

**Comment by Soarkey** [comment]
Thank you very much.
