### ISSUE TITLE
PrPooling compile error

### ISSUE THREAD

**Issue by Misaka1996** [visionml/pytracking#238]
Hi:
I followed the instructions of INSTALL_win.md to compile PrPooling on windows10 with with Visual Studio 2017, but encountered some strange errors: 
![vs2017](https://user-images.githubusercontent.com/25078061/107377476-fac35780-6b25-11eb-9c09-0945a228ece5.png)
When I switched to Visual Studio 2015, there were more errors occurred(partal as followed)：
![vs2015](https://user-images.githubusercontent.com/25078061/107377986-8210cb00-6b26-11eb-9d2b-c5e2d678063a.png)
Does anyone kwon how to modify the code?
Thanks a lot.

The platform version is followed:
Visual Studio 2017 & Visual Studio 2015
CUDA V10.1.243
PyTorch 1.6.0+cu101

**Comment by ziBLan** [comment]
use torch.ops.roipool instead (if pytorch > 1.6.0)

**Comment by goutamgmb** [comment]
Hi,

Please refer to the official PrPool [repo](https://github.com/vacancy/PreciseRoIPooling) for issues regarding precise ROI pool installation.
