### ISSUE TITLE
Question about code release

### ISSUE THREAD

**Issue by wjn922** [visionml/pytracking#250]
Hi,

     Thanks for the paper "Generating Masks from Boxes by Mining Spatio-Temporal Consistencies in Videos". Do you have a plan date for releasing its code?

**Comment by martin-danelljan** [comment]
Hi. Thank you for the interest in this work. It is still under review. However, we plan to release the code soon.

**Comment by wjn922** [comment]
Thanks for your kind reply. Looking forward.
