### ISSUE TITLE
Performance gap on YoutubeVOS

### ISSUE THREAD

**Issue by liuziyang123** [visionml/pytracking#252]
hi, thanks to your excellent work on VOS.
During reproducing your results on YoutubeVOS, I got a few problems.
The result on YoutubeVOS 2018 only reaches 77.4. The environments are ubuntu16, pytorch1.1, cuda10.0.
I adopted your provided model lwl_stage2.pth for evaluation. The parameters were set as in your default lwl_ytvos.py
Therefore, I'm wondering why the result is not as good as yours.
I'll be very grateful if you can reply me.

**Comment by liuziyang123** [comment]
A mistake was made by me. 77.4 is obtained on testing youtube2018valid sampled frames. The right way is to test on youtube2018valid_all_frames, and the results reached 81.1, which is within the margin of error.

**Comment by martin-danelljan** [comment]
Thank you for also giving the answer! :)
