### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by Fanthers** [visionml/pytracking#254]
i am running kys, but the following error occurred:
spatial_correlation_sampler_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c108BFloat16EEEPKNS_6detail12TypeMetaDataEv

**Comment by Fanthers** [comment]
> i am running kys, but the following error occurred:
> spatial_correlation_sampler_backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c108BFloat16EEEPKNS_6detail12TypeMetaDataEv

（1）i change pip install spatial-correlation-sampler ==>> **pip install spatial-correlation-sampler==0.2.1**, i change version
（2）There is a problem with the parameters because of the revision, so i **delete a parameter**:
--------------------------------------
 im_patches, patch_coords = sample_patch_multiscale(im, pos, scales, sz,
                                                    mode=self.params.get('border_mode', 'replicate'),
                                                    max_scale_change=self.params.get('patch_max_scale_change', None))
--------------------------------------
this code in pytracking/tracking/kys/kys.py 228 line, delete max_scale_change=self.params.get('patch_max_scale_change', None))

**Comment by goutamgmb** [comment]
Hi,

It seems there is still an issue with spatial_correlation_sampler. Was it compiled correctly? Or is there any mismatch in the environment used to compile the package, and the one used to run the code?

**Comment by Fanthers** [comment]
> Hi,
> 
> It seems there is still an issue with spatial_correlation_sampler. Was it compiled correctly? Or is there any mismatch in the environment used to compile the package, and the one used to run the code?

Hello, i can run it now. When I use dimp50, it can work normally, but when I change the kys model, it prompts an error, kys must install spatial_correlation_sampler，But if I install it directly, I will install the highest version 0.3, so I set the version 0.2.1 and delete the last parameter in the sample_patch_multiscale, so that it can run normally.

**Comment by Fanthers** [comment]
> Hi,
> 
> It seems there is still an issue with spatial_correlation_sampler. Was it compiled correctly? Or is there any mismatch in the environment used to compile the package, and the one used to run the code?

Hello, i can run it now. When I use dimp50, it can work normally, but when I change the kys model, it prompts an error, kys must install spatial_correlation_sampler，But if I install it directly, I will install the highest version 0.3, so I set the version 0.2.1 and delete the last parameter in the sample_patch_multiscale, so that it can run normally.

**Comment by GehenHe** [comment]
@Fanthers Hi，could you please figure out where is the "sampler_patch_multiscale"?
