### ISSUE TITLE
question about analyze the results of YouTube-VOS

### ISSUE THREAD

**Issue by zhouweii234** [visionml/pytracking#256]
hi, thanks to your excellent work on VOS.
I wrote a python file according to  pytracking/notebooks/analyze_results.ipynb to analyze the results of YouTube-VOS.Below is my code

`import matplotlib.pyplot as plt`  
`plt.rcParams['figure.figsize'] = [14, 8]`
`sys.path.append('../..')`
`from pytracking.analysis.plot_results import plot_results, print_results, print_per_sequence_results`
`from pytracking.evaluation import Tracker, get_dataset, trackerlist`
`trackers = []`
`trackers.extend(trackerlist('lwl', 'lwl_ytvos', range(0,1), 'LWL'))`
`dataset = get_dataset('yt2018_valid_all')`
`plot_results(trackers, dataset, 'yt2018_valid_all', merge_results=True, plot_types=('success', 'prec'), skip_missing_seq=False, force_evaluation=True, plot_bin_gap=0.05, exclude_invalid_frames=False)`

But i got an error

`Indexing YouTubeVOS "all_frames" frame names to /root/valid_all_frames_frame_names.json`
`Done. Move /root/valid_all_frames_frame_names.json to /root/projects/data/YouTube-VOS/2018/valid_all_frames/frame_names.json to load faster next time.`
`YouTubeVOS/2018/valid loaded.`
`  0%|                                                                                                                                        | 0/474 [00:00<?, ?it/s]`
`Traceback (most recent call last):`
`  File "analyze_results.py", line 17, in <module>`
`    plot_results(trackers, dataset, 'yt2018_valid_all', merge_results=True, plot_types=('success', 'prec'), `
`  File "/root/projects/code/pytracking/pytracking/analysis/plot_results.py", line 223, in plot_results`
`    eval_data = check_and_load_precomputed_results(trackers, dataset, report_name, force_evaluation, **kwargs)`
`  File "/root/projects/code/pytracking/pytracking/analysis/plot_results.py", line 173, in check_and_load_precomputed_results`
`    eval_data = extract_results(trackers, dataset, report_name, **kwargs)`
 ` File "/root/projects/code/pytracking/pytracking/analysis/extract_results.py", line 129, in extract_results`
 `   anno_bb = torch.tensor(seq.ground_truth_rect)`
`RuntimeError: Could not infer dtype of collections.OrderedDict`

Since examples of how to use the analysis module has no content about VOS，could you give an examples of VOS？

**Comment by iLoyalty** [comment]
May I know if you solve it? I'm facing the same error. I tried using the 'evaluate_vos' script as well but it only works with DAVIS.

**Comment by goutamgmb** [comment]
Hi,

The annotation for the YouTube-VOS validation sets are not available publically. Thus you cannot use evaluate_vos or extract_results scripts to analyze the performance on YouTube-VOS validation set. Instead, you will have to use the official [evaluation server](https://competitions.codalab.org/competitions/20127#participate) of YouTube-VOS.
