### ISSUE TITLE
The model file cannot be downloaded normally

### ISSUE THREAD

**Issue by Alexadlu** [visionml/pytracking#26]
When I used install.sh, I found that the two model files default.pth could not be downloaded. Then I copied the link to the Google browser for download, but the downloaded files were indeed unusable.So could you please upload these two model files to github? Thank you very much #

**Comment by goutamgmb** [comment]
Did you try downloading the models from https://drive.google.com/drive/folders/1WVhJqvdu-_JG1U-V0IqfxTUa1SBPnL0O?

**Comment by Alexadlu** [comment]
Yes, I tried. I downloaded one of the model files on the Google browser through this link, but it didn't work. I don't know why.The size is about 107M in compressed files.

**Comment by goutamgmb** [comment]
Are you trying to uncompress the files? If that is the case, you do not need to uncompress the downloaded tar file. Instead, just move the atom_default.pth.tar to pytracking/networks folder.

**Comment by Alexadlu** [comment]
Ok, thank you. I always think it needs to be decompressed, so I will try to use it directly first. Thank you very much.

**Comment by goutamgmb** [comment]
You are welcome :)

**Comment by QIQIVTrackingY** [comment]
Hello, do you slove the problem? I download the tar file, but it a broken file and can not uncompress.

**Comment by goutamgmb** [comment]
@QIQIVTrackingY  You **do not** need to uncompress the network file. Just save the network file as atom_default.pth

**Comment by QIQIVTrackingY** [comment]
Thank  you!



---Original---
