### ISSUE TITLE
VOT2020 Parameters for PrDiMP50 & DiMP50

### ISSUE THREAD

**Issue by khaghanijavad** [visionml/pytracking#262]
Hi, 
Thank you for your strong works and framework. 
Could you please release the parameters (and your official results) of PrDiMP50 & DiMP50 for VOT2020? 
Thank you very much.

**Comment by goutamgmb** [comment]
We used the default [dimp50](https://github.com/visionml/pytracking/blob/master/pytracking/parameter/dimp/dimp50.py) and [super_dimp](https://github.com/visionml/pytracking/blob/master/pytracking/parameter/dimp/super_dimp.py) parameters for our VOT2020 submissions.
