### ISSUE TITLE
Issue with the (evaluate_vos) script 

### ISSUE THREAD

**Issue by iLoyalty** [visionml/pytracking#266]
Thank your for your great work! I'm trying to evaluate the LWL trackers performance on youtube-vos using the evaluate_vos script. It is working fine when I set the dataset to DAVIS. However, it is giving me "NaN' values for youtube-vos-valid. The segmentation and tracking results folders aren't empty. 

`tracker_ytvos = []
tracker_ytvos.extend(trackerlist('lwl', 'lwl_ytvos'))
evaluate_vos(tracker_ytvos, dataset = 'yt2019_valid', force=False)`

`                  | J-Mean     | J-Recall    | J-Decay    |
lwl lwl_ytvos      | 3.80       | 3.80        | -7.70      |

([   J-Mean  J-Recall  J-Decay
  0   0.038     0.038   -0.077],
 [          Sequence  J-Mean  J-Recall  J-Decay
  0     0062f687f1_1     NaN       NaN      NaN
  1     0062f687f1_2     NaN       NaN      NaN
  2     0062f687f1_3     NaN       NaN      NaN
  3     00f88c4f0a_1     NaN       NaN      NaN
  4     00f88c4f0a_2     NaN       NaN      NaN
  ...            ...     ...       ...      ...
  1058  ff6eb95840_1     NaN       NaN      NaN
  1059  ffcc04a0c2_1     NaN       NaN      NaN
  1060  ffcc04a0c2_3     NaN       NaN      NaN
  1061  ffd7c15f47_1     NaN       NaN      NaN
  1062  ffd7c15f47_2     NaN       NaN      NaN
  
  [1063 rows x 4 columns]])`

May I have any suggestion, please?

**Comment by goutamgmb** [comment]
The annotation for the official YouTubeVOS validation set is private. Thus, you cannot evaluate the performance on the YouTubeVOS validation set using evaluate_vos script. Instead you will have to upload the results on the [evaluation server](https://competitions.codalab.org/competitions/20127#participate).
