### ISSUE TITLE
something about got10k_val_split.txt in pytracking\ltr\data_specs

### ISSUE THREAD

**Issue by qq1018408006** [visionml/pytracking#269]
Do the numbers mean the indices of sequences in got-10k trainset？I find the maximum in that txt is 9931， but the valset only has 180 sequences. 
Appreciating for one's help.

**Comment by martin-danelljan** [comment]
What numbers?

**Comment by qq1018408006** [comment]
> What numbers?

`1896
1834
8689
3665
2957
6913
8009
4851
6420
7987
828
3003
8884
8815
3198
8008
194
6251
3303
3934
395
1285
6230
7241
8250
2219
2582
8353
7790
7583
4462
3904
9004
6942
1704
5686
8051
2981
5511
6182
7088
1699`Like this.

**Comment by goutamgmb** [comment]
Note that got10k_val_split does not refer to the original GOT-10k validation split. Instead, we constructed a custom validation split for monitoring training by randomly sampling 15% of the sequences from the official GOT-10k training split. got10k_val_split.txt contains the indices of sequences from the official GOT-10k training split which we use as our validation sequences. got10k_train_split.txt contains indices of remaining sequences which we use for training. You can refer to the code [here](https://github.com/visionml/pytracking/blob/master/ltr/dataset/got10k.py#L64) to check exactly how the indices are used.

**Comment by qq1018408006** [comment]
> Note that got10k_val_split does not refer to the original GOT-10k validation split. Instead, we constructed a custom validation split for monitoring training by randomly sampling 15% of the sequences from the official GOT-10k training split. got10k_val_split.txt contains the indices of sequences from the official GOT-10k training split which we use as our validation sequences. got10k_train_split.txt contains indices of remaining sequences which we use for training. You can refer to the code [here](https://github.com/visionml/pytracking/blob/master/ltr/dataset/got10k.py#L64) to check exactly how the indices are used.

Well,I see.Thanks for your reply!
