### ISSUE TITLE
Do I certainly need to install the cuda10?

### ISSUE THREAD

**Issue by nosaydomore** [visionml/pytracking#27]
hello,thank for  your Great work.
I can not install cuda10 for some reasons, Could I install another version of cuda(e.g. cuda7, cuda8) to instead of cuda10?

**Comment by goutamgmb** [comment]
Hi,

We have tested the pytorch 0.4.1 version (see pytorch041 branch) with cuda9.2. We have not tested older cuda versions, however it should work. In case you have issues with installing preciseROIPooling, please check the original repo at https://github.com/vacancy/PreciseRoIPooling.
