### ISSUE TITLE
‘ImportError: Can not compile Precise RoI Pooling library.’

### ISSUE THREAD

**Issue by qq1018408006** [visionml/pytracking#271]
I deployed the project on ubuntu following INSTALL.md，however python meets trouble `‘ImportError: Can not compile Precise RoI Pooling library.’` when running `python run_webcam.py atom default`.I have no idea to deal with that. Could anyone give me some advice?

**Comment by martin-danelljan** [comment]
Do you have a GPU?

**Comment by yyk-nb** [comment]
i met this same problem and i have a gpu
