### ISSUE TITLE
Win10,in functional.py,Error:ImportError: DLL load failed 

### ISSUE THREAD

**Issue by angaio** [visionml/pytracking#273]
def _import_prroi_pooling():
    global _prroi_pooling

    #load the prroi_pool module
    import imp
    file, path, description = imp.find_module('prroi_pool')
    with file:
        _prroi_pooling = imp.load_module('prroi_pool', file, path, description)

    if _prroi_pooling is None:
        try:
            from os.path import join as pjoin, dirname
            from torch.utils.cpp_extension import load as load_extension
            root_dir = pjoin(dirname(__file__), 'src')

            _prroi_pooling = load_extension(
                '_prroi_pooling',
                [pjoin(root_dir, 'prroi_pooling_gpu.c'), pjoin(root_dir, 'prroi_pooling_gpu_impl.cu')],
                verbose=True
            )
        except ImportError:
            raise ImportError('Can not compile Precise RoI Pooling library.')

    return _prroi_pooling
----------------------
    import imp is not supported on python3.7 version.these code can't run on python3.7,on windows10,pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.2.
How to fix this problem?

**Comment by goutamgmb** [comment]
As stated in the error message, the `imp` package is not supported for your particular configuration. You can try replacing it with `importlib` (see https://docs.python.org/3/library/imp.html). Unfortunately we have only tested the code on Ubuntu, and thus cannot help much with windows installation.
