### ISSUE TITLE
run tracker in nfs

### ISSUE THREAD

**Issue by FreezerBreath** [visionml/pytracking#274]
The method of reading NFS data set in pytracking is not compatible with the original NFS data set.

**Comment by goutamgmb** [comment]
Hi,

Yes. You can use the nfs dataset in pytracking compatible format using the link https://drive.google.com/file/d/1VgA-iJV8HMLm8Yn4ntMPF19RajugxgbW/view?usp=sharing.

**Comment by FreezerBreath** [comment]
Thank you very much!
