### ISSUE TITLE
A question of the training

### ISSUE THREAD

**Issue by JawnHoan** [visionml/pytracking#277]
Thank you for your work!
I have a problem when I was training my own DIMP50-net.
The error information is as follows:

Training crashed at epoch 1
Traceback for the error!
Traceback (most recent call last):
  File "ltr/../ltr/trainers/base_trainer.py", line 70, in train
    self.train_epoch()
  File "ltr/../ltr/trainers/ltr_trainer.py", line 80, in train_epoch
    self.cycle_dataset(loader)
  File "ltr/../ltr/trainers/ltr_trainer.py", line 52, in cycle_dataset
    for i, data in enumerate(loader, 1):

      raise ValueError('The number of weights does not match the population')
ValueError: The number of weights does not match the population

I don't know why such a mistake happened. I hope I can get your help. Thanks

**Comment by goutamgmb** [comment]
Are you using different datasets? In the initialization of `sampler.DiMPSampler`, the length of the list of datasets, and the length of sampling probabilities should match, as in the code snippet.

```
  # Train sampler and loader
  dataset_train = sampler.DiMPSampler([lasot_train, got10k_train, trackingnet_train, coco_train], [0.25,1,1,1],
                                      samples_per_epoch=26000, max_gap=30, num_test_frames=3, num_train_frames=3,
                                      processing=data_processing_train)
```

**Comment by JawnHoan** [comment]
Thank you very much for your help!  I am sorry for my carelessness.

**Comment by goutamgmb** [comment]
No problem :)

**Comment by wsasdsda** [comment]
As a beginner,I still can't get your answer,could you please be a little more specific?
