### ISSUE TITLE
super_dimp_simple.pth.tar missing?

### ISSUE THREAD

**Issue by lfxx** [visionml/pytracking#278]
When i use keep_track code,i can not find where to download this file @martin-danelljan @2006pmach

**Comment by 2006pmach** [comment]
We updated the `MODEL_ZOO.md` and `pytracking/README.md` files to include the link to the model file. You can find it [here](https://drive.google.com/file/d/1lzwdeX9HBefQwznMaX5AKAGda7tqeQtg).  Let us know if this works for you.

**Comment by lfxx** [comment]
> We updated the `MODEL_ZOO.md` and `pytracking/README.md` files to include the link to the model file. You can find it [here](https://drive.google.com/file/d/1lzwdeX9HBefQwznMaX5AKAGda7tqeQtg). Let us know if this works for you.

Now the code can work well.Thanks!
