### ISSUE TITLE
All tar models are downloadable but all corrupted/empty inside

### ISSUE THREAD

**Issue by franva** [visionml/pytracking#280]
I have been trying to download the Keep_track model for at least 6 times, 
the downloaded model(186.6MB on my disk) does not have anything inside.

![image](https://user-images.githubusercontent.com/5151146/133873934-70022ae7-188a-4757-8c4d-93e55f6ee4bf.png)

My observation is :

The download seems running okay for a few seconds, then the process of downloading out of sudden finished which does not seem to be a real completion.

Could someone fix the corrupted file please?

**Comment by franva** [comment]
Also tried SuperDiMPSimple and PrDiMP-18, same issue.

**Comment by 2006pmach** [comment]
Hey, you don't need to unpack the tar files. We load them in the code as such. Just follow the [INSTALL.md](https://github.com/visionml/pytracking/blob/master/INSTALL.md#) and [setup the environment](https://github.com/visionml/pytracking/blob/master/INSTALL.md#setup-the-environment) therein.  Save the `*.pth.tar` files on disk and specify the path in the `pytracking/evaluation/local.py` file and add the path to the `network_path` variable.

**Comment by franva** [comment]
hi @2006pmach 

Wow, I didn't know the model can be tar files~! 

Tried and they all work as expected~! 

Thank you so much~!

Just wondering, I am trying to use one of the models on my edge devices e.g. RPi 4 with 4GB or Jetson nano or Intel Myriad Stick 2, Intel VPU.

Have you ever heard anybody done this?

If not, could you please recommend a model which is the lightest model?

Thank you ~!
