### ISSUE TITLE
Training KeepTrack using "super_dimp_simple.pth.tar" as a base [SOLVED]

### ISSUE THREAD

**Issue by iLoyalty** [visionml/pytracking#282]
Hi.

Thank you for the amazing effort.

I've been trying to train "KeepTrack" using the weights downloaded from [here](https://github.com/visionml/pytracking/blob/master/ltr/README.md#KeepTrack), and I placed them in `"/checkpoints/ltr/dimp/super_dimp_simple/super_dimp_simple.pth.tar" ` but I got an error: `'No matching checkpoints file found'`

I noticed that the function in the script has an argument "super_dimp_hinge", `net_pretrained, _ = load_pretrained('dimp', 'super_dimp_hinge')`. I'm confused, what does the "super_dimp_hinge" refer to?, since there are no training scripts with that name in the "training_settings" folder. 

I tried to change it to "super_dimp_simple", but no luck.

Thank you for your time and help in advance.

**Comment by 2006pmach** [comment]
Hi

The issue should be resolved now, I updated the train_settings file (it was a relict from the past). Just set `self.pretrained_networks` in `ltr/admin/local.py` to point to the directory where `super_dimp_simple.pth.tar` is stored on your disk and the model should be loaded as expected. Let me know if this works for you.

**Comment by iLoyalty** [comment]
Works like a charm!

Thank you very much for your help, I appreciate it.
