### ISSUE TITLE
Performance gap on NSF (KeepTrack)

### ISSUE THREAD

**Issue by wafaAlghallabi** [visionml/pytracking#283]
Hello.

Thank you for your amazing work.

I used the pre-trained KeepTrack tracker from [here](https://drive.google.com/file/d/1JIhzF1yd1EFbVCKJMakqEjWngthySIS5/edit) and tested on NSF (downloaded from [here](https://drive.google.com/file/d/1VgA-iJV8HMLm8Yn4ntMPF19RajugxgbW/view?usp=sharing.). However, I got a lower score (AUC 65.54) compared to the result reported in the paper (AUC 66.4). Then, I tried to train the KeepTrack using the source code with the same configurations using the pre-trained base tracker, I got (65.04). 

I'm aware that the results were reported using the average of 5 runs, tried that as well but the AUC score won't be higher than 65.8. 

Thank you for your time.

**Comment by iLoyalty** [comment]
Thanks for the reply. I got 66.8 (individual run) on LaSOT (using the pre-trained KeepTrack), so there is still 0.3% inferior.

**Comment by iLoyalty** [comment]
> Hi. I am not really sure what is causing the issue on your side. I just checked our achieved results with KeepTrack and we get [66.2, 66.2, 66.3, 66.6, 66.5] for the individual runs which lead to 66.4 on average. These results are also available [here](https://github.com/visionml/pytracking/blob/master/MODEL_ZOO.md#Raw-Results-1). You could download them and check if you can reproduce the reported results to make sure that your evaluation environment is setup properly. Otherwise, did you try LaSOT? What do you get there?

Thanks for the reply. I got 66.8 (individual run) on LaSOT (using the pre-trained KeepTrack), so there is still 0.3% inferior.
