### ISSUE TITLE
I can't compile Precise RoI Pooling library. Error building extension '_prroi_pooling'

### ISSUE THREAD

**Issue by Hevans123** [visionml/pytracking#29]
My cuda=9.0, other configurations follow the installations
when I ran the command "python run_tracker.py atom default --sequence Crossing --debug 0 --threads 6". something went wrong.Could you give me some advice? Thanks
Errors like this:
Emitting ninja build file /tmp/torch_extensions/_prroi_pooling/build.ninja...
Building extension module _prroi_pooling...
[1/3] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -isystem ..........
 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -std=c++11 -c /home1/ads/pytracking-master/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu -o prroi_pooling_gpu_impl.cuda.o

FAILED: prroi_pooling_gpu_impl.cuda.o 

/home1/ads/pytracking-master/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu_impl.cu(1): error: expected a declaration

1 error detected in the compilation of "/tmp/tmpxft_0000becb_00000000-6_prroi_pooling_gpu_impl.cpp1.ii".

**Comment by goutamgmb** [comment]
Have you tried using the pytorch 0.4.1 version (see pytorch041 branch)? We have had fewer issues installing precise roi pooling with pytorch 0.4.1. In case the issue persists, please check the original precise roi pooling repo at https://github.com/vacancy/PreciseRoIPooling.

**Comment by Hevans123** [comment]
Really thank you for your advice.Now I can run with cuda 10. And I think pytorch with cuda 9.2 is also ok . But cuda 9.0 may not work well if using 2080ti , after looking for solutions online,I found that there will be some bugs between cuda9.0 and gpu 2080ti.(I just guess,maybe it can also run well)

**Comment by bigmoking** [comment]
Ｉ meet the some question, details follow:torch/include/c10/cuda/CUDAStream.h:6:10: fatal error: cuda_runtime_api.h: No such file or directory.
 #include <cuda_runtime_api.h>
Loading extension module _prroi_pooling...
Can not compile Precise RoI Pooling library.
