### ISSUE TITLE
ModuleNotFoundError: No module named 'ltr.admin.local'  when run_video.py or  run_webcam.py is runnning? 

### ISSUE THREAD

**Issue by chenziwen23** [visionml/pytracking#295]
importlib.import_module('ltr.admin.' + m);

NOT FOUND  ltr.admin.local file.

**Comment by 2006pmach** [comment]
Please setup the environment as specified in the instal scripts [here](https://github.com/visionml/pytracking/blob/master/INSTALL.md#setup-the-environment).
