### ISSUE TITLE
DLL load failed problem when run it in WIN10  resolved!

### ISSUE THREAD

**Issue by yuandongbo123** [visionml/pytracking#299]
`File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\imp.py", line 342, in load_dynamic
return _load(spec)
File "", line 696, in _load
File "", line 670, in _load_unlocked
File "", line 583, in module_from_spec
File "", line 1043, in create_module
File "", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.`

This is my runtime error!

When my device was configured cuda11.+python3.7+torch1.8

When my equipment is updated to cuda10.1+python3.7+torch1.6, it still made an error

Finally I updated my device to cuda10.0+python3.7+torch1.2 , it work!!!!

The last Please make sure to use  cuda10.0+python3.7+torch1.2  .Because I tried so many other combinations that I wouldn't give you a job

**Comment by martin-danelljan** [comment]
Hi. Thank you for sharing this.

**Comment by MSathishkumar1990** [comment]
I also tried with the same configuration. But, it is not working for me. Please help me to solve this issue.
