### ISSUE TITLE
Jetson Nano

### ISSUE THREAD

**Issue by senanursahin** [visionml/pytracking#300]
Hello,

Can I run this project on Jetson Nano 4GB?
Arm64 arch doesn't supports anaconda so if I manually download the requisities declared on environment.yaml would that work?

Thanks in advance,
Sena

**Comment by DeepBrainsMe** [comment]
您的邮件已收到，我会尽快查看处理。（此邮件为自动回复）

**Comment by senanursahin** [comment]
多谢

**Comment by Ahsanr312** [comment]
> Hello,
> 
> Can I run this project on Jetson Nano 4GB? Arm64 arch doesn't supports anaconda so if I manually download the requisities declared on environment.yaml would that work?
> 
> Thanks in advance, Sena

Yes, you can. What you have to do is that install each and everything individually via sudo apt-get and pip commands. I am using the same repository for Jetson Tx2
