### ISSUE TITLE
Has E.T. Track be released?

### ISSUE THREAD

**Issue by songtianhui** [visionml/pytracking#306]
Hello! I wonder where can I find code for the latest E.T Track.
It's perfect work and I'm looking forward.
Thank you!

**Comment by orilifs** [comment]
Yea, me too :)

**Comment by martin-danelljan** [comment]
Hey! Patience :)

Philipp is working hard on it currently, so you can expect it fairly soon.

/Martin

**Comment by orilifs** [comment]
> Hey! Patience :)
> 
> Philipp is working hard on it currently, so you can expect it fairly soon.
> 
> /Martin

Excellent news, thank you for the update, looking forward to it.

**Comment by orilifs** [comment]
May I help with the development/implementation in someway please?

If so, please leave an email address or a means of contacting you guys :)

**Comment by MoiseevMikhail** [comment]
Hello! Any updates on this issue?
