### ISSUE TITLE
Trackers Initialization Time

### ISSUE THREAD

**Issue by Ahsanr312** [visionml/pytracking#308]
Is there any way to reduce the initialization time of trackers? @martin-danelljan @2006pmach 

Once we select Region of Interest (ROI) that is used to initialize the tracker that we are using, this takes quite alot of time and I don't think so it's applicable in real time applications. 

Can anyone help?

**Comment by orilifs** [comment]
Can you give more details about your environment and which tracker you're running?

Is it within a container?
Is it a dimp-family tracker, etc'?

Some logs and profiling would be helpful as well

I think I might have a suggestion but without unerstanding your use case and from what environment you're running the tracker it might be a moot suggestion

**Comment by Ahsanr312** [comment]
First of all, sorry for the late reply. The answer to your questions are:

I am using Dimp18 and have tried Dimp50, PrDimp18, PrDimp50 and KeepTrack as well. All of the mentioned trackers take some seconds to start (i.e. start the track after ROI is selected). 
My hardware is Jetson TX2 and I have followed the repository for all the installations. 

To tackle the problem, currently I initialize the tracker with an arbitrary small ROI and when it start tracking, I reset the tracker and re-initialize it with the target object and it is way more real time than the first time selection of ROI. 

I hope you have understand the problem as well the solution I am applying to it for now.

**Comment by martin-danelljan** [comment]
Hi. You can try reducing the [number of initial iterations](https://github.com/visionml/pytracking/blob/114ae6f26e0e397791e1d2034cf3bb7da0c1e1de/pytracking/parameter/dimp/dimp50.py#L23) or reducing the [number and types of data augmentation](https://github.com/visionml/pytracking/blob/114ae6f26e0e397791e1d2034cf3bb7da0c1e1de/pytracking/parameter/dimp/dimp50.py#L32). You will find the same parameters/setting in most of our trackers.

**Comment by Ahsanr312** [comment]
Thanks for the answer. 
Are these initial iterations and data augmentation for online learning, right?

**Comment by orilifs** [comment]
Any chance the lag you're expriencing is due to ninja-build of the prroi code?

Can you post the output of whatever it is your're running when you exprience the delay please?
