### ISSUE TITLE
Code Crash

### ISSUE THREAD

**Issue by Ahsanr312** [visionml/pytracking#309]
I am using pytracking repo and getting this error "Segmentation fault (core dumped)" when I press "q" or "r" for quit and reset tracker respectively. Any sort of help will really be admired @goutamgmb @martin-danelljan @2006pmach

**Comment by Ahsanr312** [comment]
I solved the issue by re-building opencv

**Comment by laisimiao** [comment]
@Ahsanr312 which version of cv2 you used is fine?
