### ISSUE TITLE
no checkpoint file 

### ISSUE THREAD

**Issue by universefall** [visionml/pytracking#31]
Hello,I run the command "python run_webcam.py atom default".But shows:
Traceback (most recent call last):
  File "run_webcam.py", line 35, in <module>
    main()
  File "run_webcam.py", line 31, in main
    run_webcam(args.tracker_name, args.tracker_param, args.debug)
  File "run_webcam.py", line 20, in run_webcam
    tracker.run_webcam(debug)
  File "../pytracking/evaluation/tracker.py", line 94, in run_webcam
    tracker.track_webcam()
  File "../pytracking/tracker/base/basetracker.py", line 179, in track_webcam
    self.initialize_features()
  File "../pytracking/tracker/atom/atom.py", line 19, in initialize_features
    self.params.features.initialize()
  File "../pytracking/features/extractor.py", line 16, in initialize
    f.initialize()
  File "../pytracking/features/deep.py", line 95, in initialize
    self.net, _ = load_network(net_path_full, backbone_pretrained=False)
  File "../ltr/admin/loading.py", line 36, in load_network
    raise Exception('No matching checkpoint file found')
Exception: No matching checkpoint file found

I check the model file in /networks, it is there. and the local.py shows that "**settings.network_path = '/home/bill/Documents/pytracking/pytracking/networks/**'",however the probelm still happen.

**Comment by universefall** [comment]
I didn't unzip it

**Comment by universefall** [comment]
when I run eco, it works. the eco model file is in the same directory with atom model. But when I run with atom, it fails.

**Comment by WenjieYan1997** [comment]
you shou change the name from atom_default.pth.tar to atom_default.pth

**Comment by buaaswf** [comment]
> you shou change the name from atom_default.pth.tar to atom_default.pth

However, it cannot work

**Comment by dulibubai** [comment]
the link of the pre_trained id 404 not found in the install.sh file

**Comment by dulibubai** [comment]
the link of the pre_trained id 404 not found in the install.sh file

**Comment by dulibubai** [comment]
can you provide the valid links of the models ,Thanks very much!

**Comment by universefall** [comment]
https://github.com/visionml/pytracking/issues/31#issuecomment-502948348
Ok, I’ll share with you later.

**Comment by dulibubai** [comment]
Thanks




------------------ 原始邮件 ------------------
发件人: "Bill"<notifications@github.com>; 
发送时间: 2019年6月19日(星期三) 中午12:13
收件人: "visionml/pytracking"<pytracking@noreply.github.com>; 
抄送: "唯我杜尊"<1257618212@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [visionml/pytracking] no checkpoint file  (#31)




#31 (comment)
 Ok, I’ll share with you later.

**Comment by universefall** [comment]
> Thanks
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Bill"<notifications@github.com>; 发送时间: 2019年6月19日(星期三) 中午12:13 收件人: "visionml/pytracking"<pytracking@noreply.github.com>; 抄送: "唯我杜尊"<1257618212@qq.com>; "Comment"<comment@noreply.github.com>; 主题: Re: [visionml/pytracking] no checkpoint file (#31) #31 (comment) Ok, I’ll share with you later. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

https://pan.baidu.com/s/10tdzt5Sw8lazEegHVCLj9g 
提取码: p8mc

**Comment by dulibubai** [comment]
Thanks  very much



------------------ 原始邮件 ------------------
发件人: "Bill"<notifications@github.com>; 
发送时间: 2019年6月19日(星期三) 下午3:02
收件人: "visionml/pytracking"<pytracking@noreply.github.com>; 
抄送: "唯我杜尊"<1257618212@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [visionml/pytracking] no checkpoint file  (#31)



 
Thanks
 …
 ------------------ 原始邮件 ------------------ 发件人: "Bill"notifications@github.com; 发送时间: 2019年6月19日(星期三) 中午12:13 收件人: "visionml/pytracking"pytracking@noreply.github.com; 抄送: "唯我杜尊"1257618212@qq.com; "Comment"comment@noreply.github.com; 主题: Re: [visionml/pytracking] no checkpoint file (#31) #31 (comment) Ok, I’ll share with you later. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
  
https://pan.baidu.com/s/10tdzt5Sw8lazEegHVCLj9g
 提取码: p8mc

**Comment by dulibubai** [comment]
Excuse me, can you give me the model of eco ？Thanks again!

**Comment by universefall** [comment]
> Excuse me, can you give me the model of eco ？Thanks again!

https://pan.baidu.com/s/12r3NHUj4crX1CpDV9jZHhw 
提取码: ecbh

**Comment by goutamgmb** [comment]
@universefall Thanks a lot for sharing the models on baidu!

**Comment by QIQIVTrackingY** [comment]
Excuse me, can you provide me the with the model of atom?

**Comment by universefall** [comment]
> Excuse me, can you provide me the with the model of atom?

Link:https://pan.baidu.com/s/1sqkyIxxPO4jGEZRIp2Bxfg  
Password:7dq0

**Comment by Terry1iu** [comment]
Excuse me
Have you solved this problem yet?
I met the same situation, could you please tell me the solution?

**Comment by berkantay** [comment]
I am having the same issue where are the model files and where should the be placed?

**Comment by eladmeir** [comment]
The Baidu link for ECO pre trained weights is broken, can someone please provide a new one?
Maybe add it also to the google drive folder where all the others can be found?

Thanks

**Comment by Fanthers** [comment]
I am having the same issue, but i use kys

**Comment by eladmeir** [comment]
@Fanthers 
You can find KYS' pre-trained weights, with most of the others, on
https://drive.google.com/drive/folders/1WGNcats9lpQpGjAmq0s0UwO6n22fxvKi?usp=sharing

**Comment by Fanthers** [comment]
> @Fanthers
> You can find KYS' pre-trained weights, with most of the others, on
> https://drive.google.com/drive/folders/1WGNcats9lpQpGjAmq0s0UwO6n22fxvKi?usp=sharing

ok, thank you!

**Comment by han-0111** [comment]
> Hello,I run the command "python run_webcam.py atom default".But shows: Traceback (most recent call last): File "run_webcam.py", line 35, in main() File "run_webcam.py", line 31, in main run_webcam(args.tracker_name, args.tracker_param, args.debug) File "run_webcam.py", line 20, in run_webcam tracker.run_webcam(debug) File "../pytracking/evaluation/tracker.py", line 94, in run_webcam tracker.track_webcam() File "../pytracking/tracker/base/basetracker.py", line 179, in track_webcam self.initialize_features() File "../pytracking/tracker/atom/atom.py", line 19, in initialize_features self.params.features.initialize() File "../pytracking/features/extractor.py", line 16, in initialize f.initialize() File "../pytracking/features/deep.py", line 95, in initialize self.net, _ = load_network(net_path_full, backbone_pretrained=False) File "../ltr/admin/loading.py", line 36, in load_network raise Exception('No matching checkpoint file found') Exception: No matching checkpoint file found
> 
> I check the model file in /networks, it is there. and the local.py shows that "**settings.network_path = '/home/bill/Documents/pytracking/pytracking/networks/**'",however the probelm still happen.

Have you solved this issue? I'm having a similar problem with keeptrack. I would be grateful if you could share your experience.Thanks

**Comment by Obadahheyari** [comment]
did anyone solve the issue i keep getting this error and cant find the network file :( 
Traceback (most recent call last):
  File "/home/obadah/Desktop/trackers/pytracking/run_webcam.py", line 41, in <module>
    main()
  File "/home/obadah/Desktop/trackers/pytracking/run_webcam.py", line 37, in main
    run_webcam(args.tracker_name, args.tracker_param, args.debug, visdom_info)
  File "/home/obadah/Desktop/trackers/pytracking/run_webcam.py", line 22, in run_webcam
    tracker.run_video_generic(debug=debug, visdom_info=visdom_info)
  File "/home/obadah/Desktop/trackers/pytracking/pytracking/evaluation/tracker.py", line 285, in run_video_generic
    tracker = MultiObjectWrapper(self.tracker_class, params, self.visdom, fast_load=True)
  File "/home/obadah/Desktop/trackers/pytracking/pytracking/evaluation/multi_object_wrapper.py", line 21, in __init__
    self.tracker_copy.initialize_features()
  File "/home/obadah/Desktop/trackers/pytracking/pytracking/tracker/tomp/tomp.py", line 22, in initialize_features
    self.params.net.initialize()
  File "/home/obadah/Desktop/trackers/pytracking/pytracking/features/net_wrappers.py", line 53, in initialize
    super().initialize()
  File "/home/obadah/Desktop/trackers/pytracking/pytracking/features/net_wrappers.py", line 37, in initialize
    self.load_network()
  File "/home/obadah/Desktop/trackers/pytracking/pytracking/features/net_wrappers.py", line 31, in load_network
    self.net = load_network(self.net_path, **self.net_kwargs)
  File "/home/obadah/Desktop/trackers/pytracking/pytracking/utils/loading.py", line 31, in load_network
    net, _ = ltr_loading.load_network(path_full, **kwargs)
  File "/home/obadah/Desktop/trackers/pytracking/ltr/admin/loading.py", line 62, in load_network
    raise Exception('No matching checkpoint file found')
Exception: No matching checkpoint file found
