### ISSUE TITLE
When running dimp the iou_net is called from a file with ATOM in its name.

### ISSUE THREAD

**Issue by orilifs** [visionml/pytracking#311]
When running dimp family trackers this is the call for iou_net -> predict_iou():
 "/ltr/models/bbreg/atom_iou_net.py" with the method: "predict_iou()"
 Is this normal/expected behaviour?
 
 Thanks!

**Comment by 2006pmach** [comment]
Yes, please have a look at the DiMP paper for the details. To summarize, DiMP uses the same bounding box regression branch as ATOM (but retrained so the weighs differ) but proposes a novel target classification branch.
