### ISSUE TITLE
pytracking-master train lasot in keep_track

### ISSUE THREAD

**Issue by 123wfl** [visionml/pytracking#315]
How to train lasot dataset with keep_track or can you provide the json file of lasot

**Comment by 2006pmach** [comment]
Please check the Readme (KeepTrack section) everything is explained and shared there.

**Comment by 123wfl** [comment]
How to test nfs dataset

**Comment by 2006pmach** [comment]
https://github.com/visionml/pytracking/tree/master/pytracking
