### ISSUE TITLE
TypeError: batch must contain tensors, numbers, dicts or lists; found <class 'torch.Tensor'>

### ISSUE THREAD

**Issue by yutinyang** [visionml/pytracking#32]
ｗｈｅｎ running 13 epoch:

raise Exception('Too small bounding box.')
Exception: Too small bounding box.

**Comment by martin-danelljan** [comment]
Hi. I did a fix in the sampler that should prevent this from happening. Please tell us if it keeps happening in the new version.

**Comment by yutinyang** [comment]
Ｉ　can not remember clearly when I downloaded your code,maybe a month ago. But this  mistake
can be avoided by rerunning this code.I do not know why this could be so？

**Comment by martin-danelljan** [comment]
That is just because it happens very rarely. But with the new version is should not happen at all.

**Comment by iminfine** [comment]
> That is just because it happens very rarely. But with the new version is should not happen at all.

No，the problem still is not well fixed. I am training Dimp50 and it happened on epoch 15.

**Comment by martin-danelljan** [comment]
Hi. Could you please check if you have the latest version of the master branch. Please also provide the PyTorch version. Are you using the standard dimp50 train setting?

**Comment by iminfine** [comment]
Yes, I use the latest version with the standard dimp50 train setting. My PyTorch version is 1.2. I saw you recommend PyTorch 1.4 in another issue, however it seems the code now is not suitable for this version. The error is:  

Original Traceback (most recent call last):
  File "/jmain01/home/JAD014/mxm06/bxg73-mxm06/.conda/envs/pytracking/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/jmain01/home/JAD014/mxm06/bxg73-mxm06/.conda/envs/pytracking/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "../ltr/models/tracking/dimpnet.py", line 54, in forward
    train_feat = self.extract_backbone_features(train_imgs.view(-1, *train_imgs.shape[-3:]))
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**Comment by martin-danelljan** [comment]
We have seen this issue when using MultiGPU. Are you using that?

**Comment by iminfine** [comment]
No，I use a single GPU for training.

**Comment by martin-danelljan** [comment]
Are you sure? Because in the traceback it seems like torch parallel is used:

> Original Traceback (most recent call last):
> File "/jmain01/home/JAD014/mxm06/bxg73-mxm06/.conda/envs/pytracking/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker

Check if the use multigpu option really is false in the train setting please.

**Comment by iminfine** [comment]
> Are you sure? Because in the traceback it seems like torch parallel is used:
> 
> > Original Traceback (most recent call last):
> > File "/jmain01/home/JAD014/mxm06/bxg73-mxm06/.conda/envs/pytracking/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
> 
> Check if the use multigpu option really is false in the train setting please.

Sorry，I didn't make it clear. Initially, PyTorch 1.4 with multigpu was used, and I got this error. It seems multigpu training is not compatible with PyTorch 1.4, then I used PyTorch 1.2 instead.
As I submitted my job to a cluster, most gpus were used. Therefore, I had to use a single gpu(multigpu option is false). So the errors are both existing.

**Comment by martin-danelljan** [comment]
Hi. Yes so there seems to be a bug when running multi-GPU with Pytorch 1.4. We have not had time to look into that. Please use 1.2 for multi-gpu in the meantime. 

The "too small bounding box" bug seems to be something that has reappeared with newer PyTorch versions as well. But this should happen very rarely, and the training should restart from the previous checkpoint if the fail_save option is set to True in the trainer.

**Comment by whittenator** [comment]
Good Morning,

When running Dimp, Is there a way to specify which GPU to use for tracking if you have multiple? For example, I have 2 NVIDIA 2080 Titan, and I want to run dimp on cuda device #1 instead of cuda device #0. 

Thanks

**Comment by martin-danelljan** [comment]
Good afternoon,

This is not related to this issue really. Anyway, best thing is to use `CUDA_VISIBLE_DEVICES`, e.g.

```
CUDA_VISIBLE_DEVICES=1 python run_tracker.py dimp dimp50 --dataset_name "otb" --sequence 0
