### ISSUE TITLE
Classification methodology in ATOM and DIMP

### ISSUE THREAD

**Issue by Ahsanr312** [visionml/pytracking#320]
I have question regarding the tracking methodology of ATOM and DIMP. I have read the research papers as well but I am still not clear on this point. 

In the first frame we select ROI (Region of Interest) and then it is tracked in the subsequent frames via classification and estimation. The classification (ResNet18 or ResNet50) computes or extracts features from the whole input image or is it some patch in the image only? I am confused and also mentioning a part from ATOM paper. 
![ATOm](https://user-images.githubusercontent.com/39031891/158962336-dbbf8458-4104-46f9-aa0b-f548dd6c66e1.jpg)

**Comment by 2006pmach** [comment]
We do exactly what you highlighted in your screen shot. We process an image patch of a fixed size. The content in the patch corresponds to a region that is 5 times (or any other fixed factor) the estimated target size. So if the estimated target in the previous frame was very small then the patch contains only a small part of the whole image but if the target was relatively large then the patch can contain the entire frame. The patch center is determined by the center of the detected target in the last frame. We resample/interpolate the frames and the corresponding regions to guarantee the fixed resolution of the patch. Typically this patch is called the search region and can be visualized in visdom. Search regions of fixed size are used in almost all modern trackers these days.

**Comment by Ahsanr312** [comment]
Thank you for your detailed answer.

**Comment by martin-danelljan** [comment]
Note also that the patch resolution and size can be customised in the parameter file.
