### ISSUE TITLE
RUN tracker on Extension camera

### ISSUE THREAD

**Issue by AliFayod** [visionml/pytracking#324]
Hi, 
I am looking for the instruction that turns the camera on, as I want to turn on the secondary camera connected through the USB port
Example: cv2.videoCapture(0) for primary camera and cv2.videoCapture(1) for secondary camera
Now in this project how do I turn on a secondary camera where the code is modified to do that
Note that I run the code as follows and the main camera works:
"python run_webcam.py dimp dimp50 "
Thank you.

**Comment by Ahsanr312** [comment]
Hello, 
You need make changes to tracker.py file which can be found in evaluation folder. 
Scroll down the file and you will see a function run_webcam() there change cv.VideoCapture(0) to cv.VideoCapture(1)

**Comment by AliFayod** [comment]
It's DONE
Thank you bro. @Ahsanr312
