### ISSUE TITLE
Where is the code for RTS?

### ISSUE THREAD

**Issue by xjtuwh** [visionml/pytracking#327]
@2006pmach @martin-danelljan

**Comment by martin-danelljan** [comment]
Thanks for the interest! We are working on it. Hope to release it within a month or two.

**Comment by sfchen94** [comment]
Hi, Dr. Martin. Thanks for your work on RTS.
Will it release recently?

> Thanks for the interest! We are working on it. Hope to release it within a month or two.

**Comment by sfchen94** [comment]
> Hi @sfchen94, I just released the code for RTS.

Cool

**Comment by sfchen94** [comment]
> Hi @sfchen94, I just released the code for RTS.
Just report that I can successfully train and inference RTS.
<img width="563" alt="image" src="https://user-images.githubusercontent.com/113094161/191322590-1dcf5660-26f0-424d-8c1d-6489347e34c7.png">

One drawback might be it takes a huge GPU memory when training.
Except for reducing batch size, is there any way I can try to reduce GPU memory?
