### ISSUE TITLE
How to plot the confidence map?

### ISSUE THREAD

**Issue by universefall** [visionml/pytracking#33]
Could u please tell me how to plot the confidence map of the correlation result? just like in your paper? Thank you every much.

**Comment by universefall** [comment]
sorry for interupting. I found it. Thanks for your work!

**Comment by DeepBrainsMe** [comment]
> sorry for interupting. I found it. Thanks for your work!

sorry , could u please tell me ,I didn't find it yet

**Comment by martin-danelljan** [comment]
Hi.
Just set the debug level to 2 with e.g. `--debug 2`
