### ISSUE TITLE
select target when I zoom in video 

### ISSUE THREAD

**Issue by AliFayod** [visionml/pytracking#331]
I use >>>python2 run_webcam.py dimp dimp50
when it run I can use mouse roll to zoom in/out but when zooming I can't select target ,the moue be hand icon, how I can change this feature to be able to select target with zooming 
thanks.

**Comment by Ahsanr312** [comment]
You will need to add this feature manually. 
One solution is to change the functionality of zoom. By first click a specific surrounding area should zoom in and then a bounding box must be drawn and then with a right click zoom out and start processing/tracking.
