### ISSUE TITLE
any possible convert to onnx model?

### ISSUE THREAD

**Issue by jcyhcs** [visionml/pytracking#333]
hi,professor:
in this time, any method that convert DiMP pretrained model to onnx format?
please help!

**Comment by daisatojp** [comment]
Hi I'm not professor, though I'll try to answer. :)
You can convert the model partially (e.g. resnet backbone). But it's not enough to run dimp on onnx model. I think the biggest issue is that the dimp needs automatic differentiation (https://github.com/visionml/pytracking/blob/master/pytracking/tracker/dimp/dimp.py#L742) and prroi_pooling. I think onnx does not support these functions.

**Comment by jcyhcs** [comment]
oh, is there any method in this repository could export pretrained model to onnx format ?? please tell me, thanks!

**Comment by daisatojp** [comment]
Hi, there is no conversion script for DiMP (and other trackers). You have to write by yourself. Use `torch.onnx.export`. Thanks!
