### ISSUE TITLE
On the implementation of update_sample_weights in dimp.py

### ISSUE THREAD

**Issue by YangC-1** [visionml/pytracking#335]
Hi, I am a bit confused about the update strategy used in the function _update_sample_weights_ in _dimp.py_. The snippet of the code is following:

                # Update weights
                if prev_ind is None:
                    sw /= 1 - lr
                    sw[r_ind] = lr
                else:
                    sw[r_ind] = sw[prev_ind] / (1 - lr)
            sw /= sw.sum()
            if init_samp_weight is not None and sw[:num_init].sum() < init_samp_weight:
                sw /= init_samp_weight + sw[num_init:].sum()
                sw[:num_init] = init_samp_weight / num_init

Could you please explain the logic behind this? Many thanks!

**Comment by martin-danelljan** [comment]
Hi.
The first case
```
            if prev_ind is None:
                sw /= 1 - lr
                sw[r_ind] = lr
```
is when the memory is not yet full. The new sample gets the weight `lr` and the rest are down weighted accordingly (to sum to one).

The next
```
sw[r_ind] = sw[prev_ind] / (1 - lr)
```
is when the memory is full and we are replacing the oldest sample. We then take the weight of the previous sample divided by the forgetting factor.

The last part
```
if init_samp_weight is not None and sw[:num_init].sum() < init_samp_weight:
            sw /= init_samp_weight + sw[num_init:].sum()
            sw[:num_init] = init_samp_weight / num_init
```
just makes sure that the initial samples remains at a total minimum weight of `init_samp_weight`
