### ISSUE TITLE
RuntimeError: Error building extension '_prroi_pooling'

### ISSUE THREAD

**Issue by mark-91** [visionml/pytracking#337]
Ubuntu 18.04.6 LTS
torch===1.4.0
cuda 10.1
python run_webcam.py dimp dimp50    QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

QObject::moveToThread: Current thread (0x55b10c970780) is not the object's thread (0x55b10af35d30).
Cannot move to target thread (0x55b10c970780)

Using /home/ai/.cache/torch_extensions/py310_cu102 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/ai/.cache/torch_extensions/py310_cu102/_prroi_pooling/build.ninja...
Building extension module _prroi_pooling...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ai/anaconda3/envs/pytracking/lib/python3.10/site-packages/torch/include -isystem /home/ai/anaconda3/envs/pytracking/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/ai/anaconda3/envs/pytracking/lib/python3.10/site-packages/torch/include/TH -isystem /home/ai/anaconda3/envs/pytracking/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/ai/anaconda3/envs/pytracking/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/ai/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o 
FAILED: prroi_pooling_gpu.o 
c++ -MMD -MF prroi_pooling_gpu.o.d -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/ai/anaconda3/envs/pytracking/lib/python3.10/site-packages/torch/include -isystem /home/ai/anaconda3/envs/pytracking/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/ai/anaconda3/envs/pytracking/lib/python3.10/site-packages/torch/include/TH -isystem /home/ai/anaconda3/envs/pytracking/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/ai/anaconda3/envs/pytracking/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/ai/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c -o prroi_pooling_gpu.o 
/home/ai/pytracking/ltr/external/PreciseRoIPooling/pytorch/prroi_pool/src/prroi_pooling_gpu.c:17:10: fatal error: THC/THC.h: No such file or directory
 #include <THC/THC.h>
          ^~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/ai/anaconda3/envs/pytracking/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1740, in _run_ninja_build
    subprocess.run(
  File "/home/ai/anaconda3/envs/pytracking/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ai/pytracking/pytracking/run_webcam.py", line 41, in <module>
    main()
  File "/home/ai/pytracking/pytracking/run_webcam.py", line 37, in main
    run_webcam(args.tracker_name, args.tracker_param, args.debug, visdom_info)
  File "/home/ai/pytracking/pytracking/run_webcam.py", line 22, in run_webcam
    tracker.run_webcam(debug, visdom_info)
  File "/home/ai/pytracking/pytracking/../pytracking/evaluation/tracker.py", line 451, in run_webcam
    out = tracker.track(frame, info)
  File "/home/ai/pytracking/pytracking/../pytracking/evaluation/multi_object_wrapper.py", line 165, in track
    out = self.trackers[obj_id].initialize(image, init_info_split[obj_id])
  File "/home/ai/pytracking/pytracking/../pytracking/tracker/dimp/dimp.py", line 84, in initialize
    self.init_classifier(init_backbone_feat)
  File "/home/ai/pytracking/pytracking/../pytracking/tracker/dimp/dimp.py", line 573, in init_classifier
    self.target_filter, _, losses = self.net.classifier.get_filter(x, target_boxes, num_iter=num_iter,
  File "/home/ai/pytracking/pytracking/../ltr/models/target_classifier/linear_filter.py", line 97, in get_filter
    weights = self.filter_initializer(feat, bb)
  File "/home/ai/anaconda3/envs/pytracking/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ai/pytracking/pytracking/../ltr/models/target_classifier/initializer.py", line 164, in forward
    weights = self.filter_pool(feat, bb)
  File "/home/ai/anaconda3/envs/pytracking/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ai/pytracking/pytracking/../ltr/models/target_classifier/initializer.py", line 45, in forward
    return self.prroi_pool(feat, roi1)
  File "/home/ai/anaconda3/envs/pytracking/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ai/pytracking/pytracking/../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/prroi_pool.py", line 28, in forward
    return prroi_pool2d(features, rois, self.pooled_height, self.pooled_width, self.spatial_scale)
  File "/home/ai/pytracking/pytracking/../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 44, in forward
    _prroi_pooling = _import_prroi_pooling()
  File "/home/ai/pytracking/pytracking/../ltr/external/PreciseRoIPooling/pytorch/prroi_pool/functional.py", line 30, in _import_prroi_pooling
    _prroi_pooling = load_extension(
  File "/home/ai/anaconda3/envs/pytracking/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1144, in load
    return _jit_compile(
  File "/home/ai/anaconda3/envs/pytracking/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1357, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/ai/anaconda3/envs/pytracking/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1469, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/ai/anaconda3/envs/pytracking/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension '_prroi_pooling'
(pytracking) ai@ai:~/pytracking/pytracking$ nvidia-smi
Sat Jun 11 19:20:55 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   47C    P8     4W /  N/A |    275MiB /  3903MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1250      G   /usr/lib/xorg/Xorg                 18MiB |
|    0   N/A  N/A      1335      G   /usr/bin/gnome-shell               68MiB |
|    0   N/A  N/A      1661      G   /usr/lib/xorg/Xorg                 92MiB |
|    0   N/A  N/A      1816      G   /usr/bin/gnome-shell               24MiB |
|    0   N/A  N/A      2279      G   ...273679352589424270,131072       67MiB |
+----------------------------------------------

how can i solve this error i use Ubuntu 20.4 and i have same problem
thanks

**Comment by Ahsanr312** [comment]
I have gone through the installations and made a repo for it. Follow it, hopefully your problem will be resolved. Currently it seems you are using an older version of pytorch. Install 1.8.0 with cuda 10.2. 
https://github.com/Ahsanr312/Installing-CUDA-Toolkit-cuDNN-OpenCV-and-PyTorch-on-Ubuntu-20.04

**Comment by mark-91** [comment]
> I have gone through the installations and made a repo for it. Follow it, hopefully your problem will be resolved. Currently it seems you are using an older version of pytorch. Install 1.8.0 with cuda 10.2. https://github.com/Ahsanr312/Installing-CUDA-Toolkit-cuDNN-OpenCV-and-PyTorch-on-Ubuntu-20.04

thank you it work for me
