### ISSUE TITLE
AttributeError: 'float' object has no attribute 'is_video_sequence'

### ISSUE THREAD

**Issue by klyjb** [visionml/pytracking#34]
Thank you for your excellent work !
my python = 3.5 , my pytorch = 0.4.1 , my cuda = 9.0
when I used the imagenetvid datasets to train the ATOM, and I run the "python 
  run_training.py bbreg atom_default" 
1. I got the first error:
  ****File "../ltr/data/sampler.py", line 93, in __getitem__
    dataset = random.choices(self.datasets, self.p_datasets)[0]
  AttributeError: module 'random' has no attribute 'choices'****
  This error is that my python version is 3.5,and I made the following changes:
    **dataset = random.choice([self.datasets, self.p_datasets])[0]**
   So,I'm not sure if I did it right.
2. After correcting according to error 1, I encountered a second error:
    **File "../ltr/data/sampler.py", line 94, in __getitem__
    is_video_dataset = dataset.is_video_sequence()
    AttributeError: 'float' object has no attribute 'is_video_sequence'**
Could you please tell me how I need to fix it? thank you!

**Comment by goutamgmb** [comment]
You should have:  
dataset = random.choice(self.datasets)

You won't be able to use the self.p_datasets here ofc. However that should not have any major impact.
