### ISSUE TITLE
SELECT TRAIN_IMAGES

### ISSUE THREAD

**Issue by sumzora** [visionml/pytracking#345]
HELLO, I am very interested in the method of update train images in paper "Transforming Model Prediction for Tracking", which is described as "we include one previously tracked frame and replace it with the most recent frame that achieves a target classifier confidence higher than a threshold." 
HOWEVER, I can not find the comparison process in CODE (ToMP). Actually,  the code of <def _sample_visible_ids> in <sampler.py> is random.choices(valid_ids, k=num_ids). 
Is I missing something? Could you tell me where described the process "the most recent frame that achieves a target classifier confidence higher than a threshold" in CODE?
Thank you so much! 
HAVE A NICE DAY!

**Comment by 2006pmach** [comment]
Hi

So we only use the described strategy during inference and not during training. During training we sample two random samples the temporally first, we treat as initial frame with and the other as most recent frame stored in the memory. On top with sample a third frame that appears later in the sequence as the other two and treat it as test frame. If you want to checkout the inference code where we select the most recent memory frame according to a threshold, have a look here https://github.com/visionml/pytracking/blob/master/pytracking/tracker/tomp/tomp.py#L186
