### ISSUE TITLE
How could i get the quantitative indexes of tracking results?

### ISSUE THREAD

**Issue by lebronze** [visionml/pytracking#347]
Hello!

I have already run the run_tracker.py successfully and got the coordinates of bounding boxs of the test frames.

Then i want to get some quantitative indexes of the tracker, such as success,precision, how could i do?

I checked the files in folder of evalution, but i don't find any useful founctions.

**Comment by martin-danelljan** [comment]
Hey. Check [the jupyter notebook] :)(https://github.com/visionml/pytracking/blob/cdab204883fd427e8f8f8afce672cfa5a5b47dc9/pytracking/notebooks/analyze_results.ipynb)
