### ISSUE TITLE
Dataset inference Visualisation

### ISSUE THREAD

**Issue by sfchen94** [visionml/pytracking#350]
Hi, is it possible to visualize without **visdom** when we run the tracker on some dataset sequence?

For example, run_video.py give us a frame with a box by imshow,
how can I have the same painted image when inference by a run_tracker.py?

**Comment by 2006pmach** [comment]
For visualization I would recommend using `visdom` it is already mentioned in the install instructions and it is fully supported in the code, see [here](https://github.com/visionml/pytracking/tree/master/pytracking#visdom). You can for example create a file in the root of this project and paste this code

```python
import pytracking

pytracking.run_tracker("dimp", "super_dimp", dataset_name="lasot", sequence=0, debug=3,
visdom_info={'use_visdom': True, 'server': "127.0.0.1", 'port': 8097})
```
This runs the tracker `super_dimp` on the first LaSOT sequence and visualizes the results in the browsers `localhost:8097`.  Make sure that you start visdom first on the GPU node in case you don't have a GPU in your local machine you might need ssh into the GPU with port forwarding.

**Comment by sfchen94** [comment]
Actually, it is challenging to apply port forwarding from my local GPU server.
But it's OK. I can still use visdom in my with Xserver.
