### ISSUE TITLE
AttributeError: 'ATOMSampler' object has no attribute 'sequence_list'

### ISSUE THREAD

**Issue by klyjb** [visionml/pytracking#36]
Hello,Thank you for your answer to my last question.
Let me say it again for clarity:
my python = 3.5 , my pytorch = 0.4.1 , my cuda = 9.0
when I used the imagenetvid datasets to train the ATOM, and I run the "python
run_training.py bbreg atom_default"
1. Firstly:
 **File "../ltr/data/sampler.py", line 95, in __getitem__
    is_video_dataset = dataset.is_video_sequence()
    TypeError: is_video_sequence() missing 1 required positional argument: 'self'**
**File "../ltr/data/sampler.py", line 102, in __getitem__
    seq_id = random.randint(0, dataset.get_num_sequences() - 1)
    TypeError: get_num_sequences() missing 1 required positional argument: 'self'**
    I added self in the appropriate place.
2.Secondly,I got the error:
    **File "../ltr/dataset/imagenetvid.py", line 64, in get_num_sequences
    return len(self.sequence_list)
    AttributeError: 'ATOMSampler' object has no attribute 'sequence_list'**
    Could you please tell me how I need to fix it? thank you!

**Comment by goutamgmb** [comment]
Check if you have correctly set the dataset in the train_settings file. For using imagenetvid, you should have 
imagenetvid_train = ImagenetVID()

**Comment by klyjb** [comment]
Thank you ! I actually forgot to put the parentheses after I copied it
