### ISSUE TITLE
Question about GNSteepestDescent

### ISSUE THREAD

**Issue by daisatojp** [visionml/pytracking#360]
Hi, I have a question about filter optimization for DiMP.

I know DiMP uses steepest descent for filter optimization. I found the implementation of steepest descent in here [ltr/models/meta/steepestdescent.py]( https://github.com/visionml/pytracking/blob/master/ltr/models/meta/steepestdescent.py). I thought the g ([steepestdescent.py, L70](https://github.com/visionml/pytracking/blob/master/ltr/models/meta/steepestdescent.py#L70)) corresponds to the ∇L in DiMP paper,  but the `g = TensorList(torch.autograd.grad(r, meta_parameter, u, create_graph=True))` means multiplication of Jacobian(of residuals and filter parameters) and residuals, and it is not ∇L. Is this right? If so, what does corresponds to the ∇L?

Thanks!

**Comment by martin-danelljan** [comment]
Hi. This is actually the gradient. Recall that for an L2 loss

L(w) = 1/2 ||r(w)||^2

the gradient becomes

g = (dL/dw)^T = (dL/dr dr/dw)^T = (dr/dw)^T r
