### ISSUE TITLE
Definition self.get_backbone_clf_feat(backbone_feat) function at ltr/models/tracking/tompnet.py

### ISSUE THREAD

**Issue by shen-ttt** [visionml/pytracking#369]
Thank you for your amazing work! 

I am trying to understand the logic of ToMP and find the definition of self.get_backbone_clf_feat intriguing (Line 63). There seems to be no declaration of this function in the tomp framework. And ToMP Tracker keeps calling this function and it works perfectly. 

And I searched the entire codebase, these files define this function but none of them is used in tompnet.py. 

```
./ltr/models/tracking/dimpnet.py:    def get_backbone_clf_feat(self, backbone_feat):
./ltr/models/tracking/kysnet.py:    def get_backbone_clf_feat(self, backbone_feat):
./ltr/models/target_candidate_matching/target_candidate_matching.py:    def get_backbone_clf_feat(self, backbone_feat):
./ltr/models/rts/rts_net.py:    def get_backbone_clf_feat(self, backbone_feat):
```

Could you help me and explain to me a bit? Thank you!

**Comment by 2006pmach** [comment]
To me it looks like `get_backbone_clf_feat()` is no longer used nor called. The only function that used it is `extract_head_feat()` which is only called by `extract_features()` which is not used anywhere from what I see. Probably these functions are just leftovers and should have been removed. I haven't tested yet if inference and training still work when removing these parts but I think it should be fine.

**Comment by shen-ttt** [comment]
Yeah, I was wrong. Those functions are never used. 

Thank you! Will close this thread now
