### ISSUE TITLE
code release date for paper "learning discriminative model prediction for tracking"

### ISSUE THREAD

**Issue by HugoFeng** [visionml/pytracking#37]
Hi, when will the code be released for paper "learning discriminative model prediction for tracking"? Thank you.

**Comment by martin-danelljan** [comment]
Hi. Thank you very much for your interest. We plan to release the DiMP code during summer. Probably in July.

Thank you for your patience.
/Martin

**Comment by HugoFeng** [comment]
Great. Thank you for your reply.

Hugo

**Comment by DeepBrainsMe** [comment]
Hello，I wonder  which journal is your paper DiMP submitted?

**Comment by martin-danelljan** [comment]
Hi. The paper just got accepted at ICCV 2019 as Oral presentation.

**Comment by DeepBrainsMe** [comment]
Hello，I  wonder when will your release the  DiMP CODE  in  pytracking .Although I have notice your words in README.md ，is there a precise clock time about releasing code.


------------------ 原始邮件 ------------------
发件人: "Martin Danelljan"<notifications@github.com>;
发送时间: 2019年7月24日(星期三) 上午7:10
收件人: "visionml/pytracking"<pytracking@noreply.github.com>;
抄送: "JesseWang"<1098069058@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [visionml/pytracking] code release date for paper "learningdiscriminative model prediction for tracking" (#37)




Hi. The paper just got accepted at ICCV 2019 as Oral presentation.

**Comment by martin-danelljan** [comment]
Hi. Thank you for your patience. The code for DiMP is now released.
Regards,
Martin
