### ISSUE TITLE
Running RTS without initial bounding box

### ISSUE THREAD

**Issue by jama1017** [visionml/pytracking#378]
Hi!

Currently, when I run `run_video.py`, it either asks me to draw a bounding box or pass in the parameters for one. I wonder if there is a way to inference with RTS on a video without having to define a bounding box at the beginning?

**Comment by mattpfr** [comment]
Hello @jama1017, by construction, RTS is designed to initialize with a bounding box. 
What would you like to initialize with, if not with a bounding box ?

**Comment by jama1017** [comment]
Hi @mattpfr! Thanks for the quick reply. I guess I was asking if the initial bounding box can be found automatically somehow, instead of inputting it manually? Do I need a separate algorithm that detects the bounding box for the object of interest?

**Comment by mattpfr** [comment]
RTS inference is semi-supervised. You need to provide either an initial segmentation mask, or an initial bounding box from which we infer automatically a segmentation mask. 

If you do not want to provide an initial bounding box you'd have to either provide an even weaker annotation (scribbles for instance) or text description of what you want to track (still semi-supervised) or figure it out automatically (unsupervised). These are not supported by RTS, but are active research topics, so you'll definitely find papers and techniques to do that.

**Comment by jama1017** [comment]
Awesome. Got it. Thanks for the insight!
