### ISSUE TITLE
UAV123 result different in TOMP

### ISSUE THREAD

**Issue by ChuangGe66** [visionml/pytracking#389]
I tested the UAV123 dataset on the computer and the result was success=67.8, but the result provided by your team was 69.0. What's the reason? I used a pre-training model that I downloaded. Looking forward to your team's reply.

**Comment by ChuangGe66** [comment]
@mattpfr @goutamgmb

**Comment by cute-koala** [comment]
I had the same question. I followed the same steps using the source code and got a result of 66.9 on uav123
