### ISSUE TITLE
AttributeError: 'JPEG' object has no attribute 'decompressor'

### ISSUE THREAD

**Issue by klyjb** [visionml/pytracking#39]
Hello, thank you for your excellent work.
my python = 3.5 , my pytorch = 0.4.1 , my cuda = 9.0
I have successfully started training ATOM on the imagenetvid dataset, as shown below: 
**[train: 5, 5 / 1000] FPS: 21.1 (23.9)  ,  Loss/iou: 0.03104  ,  Loss/total: 0.03104
[train: 5, 6 / 1000] FPS: 25.0 (338.9)  ,  Loss/iou: 0.03108  ,  Loss/total: 0.03108
[train: 5, 7 / 1000] FPS: 28.9 (361.6)  ,  Loss/iou: 0.03132  ,  Loss/total: 0.03132
[train: 5, 8 / 1000] FPS: 32.6 (363.5)  ,  Loss/iou: 0.03093  ,  Loss/total: 0.03093**
![image](https://user-images.githubusercontent.com/38532766/58251356-02612c80-7d96-11e9-9e12-26961e138bdb.png)

but every epoch gets an error before it starts, without affecting the run and the preservation of the model:
**ERROR: Could not read image "/home/ly/disk2/xqian/DaSiamRPN/code/data/ILSVRC2015/Data/VID/train/ILSVRC2015_VID_train_0000/ILSVRC2015_train_00117001/000154.JPEG"
Could not load libjpeg-turbo library
Using opencv_loader instead.
ERROR: Could not read image "/home/ly/disk2/xqian/DaSiamRPN/code/data/ILSVRC2015/Data/VID/train/ILSVRC2015_VID_train_0001/ILSVRC2015_train_00238001/000093.JPEG"
Could not load libjpeg-turbo library
Using opencv_loader instead.
ERROR: Could not read image "/home/ly/disk2/xqian/DaSiamRPN/code/data/ILSVRC2015/Data/VID/train/ILSVRC2015_VID_train_0000/ILSVRC2015_train_00069007/000005.JPEG"
ERROR: Could not read image "/home/ly/disk2/xqian/DaSiamRPN/code/data/ILSVRC2015/Data/VID/train/ILSVRC2015_VID_train_0001/ILSVRC2015_train_00259029/000136.JPEG"
Could not load libjpeg-turbo library
Could not load libjpeg-turbo library
Using opencv_loader instead.
Using opencv_loader instead.
Exception ignored in: <bound method JPEG.__del__ of <jpeg4py._py.JPEG object at 0x7fa89aae7a58>>
Traceback (most recent call last):
  File "/home/ly/.envs/xq/lib/python3.5/site-packages/jpeg4py/_py.py", line 215, in __del__
    if self.decompressor is not None:
AttributeError: 'JPEG' object has no attribute 'decompressor'
Exception ignored in: <bound method JPEG.__del__ of <jpeg4py._py.JPEG object at 0x7f8cbd876a58>>
Traceback (most recent call last):
  File "/home/ly/.envs/xq/lib/python3.5/site-packages/jpeg4py/_py.py", line 215, in __del__
    if self.decompressor is not None:
AttributeError: 'JPEG' object has no attribute 'decompressor'
Exception ignored in: <bound method JPEG.__del__ of <jpeg4py._py.JPEG object at 0x7f6c2eba7a20>>
Traceback (most recent call last):
  File "/home/ly/.envs/xq/lib/python3.5/site-packages/jpeg4py/_py.py", line 215, in __del__
    if self.decompressor is not None:
AttributeError: 'JPEG' object has no attribute 'decompressor'
Exception ignored in: <bound method JPEG.__del__ of <jpeg4py._py.JPEG object at 0x7f5145360a90>>**
Could you please tell me how I need to fix it? thank you!

**Comment by klyjb** [comment]
Sorry to disturb you again, but I got an error after 40 epochs training finished. As follows:
 
![image](https://user-images.githubusercontent.com/38532766/58295789-81d91500-7e03-11e9-80ca-449e271d026b.png)

**Comment by goutamgmb** [comment]
Hi,

Did you install jpeg4py? 

sudo apt-get install libturbojpeg
pip install jpeg4py

**Comment by klyjb** [comment]
Thank you, I just execute 'pip install jpeg4py'. When 'sudo apt-get install libturbojpeg' is also executed, the error is gone.

**Comment by martin-danelljan** [comment]
Great. This is also explained in the [installation instructions](https://github.com/visionml/pytracking/blob/master/INSTALL.md).
