### ISSUE TITLE
AttributeError: module 'torch.utils.data.dataloader' has no attribute '_use_shared_memory'

### ISSUE THREAD

**Issue by huangbiubiu** [visionml/pytracking#40]
In PyTorch `1.1.0`, it seems that `_use_shared_memory` it no longer available. So https://github.com/visionml/pytracking/blob/4b668d779fde3b923655f1f98025cecdbc57952c/ltr/data/loader.py#L15 will raise the error.

**Comment by HugoFeng** [comment]
I have the same problem, and I simply comment out these lines. Then it runs fine

**Comment by martin-danelljan** [comment]
Thank you for sharing the issue. This is properly fixed in the latest commit.
