### ISSUE TITLE
no moduloe named ltr.admin.local

### ISSUE THREAD

**Issue by Muhammadmudassir180** [visionml/pytracking#407]
i am trying to run tracker with video and i am getting error mentioned below. 
i am giving this command: python3 run_video.py dimp dimp50 video.mp4
![Screenshot from 2023-10-30 04-24-00](https://github.com/visionml/pytracking/assets/75354671/0fe40a73-cef4-4a49-8890-fb2744b51854)

**Comment by 2006pmach** [comment]
Please read the Readme
