### ISSUE TITLE
How to get box confidence score?

### ISSUE THREAD

**Issue by yarkable** [visionml/pytracking#409]
Hi, may I ask how can I get the confidence score of a tracker? In the code, it's set to be 1 in default.
![image](https://github.com/visionml/pytracking/assets/33142987/6cfbfe4e-ae9a-412d-8d02-7652913796cd)

**Comment by Setarekhosravi** [comment]
@yarkable Hi, for ToMP, or KeepTrack please check `out` value in the `tracker.py` code. It includes bounding boxes, object presence score, and inference time.
![Uploading Screenshot from 2023-12-04 14-10-03.png…]()

**Comment by yarkable** [comment]
thank you very much @Setarekhosravi

**Comment by eliafranc** [comment]
@setarekhosravi Is there also a way to get a score for the RTS tracker?

**Comment by setarekhosravi** [comment]
@eliafranc  Hi,
I think there is, check this [code](https://github.com/visionml/pytracking/blob/master/pytracking/tracker/rts/rts.py) and print or plot some variables such as clf_scores, I think you will find a way.
