### ISSUE TITLE
Can't download the .pth file.

### ISSUE THREAD

**Issue by shuida** [visionml/pytracking#41]
I'm sorry I can't download 'atom_fault.pth' and 'resnet18_vggmconv1.pth' from Google in China. Could you please provide other download links?

**Comment by sidml** [comment]
@shuida Even i am unable to download the pth file. Its most likely not a location issue (tried through VPN). I am getting the following error - Not Found Error 404.

**Comment by ilarele** [comment]
I get the same error, 404. https://docs.google.com/uc?export=download&id=1ZTdQbZ1tyN27UIwUnUrjHChQb5ug2sxr

**Comment by goutamgmb** [comment]
Can you access the google drive folder? https://drive.google.com/drive/folders/1WVhJqvdu-_JG1U-V0IqfxTUa1SBPnL0O

**Comment by QIQIVTrackingY** [comment]
Do you slove the problem? The file that i downloaded is a broken file
