### ISSUE TITLE
Train on custom dataset

### ISSUE THREAD

**Issue by setarekhosravi** [visionml/pytracking#410]
Hi, thank you for your great work.
I want to train ToMP on my own dataset, how can I prepare my data?
thank you.

**Comment by 2006pmach** [comment]
See [here](https://github.com/visionml/pytracking/blob/master/ltr/dataset/lasot.py) for how LaSOT is integrated. Simply create a new dataset class for your own dataset and create the sequences as explained in lasot.py. Then specify your dataset during training in the training config files.
