### ISSUE TITLE
Save video results

### ISSUE THREAD

**Issue by arielkantorovich** [visionml/pytracking#411]
Hi,
There is option to save video results in run_video.py?

**Comment by Setarekhosravi** [comment]
@arielkantorovich 
Hi, Do you want to save bounding boxes?

**Comment by Setarekhosravi** [comment]
you can find output bounding boxes by checking `out` value. 
check the `target_bbox`.
![image](https://github.com/visionml/pytracking/assets/101149859/2e06956a-15bf-4bb6-b14b-de6e5ee074ab)

@arielkantorovich
