### ISSUE TITLE
Can tomp process multiple images at once as batches?

### ISSUE THREAD

**Issue by ninono12345** [visionml/pytracking#419]
Hello @martin-danelljan I want to ask you for advice, since you have been more active.

Is it possible so that for example if I'm tracking 4 objects at once, that I could send into track a tensor with 4 batches, instead, so tracking woud do all computations for all 4 objects at once, instead passing through neural networks 4 separate times?

I tried just to simulate 2 frame tracking to do torch.cat with 2 image tensors (the same frame to be tracked 2 times, next time I would use different ones), didn't work... Tried to torch.cat inside classify_target all variables that enter neural networks, also didn't work... Now I'm studying the algorithm, but I wanted to ask you in theory is this possible, or would it be too much work?

Thank you

**Comment by 2006pmach** [comment]
Have a look at [TaMOs](https://openaccess.thecvf.com/content/WACV2024/papers/Mayer_Beyond_SOT_Tracking_Multiple_Generic_Objects_at_Once_WACV_2024_paper.pdf) our most recent tracker. It is designed to track multiple objects at the same time more efficiently.

**Comment by ninono12345** [comment]
Sorry, didn't forgot to reply, already figured it out. I changed the predict_cls_bbreg_filters_parallel to be more like predict_filter, changed the end of the function a little bit, and also changed a little bit tomp.py classify target
