### ISSUE TITLE
A problem about training

### ISSUE THREAD

**Issue by klyjb** [visionml/pytracking#42]
Hello, thank you for your excellent work.
my python = 3.5 , my pytorch = 0.4.1 , my cuda = 9.0
I have successfully trained on vid dataset and tested on OTB100 dataset according to your guidance, but I need to retrain with single channel grayscale map, could you please give me some guidance on how to do it? Since I have suffered many mistakes, thank you!

**Comment by goutamgmb** [comment]
Hi,

In the default training setting, 5% of the frames are converted to grayscale (see line 39: transform_joint = dltransforms.ToGrayscale(probability=0.05)). If you want to train using only the grayscale images, you can set the probability to 1.0.
