### ISSUE TITLE
Support for LMDB Dataset

### ISSUE THREAD

**Issue by kalyan0510** [visionml/pytracking#424]
Do you plan to support loading lmdb version of datasets?  
Has anyone observed training speedups on your servers by using lmdb formats in your tracking projects?

**Comment by 2006pmach** [comment]
I tested the LMDB format on the hardware we had at ETH at the time but its performance was not convincing. So we won't support this. But feel free to modify the dataset classes to support this format. (Up to you to test if it works well on your system.)
