### ISSUE TITLE
About extract features

### ISSUE THREAD

**Issue by zlj199502** [visionml/pytracking#43]
Hi,
I have a question. In the paper, your take backbone features from ResNet-18 Block3
and Block4 as input. But, you take features ResNet-18 Block2 and Block3 as input in the code. is it?

**Comment by goutamgmb** [comment]
Hi,

Unfortunately, we have a different naming convention in the code compared to the one used in the paper. We use the features from second and third residual blocks, i.e. output of conv3_x and conv4_x from original resnet paper (https://arxiv.org/pdf/1512.03385.pdf).
