### ISSUE TITLE
Are there DiMP-50 and DiMP-18?

### ISSUE THREAD

**Issue by BlueAnthony** [visionml/pytracking#44]
As paper "Learning Discriminative Model Prediction for Tracking" mentioned, are there DiMP-50 and DiMP-18 in here?

**Comment by martin-danelljan** [comment]
Hi. Thanks for your interest! Our plan is to release the DiMP code here during July or August.
Regards,
Martin

**Comment by martin-danelljan** [comment]
DiMP is now released!

Regards,
Martin
