### ISSUE TITLE
unknown error in running [run_webcam.py]

### ISSUE THREAD

**Issue by yangdashi888** [visionml/pytracking#45]
When I run the cmd--"python run_webcam.py atom default", the error occured。the error is 'ModuleNotFoundError: No module named 'dlframework.common.utils''。I don't know why it have this error。
Please help。

**Comment by martin-danelljan** [comment]
Hi. 
This is strange. Can you verify that you are running the command inside the pytracking/pytracking folder and that you have the latest version of the code?

**Comment by yangdashi888** [comment]
Hi.
1、The code is latest. The problem occurs at "filt:ltr/admin/loading function:def torch_load_legacy(path)".The path of pretrain model is correct. The picture is :
![Uploading 360截图20190625101604014.jpg…]()

My operating environment is:
pytorch 1.0    
OS: windows 10
python 3.6
2、When run the cmd --"python run_training.py bbreg atom_default", the error occured. The error is “RuntimeError: Error building extension '_prroi_pooling'”.
 After I download this code，I didn’t compile the "Precise ROI pooling". because I think the code has compile automatically, I don't know if I'm doing the right thing.The pictur is:
![Uploading 360截图20190625103354008.jpg…]()
  Finally，Can you have a description of how to configure project on window. We would appreciate it very much.

**Comment by yangdashi888** [comment]
Hi.
1、The code is latest. The problem occurs at "filt:ltr/admin/loading function:def torch_load_legacy(path)".The path of pretrain model is correct. The picture is :
![Uploading 360截图20190625101604014.jpg…]()

My operating environment is:
pytorch 1.0    
OS: windows 10
python 3.6
2、When run the cmd --"python run_training.py bbreg atom_default", the error occured. The error is “RuntimeError: Error building extension '_prroi_pooling'”.
 After I download this code，I didn’t compile the "Precise ROI pooling". because I think the code has compile automatically, I don't know if I'm doing the right thing.The pictur is:
![Uploading 360截图20190625103354008.jpg…]()
  Finally，Can you have a description of how to configure project on window. We would appreciate it very much.

**Comment by martin-danelljan** [comment]
We have never tested it on Windows. I am not even sure if the PrROI Pool has Windows support (please refer to their documentation). The loading error seems strange, I will try to look in to it.

But I strongly suggest you run this on Ubuntu, or some other Linux-based system.

**Comment by 983632847** [comment]
Hi Martin, how can I use the latest VOT toolkit to run this state-of-the-art ATOM tracker?

**Comment by martin-danelljan** [comment]
> Hi Martin, how can I use the latest VOT toolkit to run this state-of-the-art ATOM tracker?

Hi. Our latest version (that also includes the DiMP tracker) now supports VOT toolkit integration. Please [check here](https://github.com/visionml/pytracking/tree/master/pytracking#vot-integration).
