### ISSUE TITLE
Can anyone provide Need for Speed dataset?

### ISSUE THREAD

**Issue by Hevans123** [visionml/pytracking#47]
Hi,  I can't download NFS Dataset. Can any one offer this dataset ? I would  appreciate it very much.

**Comment by Dheeraj-shahul** [comment]
Hello @Hevans123 did you get the NFS dataset? I've been working on a Computer Vision project and the NFS dataset could be very helpful and i am looking for it everywhere. Could you please provide the source link if you have any?

 Thanks in advance.
