### ISSUE TITLE
Question: Target Scale in ATOM

### ISSUE THREAD

**Issue by UndecidedBoy** [visionml/pytracking#48]
Hello,

Well written paper and great code!

In my quest to understanding ATOM, I'm currently at a stage where I want to display the search area used by the tracker. When the search area is calculated it is compared to a maximum threshold (max_image_sample_size) and a minimum threshold (min_image_sample_size) to obtain the new target scale.

https://github.com/visionml/pytracking/blob/243a056905eb687f4a662c4271210a60f734ea84/pytracking/tracker/atom/atom.py#L49-L52

But looking at these parameters, I got confused since both are set to the same value.

https://github.com/visionml/pytracking/blob/4b668d779fde3b923655f1f98025cecdbc57952c/pytracking/parameter/atom/default.py#L19-L21

Shouldn't the two parameters be different from each other?

In the meantime, thanks for your time and efforts.
Regards!

**Comment by martin-danelljan** [comment]
Hi. Thanks!

Those parameters decide the initial scale of the target, so that the sample size becomes in that range (by default it is fixed, that's why min=max).

To check the limits of the target scale, see this line:

https://github.com/visionml/pytracking/blob/243a056905eb687f4a662c4271210a60f734ea84/pytracking/tracker/atom/atom.py#L104

**Comment by UndecidedBoy** [comment]
Hello again.

Thanks for the detailed response!

So if I understood correctly, firstly the program looks at the absolute target size (BBox that the user draws at the start in the image) and the absolute search area is calculated from that (5 times the area of the BBox). 
Afterward, a new scale for the target is calculated with:

https://github.com/visionml/pytracking/blob/243a056905eb687f4a662c4271210a60f734ea84/pytracking/tracker/atom/atom.py#L49-L52

The new scale is adapted for a search area of 288x288 and is used to find the base target size with: 

https://github.com/visionml/pytracking/blob/243a056905eb687f4a662c4271210a60f734ea84/pytracking/tracker/atom/atom.py#L57-L58

Also, this absolute search area is rescaled to a tensor of dimension 288x288.
Finally, the new base scale and tensor of 288x288 are fed to the DNN.

Another question:
What were the benefits/limits of using a nonsquare shape for the search area?

In the meantime, thanks for your time and consideration!

**Comment by goutamgmb** [comment]
Hi,

That is correct.

We haven't tried using a non-square shape, although it should be easy to try. Since we assume random target motion, we decided to use a square shape.

**Comment by UndecidedBoy** [comment]
Hi,

Thanks for the response!
