### ISSUE TITLE
How to put different subprocesses on different GPUs?

### ISSUE THREAD

**Issue by shuida** [visionml/pytracking#49]
Hello @martin-danelljan ,
Thanks for your great work!
I want to accelerate testing greatly by multiprocessing. However, if I double the number of subprocesses, the FPS will half. I find by nvidia-smi that different subprocesses run on the same GPU, which may cause blocking and slow FPS. So, how can I put different subprocesses on different GPUs to accelerate testing?

**Comment by martin-danelljan** [comment]
Hi.
Thank you for your appreciation! :)
Multiple GPUs in pytracking is not supported yet and not really in our pipeline at the moment. It can probably be implemented quite easily by assigning a device to the different tasks. There is already a device parameter that could be used for this.

Feel free to hack something yourself, or make it looking nice as well and contribute to the repo XD

Regards,
Martin

**Comment by shuida** [comment]
OK, I'll have a try. Thank you so much!
