### ISSUE TITLE
python run_tracker.py strange information.

### ISSUE THREAD

**Issue by fyaft2012** [visionml/pytracking#53]
Hello,
I installed the pytracking toolkit using provided install.sh (I found that I installed pytorch 1.1.0 with install.sh scirpt, I am not sure it is okay or not) on my ubuntu 16.04 with two GPUs (TaitanX and Tesla K40). And when I run commend: "python run_tracker.py atom default --sequence Soccer"
it gave the message:

"(pytracking) root@aiserver-desktop:/home/aiserver/pytracking/pytracking# python run_tracker.py atom default --sequence Soccer
Tracker: atom default None ,  Sequence: Soccer
**Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.**
Done"

Could you help me out this probelm, thanks!

**Comment by martin-danelljan** [comment]
Hi. Which version of CUDA did you install with? Also, please verify that pytorch is is properly installed in the environment with GPU support. Do this in the terminal:

`conda activate [name of your pytracking env]`
`python`
`import torch`
`a = torch.rand(3,3).cuda()`

Does this work?

**Comment by fyaft2012** [comment]
Hi martin, thanks for your timely reply. I did what you suggested, it gave the message:
"AssertionError: 
The NVIDIA driver on your system is too old (found version 9020).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver."

I think maybe I should downgrade pytorch version that has been compiled with current version of the CUDA driver.  Since I have other project with pytorch 0.4.1 which works with current CUDA driver. I will try and let you know the results.
Thanks!
