### ISSUE TITLE
CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

### ISSUE THREAD

**Issue by yinwang950613** [visionml/pytracking#55]
when i run python run_video.py, i get CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
but i have done bash install.sh conda_install_path pytracking

**Comment by martin-danelljan** [comment]
Hi. Do you have an Nvidia graphics card that is CUDA capable? Also, please check [this answer](https://github.com/visionml/pytracking/issues/53#issuecomment-516519173) to see if your environment is properly setup.

**Comment by yinwang950613** [comment]
Thank you! I have I have solved this problem.But when i run run_video.py :
File "/home/tanjianhao/zsq/pytracking/pytracking/features/extractor.py", line 65, in stride
    return torch.Tensor(TensorList([f.stride() for f in self.features if self._return_feature(f)]).unroll())
TypeError: `__cuda_array_interface__` must be a dict

But when i don't use zhe Tensorlist like:
 torch.Tensor([f.stride() for f in self.features if self._return_feature(f)])
The code works fine

**Comment by martin-danelljan** [comment]
> Thank you! I have I have solved this problem.But when i run run_video.py :
> File "/home/tanjianhao/zsq/pytracking/pytracking/features/extractor.py", line 65, in stride
> return torch.Tensor(TensorList([f.stride() for f in self.features if self._return_feature(f)]).unroll())
> TypeError: `__cuda_array_interface__` must be a dict
> 
> But when i don't use zhe Tensorlist like:
> torch.Tensor([f.stride() for f in self.features if self._return_feature(f)])
> The code works fine

That fix is not good. Please use PyTorch v1.1 for now instead, as [discussed here](https://github.com/visionml/pytracking/issues/61#issuecomment-522492326).

**Comment by martin-danelljan** [comment]
Support for pytorch v1.2 is there in the latest version now, that also includes the code for DiMP.
