### ISSUE TITLE
Question: the results in vot-toolkit did not work

### ISSUE THREAD

**Issue by mengmeng18** [visionml/pytracking#56]
Could you please tell me how can i use the results of VOT2018 in pytracking(.txt) to get EAO? It seems like that put the results in vot-toolkit did not work.Thanks a lot!

**Comment by mengmeng18** [comment]
It looks like lack of the information of lost frames

**Comment by goutamgmb** [comment]
Hi,

Do you mean the results from the google drive folder? What error did you get?

**Comment by mengmeng18** [comment]
There is no direct results from google drive folder, using the model from google drive , by runninng pytracking-run_tracker.py in vot2018, i can get a list of TXT file results ,how can i evaluate this results to get accuracy and EAO?  I put the .txt results in vot-toolkit ,but got EAO=0.

**Comment by goutamgmb** [comment]
If you have created the vot workspace, download the results from https://drive.google.com/drive/folders/1TpDfLwW-PtN9krOhrlTONvAt5NszkLR1 and save it in vot-workspace/results/ATOM folder. In run_analysis.m file set trackers = tracker_list('ATOM'), and run the run_analysis script. You should get the EAO results.

**Comment by mengmeng18** [comment]
Thanks ! But could you please tell me how to get this results? I have tried to change basetracker.py and running.py  to add bboxes, if overlap < 0 , bboxes will append 1 and skip 5 frames ,just like vot-toolkit . But i don't know where to add reinitialize information when testing.

**Comment by goutamgmb** [comment]
Hi,

The VOT integration is included in the latest release. Check https://github.com/visionml/pytracking/tree/master/pytracking#vot-integration for details.
