### ISSUE TITLE
TypeError: `__cuda_array_interface__` must be a dict

### ISSUE THREAD

**Issue by MarsBase7** [visionml/pytracking#61]
I was running the test script: `python run_webcam.py atom default`
When I had choosen something and tagged it, then clicked the mouse in the end, the script turned out these error information:

> Using /tmp/torch_extensions as PyTorch extensions root...
> Detected CUDA files, patching ldflags
> Emitting ninja build file /tmp/torch_extensions/_prroi_pooling/build.ninja...
> Building extension module _prroi_pooling...
> ninja: no work to do.
> Loading extension module _prroi_pooling...
> Traceback (most recent call last):
>   File "run_webcam.py", line 35, in <module>
>     main()
>   File "run_webcam.py", line 31, in main
>     run_webcam(args.tracker_name, args.tracker_param, args.debug)
>   File "run_webcam.py", line 20, in run_webcam
>     tracker.run_webcam(debug)
>   File "../pytracking/evaluation/tracker.py", line 94, in run_webcam
>     tracker.track_webcam()
>   File "../pytracking/tracker/base/basetracker.py", line 189, in track_webcam
>     self.initialize(frame, init_state)
>   File "../pytracking/tracker/atom/atom.py", line 61, in initialize
>     feat_max_stride = max(self.params.features.stride())
>   File "../pytracking/features/extractor.py", line 64, in stride
>     return torch.Tensor(TensorList([f.stride() for f in self.features if self._return_feature(f)]).unroll())
> TypeError: `__cuda_array_interface__` must be a dict

How could I debug it?
My enviorment is : rtx2060, driver 430, cuda 10.0

**Comment by UndecidedBoy** [comment]
Hi, 
had the same error last week, if you use PyTorch v1.2 try to downgrade to PyTorch v.1.1.

There's also this other issue #55 where the person had the same problem but solved it in a different way.

**Comment by martin-danelljan** [comment]
Hi. Thanks @MarsBase7  for posting the issue and @UndecidedBoy for posting the temporary fix. I will look into this when i have time. Please use *PyTorch v1.1* in the meantime. I have changed the installation script so that it always installs v1.1 now.

**Comment by MarsBase7** [comment]
Thanks all, I am playing well now with pytorch1.1 ^.^

**Comment by martin-danelljan** [comment]
Support for pytorch v1.2 is there in the latest version now, that also includes the code for DiMP.
