### ISSUE TITLE
multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker

### ISSUE THREAD

**Issue by yongwuSHU** [visionml/pytracking#62]
hello!
"anaconda3/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown len(cache))" 

it always appear this warning after 1 epoch when training the model "ATOM", but i can continue to train, how i can fix that.
thank you!

**Comment by yongwuSHU** [comment]
by the way, my computer [Titan xp, python 3.6, pytorch 1.1]

**Comment by goutamgmb** [comment]
Hi,

This seems to be a general PyTorch issue, not related to pytracking (https://discuss.pytorch.org/t/issue-with-multiprocessing-semaphore-tracking/22943). Unfortunately we are not aware of the exact cause of the problem, or the solution.

**Comment by yongwuSHU** [comment]
thank you,@goutamgmb
