### ISSUE TITLE
Train with Multi-GPUs

### ISSUE THREAD

**Issue by noUmbrella** [visionml/pytracking#63]
Dose pytracking can train with Multi-GPUs? If it can, please show me an example. Thank you for your excellent works.

**Comment by martin-danelljan** [comment]
No, we do not support Multi-GPU for inference at least. Integrating Multi-GPU training should be easy though, and something we might look into soon. But it something that you could quite easily implement yourself for now :)

**Comment by noUmbrella** [comment]
Yes, what I mentioned is training with multi-GPU. I have tried to add "net = nn.DataParallel(train_model)" after " net = atom_models.atom_resnet18(backbone_pretrained=True)". But, it fails and reports error. Looking forward to your help, thanks.

**Comment by noUmbrella** [comment]
@martin-danelljan

**Comment by martin-danelljan** [comment]
What is the error?

**Comment by noUmbrella** [comment]
It shows that:
Traceback (most recent call last):
  File "run_training.py", line 60, in <module>
    main()
  File "run_training.py", line 54, in main
    run_training(args.train_module, args.train_name, args.cudnn_benchmark)
  File "run_training.py", line 43, in run_training
    expr_func(settings)
  File "../ltr/train_settings/bbreg/atom_default.py", line 97, in run
    optimizer = optim.Adam(actor.net.bb_regressor.parameters(), lr=1e-3)
  File "/home/myaccount/local/anaconda3/envs/pytracking/lib/python3.7/site-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'bb_regressor' @martin-danelljan

**Comment by goutamgmb** [comment]
Hi,

As a short term hack, you could try adding `actor.net = nn.DataParallel(actor.net)` after `optimizer = optim.Adam(actor.net.bb_regressor.parameters(), lr=1e-3)` (line 96).

**Comment by noUmbrella** [comment]
Thanks for your reply! I will try it. @goutamgmb

**Comment by yongwuSHU** [comment]
Hi,
I tried your code, it also shows that:
"Traceback (most recent call last):
  File "run_training.py", line 59, in <module>
    main()
  File "run_training.py", line 54, in main
    run_training(args.train_module, args.train_name, args.cudnn_benchmark)
  File "run_training.py", line 43, in run_training
    expr_func(settings)
  File "../ltr/train_settings/bbreg/atom_default.py", line 99, in run
    optimizer = optim.Adam(actor.net.bb_regressor.parameters(), lr=1e-3)
  File "/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'bb_regressor'"
 @goutamgmb

**Comment by goutamgmb** [comment]
@yongwuSHU  

It seems you are doing `actor.net = nn.DataParallel(actor.net)` before  'optimizer = optim.Adam(actor.net.bb_regressor.parameters(), lr=1e-3)'. Could you try the other way round instead? i.e.
`    # Create network
    net = atom_models.atom_resnet18(backbone_pretrained=True)

    # Set objective
    objective = nn.MSELoss()

    # Create actor, which wraps network and objective
    actor = actors.AtomActor(net=net, objective=objective)

    # Optimizer
    optimizer = optim.Adam(actor.net.bb_regressor.parameters(), lr=1e-3)

   actor.net = nn.DataParallel(actor.net)

    # Learning rate scheduler
    lr_scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=15, gamma=0.2)


    # Create trainer
    trainer = LTRTrainer(actor, [loader_train, loader_val], optimizer, settings, lr_scheduler)

    # Run training (set fail_safe=False if you are debugging)
    trainer.train(40, load_latest=True, fail_safe=False)`

**Comment by yongwuSHU** [comment]
thank you , it is okay to train, but it still trains with sigle GPU, it can not train with multi-GPUs. my environmental configuration is okay, i don't know what is wrong.
 @goutamgmb

**Comment by martin-danelljan** [comment]
Multi-GPU training is supported in the latest release (which includes the code for DiMP). Please check the [dimp50 train settings file](https://github.com/visionml/pytracking/blob/master/ltr/train_settings/dimp/dimp50.py).

**Comment by yongwuSHU** [comment]
thank you, your team's works are amazing,.

**Comment by martin-danelljan** [comment]
Thanks!

**Comment by marcosly** [comment]
> thank you , it is okay to train, but it still trains with sigle GPU, it can not train with multi-GPUs. my environmental configuration is okay, i don't know what is wrong.
> @goutamgmb

I have the same issue while using nn.DataParallel, it is okay to train, but it still trains with sigle GPU, , did you fix it?
