### ISSUE TITLE
General question: Training on datasets like COCO

### ISSUE THREAD

**Issue by armham01** [visionml/pytracking#64]
At first excellent work, I am already looking forward to the new publications.

I have a general question, does it actually make sense to train the tracker only on a data set like COCO? I want to train the tracker (ATOM) on my own use case and the images I use will also be used for training our detector, so no sequences but single images with the labeled objects.

**Comment by martin-danelljan** [comment]
Hi. Thank you!

We have not investigated training the tracker only on still-image datasets. But i guess the result should not be very bad at least. You can try training ATOM only on COCO (by removing the other datasets in the train script) and check the performance. If you want to integrate such a dataset, just follow what we did for COCO, i.e. sampling the same image and warping it.

**Comment by goutamgmb** [comment]
Hi, 

If the target is going out of search area due to fast translations, you could just try increasing the search area. I don't think training with higher frame rate videos can help here.

**Comment by armham01** [comment]
makes sense, I guess you are referring to this parameter in https://github.com/visionml/pytracking/blob/master/pytracking/parameter/atom/default.py
params.search_area_scale = 5                # Scale relative to target size  
right?

**Comment by goutamgmb** [comment]
Yes, try increasing the search_area_scale parameter. I would also suggest increasing params.max_image_sample_size and params.min_image_sample_size proportionally so that the base target size used for tracking remains unchanged.

**Comment by armham01** [comment]
Thanks for your help, I will try it out and report if that help regarding fast translations and let you know, maybe relevant for other people as well.
