### ISSUE TITLE
Could we have a community to discuss the ATOM tracker? Thanks to the platform provided by the authors.

### ISSUE THREAD

**Issue by 983632847** [visionml/pytracking#65]
QQ:
![ATOM_QQ](https://user-images.githubusercontent.com/32026228/63938916-89f6bf80-ca98-11e9-8265-ca2d0c1067f0.png)

**Comment by 983632847** [comment]
Can anyone talk about how to test the VOT datasets using ATOM tracker?  For example, use the VOT toolkit or pysot-toolkit. There seem to some problems with using the latest VOT toolkit.

**Comment by goutamgmb** [comment]
Hi, 

Did you try using the vot integration included in the latest release (https://github.com/visionml/pytracking/tree/master/pytracking#vot-integration)? What error did you get?
