### ISSUE TITLE
BN in ATOM

### ISSUE THREAD

**Issue by noUmbrella** [visionml/pytracking#68]
In ATOM, from what I read,  for backbone network, its all parameters are freezed during training, and only bn_mean and bn_var are updated. Is this reasonable?

**Comment by goutamgmb** [comment]
Hi,

Thanks for pointing this out! In the current implementation, the bn_mean and bn_var are indeed updated during training, although this was not intentional. We will test if not updating them has any effect.

**Comment by noUmbrella** [comment]
Thanks for your attention!@goutamgmb
