### ISSUE TITLE
DiMP50 only get 0.416 EAO on VOT2018

### ISSUE THREAD

**Issue by hongyuanyu** [visionml/pytracking#69]
Hi,

Thanks for your wonderful work.
Recently I run the DIMP50 tracker in python. I modify the basetracker.py and make it can run in VOT style.

```
            out = {}
            start_frame = 0
            init_dict = sequence.init_info()

            for f, image_file in enumerate(sequence.frames):
                start_time = time.time()
                image = self._read_image(image_file)
                if f == start_frame:
                    cx, cy, w, h = get_axis_aligned_bbox(np.array(sequence.ground_truth_rect[f]))
                    gt_bbox = [cx, cy, w, h]
                    init_dict['init_bbox'] = gt_bbox
                    
                    if getattr(self.params, 'restore_online', False):
                        read_online = getattr(self.params, 'read_online', False)
                        flag_read = read_online and (f==0)
                        raise NotImplementedError
                    else:
                        # self.initialize(raw_im, image, gt_bbox, init_online=True, read_pretrained=(f==0), video_name=sequence.name)
                        self.initialize(image, init_dict)
                        _store_outputs(out, {'target_bbox': [1, 1, 1, 1],
                             'score': 1.,
                             'time': time.time() - start_time})

                elif f > start_frame:
                    cx, cy, w, h = get_axis_aligned_bbox(np.array(sequence.ground_truth_rect[f]))
                    gt_bbox = [cx - w * 0.5, cy - h * 0.5, w, h]
                    output_dict = self.track(image)
                    state = output_dict['target_bbox']
                    score = output_dict['score']
                    iou = IoU(gt_bbox, state)
                    if iou <= 0:
                        state = [2, 2, 2, 2]
                        start_frame = f + 5

                    _store_outputs(out, {'target_bbox': state,
                            'score': score,
                            'time': time.time() - start_time})
                else:
                    state = [0, 0, 0, 0]
                    _store_outputs(out, {'target_bbox': state,
                            'score': 0.,
                            'time': time.time() - start_time})
```
I test the atom(default_vot.py) and dimp50(dimp50_vot.py)  10 times each. For ATOM the average EAO is 0.404(a bit better than paper), but for dimp50 the average EAO is only 0.416(0.44 in paper). The maximum EAO of DiMP50 is 0.446 and the minimum EAO is 0.378.

**Comment by DeepBrainsMe** [comment]
Hello,would you please share your IOU compute function? I can test it .

**Comment by hongyuanyu** [comment]
> Hello,would you please share your IOU compute function? I can test it .

https://github.com/researchmm/SiamDW/blob/d9180ed9947f1f0408dd2989f375bfbb45f930fe/lib/utils/utils.py#L371
https://github.com/researchmm/SiamDW/blob/d9180ed9947f1f0408dd2989f375bfbb45f930fe/lib/utils/utils.py#L396

**Comment by DeepBrainsMe** [comment]
我想请问一下，在跑dimp在线跟踪代码的时候，你的程序占用内存会一直增大么？会不会遇到随着跟踪视频个数的增加，内存占用也增加？



------------------ 原始邮件 ------------------
发件人: "hongyuan_yu"<notifications@github.com>; 
发送时间: 2019年9月16日(星期一) 上午10:47
收件人: "visionml/pytracking"<pytracking@noreply.github.com>; 
抄送: "JesseWang"<1098069058@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [visionml/pytracking] DiMP50 only get 0.416 EAO on VOT2018 (#69)



 
Hello,would you please share your IOU compute function? I can test it .
  
https://github.com/researchmm/SiamDW/blob/d9180ed9947f1f0408dd2989f375bfbb45f930fe/lib/utils/utils.py#L371
 https://github.com/researchmm/SiamDW/blob/d9180ed9947f1f0408dd2989f375bfbb45f930fe/lib/utils/utils.py#L396

**Comment by DeepBrainsMe** [comment]
> Hi,
> 
> Thanks for your wonderful work.
> Recently I run the DIMP50 tracker in python. I modify the basetracker.py and make it can run in VOT style.
> 
> ```
>             out = {}
>             start_frame = 0
>             init_dict = sequence.init_info()
> 
>             for f, image_file in enumerate(sequence.frames):
>                 start_time = time.time()
>                 image = self._read_image(image_file)
>                 if f == start_frame:
>                     cx, cy, w, h = get_axis_aligned_bbox(np.array(sequence.ground_truth_rect[f]))
>                     gt_bbox = [cx, cy, w, h]
>                     init_dict['init_bbox'] = gt_bbox
>                     
>                     if getattr(self.params, 'restore_online', False):
>                         read_online = getattr(self.params, 'read_online', False)
>                         flag_read = read_online and (f==0)
>                         raise NotImplementedError
>                     else:
>                         # self.initialize(raw_im, image, gt_bbox, init_online=True, read_pretrained=(f==0), video_name=sequence.name)
>                         self.initialize(image, init_dict)
>                         _store_outputs(out, {'target_bbox': [1, 1, 1, 1],
>                              'score': 1.,
>                              'time': time.time() - start_time})
> 
>                 elif f > start_frame:
>                     cx, cy, w, h = get_axis_aligned_bbox(np.array(sequence.ground_truth_rect[f]))
>                     gt_bbox = [cx - w * 0.5, cy - h * 0.5, w, h]
>                     output_dict = self.track(image)
>                     state = output_dict['target_bbox']
>                     score = output_dict['score']
>                     iou = IoU(gt_bbox, state)
>                     if iou <= 0:
>                         state = [2, 2, 2, 2]
>                         start_frame = f + 5
> 
>                     _store_outputs(out, {'target_bbox': state,
>                             'score': score,
>                             'time': time.time() - start_time})
>                 else:
>                     state = [0, 0, 0, 0]
>                     _store_outputs(out, {'target_bbox': state,
>                             'score': 0.,
>                             'time': time.time() - start_time})
> ```
> 
> I test the atom(default_vot.py) and dimp50(dimp50_vot.py) 10 times each. For ATOM the average EAO is 0.404(a bit better than paper), but for dimp50 the average EAO is only 0.416(0.44 in paper). The maximum EAO of DiMP50 is 0.446 and the minimum EAO is 0.378.

我认为原因1：可能是应为在vot数据集上四个点的旋转矩形框坐标转换到xywh坐标中引入了背景信息，导致跟踪精度降低，鲁棒性变差，EAO跟作者不符。你觉得是什么原因呢？

**Comment by goutamgmb** [comment]
Hi @hongyuanyu 

 I just evaluated the released model using the integration with vot toolkit (https://github.com/visionml/pytracking/tree/master/pytracking#vot-integration) and got ~0.425 over 15 runs. It's still lower than what we had with the model used for the paper. I will check if there has been some error introduced during the clean up of the code, but this might take some time.
