### ISSUE TITLE
Which dataset did you use for training MODEL_ZOO weight? 

### ISSUE THREAD

**Issue by whyjay** [visionml/pytracking#72]
Hi, i'm Youngjin.
Thanks for awesome research papers and codes. 
My question is, 
among various datasets listed in [MODEL_ZOO](https://github.com/visionml/pytracking/blob/master/MODEL_ZOO.md), 
which dataset did you use for training DiMP-18 pretrained weight?

**Comment by goutamgmb** [comment]
Hi,

We used the subsets of LaSOT, GOT10k, TrackingNet and COCO datasets. You can check the train setting file https://github.com/visionml/pytracking/blob/master/ltr/train_settings/dimp/dimp18.py to check the exact details.

**Comment by whyjay** [comment]
Great, thank you for answering!
