### ISSUE TITLE
train

### ISSUE THREAD

**Issue by 627081385** [visionml/pytracking#74]
when I run the training code for DiMP, I have encountered the following run-time assert which terminates my application
OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
What does this assert mean? What is the typical cause?

**Comment by dincaus** [comment]
I had same issue with that error and found [here](https://github.com/ContinuumIO/anaconda-issues/issues/11294) solution.  

Just set env. variable **KMP_INIT_AT_FORK**  to **FALSE** (in terminal type **export KMP_INIT_AT_FORK=FALSE**) and will solve the issue.
