### ISSUE TITLE
Computation of grdient of the loss (S1) w.r.t. filter coefficients f

### ISSUE THREAD

**Issue by chenfsjz** [visionml/pytracking#76]
Hi, in the Eqn. S4 in supplementary material, the computation <a href="https://www.codecogs.com/eqnedit.php?latex=q_c=v_c&space;m_c&plus;(1-m_c)\dot&space;$\mathbb&space;I$_{s>0}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?q_c=v_c&space;m_c&plus;(1-m_c)\dot&space;$\mathbb&space;I$_{s>0}" title="q_c=v_c m_c+(1-m_c)\dot $\mathbb I$_{s>0}" /></a>, does it miss the item <a href="https://www.codecogs.com/eqnedit.php?latex=v_c" target="_blank"><img src="https://latex.codecogs.com/gif.latex?v_c" title="v_c" /></a> in the second part of the equation. Because it multiplies with the whole residual function when compute the <a href="https://www.codecogs.com/eqnedit.php?latex=r(s,c)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?r(s,c)" title="r(s,c)" /></a>.  Could you explain it, thank you!

**Comment by goutamgmb** [comment]
Hi @chenfsjz 

Yes, that is indeed an error in the equation. Thanks a lot for notifying.

**Comment by chenfsjz** [comment]
Ok, Thank you for your reply!
