### ISSUE TITLE
Loading extension module _prroi_pooling... Can not compile Precise RoI Pooling library.

### ISSUE THREAD

**Issue by bigmoking** [visionml/pytracking#77]
Ｉ meet the  question, details follow:torch/include/c10/cuda/CUDAStream.h:6:10: fatal error: cuda_runtime_api.h: No such file or directory.
#include <cuda_runtime_api.h>
Loading extension module _prroi_pooling...
Ｉ meet the some question, details follow:torch/include/c10/cuda/CUDAStream.h:6:10: fatal error: cuda_runtime_api.h: No such file or directory.
#include <cuda_runtime_api.h>
Loading extension module _prroi_pooling...
Can not compile Precise RoI Pooling library.
ptorch:1.2.0
cuda:10.0.3
Thanks.

**Comment by martin-danelljan** [comment]
What OS and environment do you have? How did you install CUDA?

**Comment by bigmoking** [comment]
Thank you very much.  OS is Linux, CUDA version is 9.0, pytorch version is
1.0.0.

**Comment by martin-danelljan** [comment]
I would suggest you to try with pytorch 1.2 and CUDA 10.

**Comment by bigmoking** [comment]
okay, thank you very much for your help.

Martin Danelljan <notifications@github.com> 于2019年11月8日周五 下午5:36写道：
