### ISSUE TITLE
Can I get your help? I failed to reproduce the EAO score on VOT2018 from the given DiMP50 model

### ISSUE THREAD

**Issue by jinwook00** [visionml/pytracking#79]
Hi, 
Thanks to your great works and useful codes!
I just ran and evaluated the model 'dimp50.pth' on VOT2018. As shown in the following tables containing 10 and 100 trials respectively, couldn't reach the reported EAO(0.440).
10 trials,
![image](https://user-images.githubusercontent.com/56151017/66193260-267e3400-e6cd-11e9-8779-f163a1751128.png)
100 trials,
![image](https://user-images.githubusercontent.com/56151017/66193387-634a2b00-e6cd-11e9-94de-8bf21a9f0216.png)

Here is a process to reproduce the reported EAO with your codes.
1. download 'dimp50.pth' (from model Zoo and script your shared in 'install.sh')
2. run the tracker with $python run_experiment.py myexperiments dimp_vot
(with modified basetracker.py to handle VOT evaluation protocol such as skipping 5 frame)
3. evaluate the raw results with VOT protocol
4. find average EAO score

Although I'm already aware that stochastic methods such as dropout, random augmentation and initialization can lead fluctuation in terms of accuracy for each trial. The EAO range we made is too low to reach the reported one. How can I reproduce your work correctly? What am I missing? 
Thanks in advance.

**Comment by DeepBrainsMe** [comment]
> Hi,
> Thanks to your great works and useful codes!
> I just ran and evaluated the model 'dimp50.pth' on VOT2018. As shown in the following tables containing 10 and 100 trials respectively, couldn't reach the reported EAO(0.440).
> 10 trials,
> ![image](https://user-images.githubusercontent.com/56151017/66193260-267e3400-e6cd-11e9-8779-f163a1751128.png)
> 100 trials,
> ![image](https://user-images.githubusercontent.com/56151017/66193387-634a2b00-e6cd-11e9-94de-8bf21a9f0216.png)
> 
> Here is a process to reproduce the reported EAO with your codes.
> 
> 1. download 'dimp50.pth' (from model Zoo and script your shared in 'install.sh')
> 2. run the tracker with $python run_experiment.py myexperiments dimp_vot
>    (with modified basetracker.py to handle VOT evaluation protocol such as skipping 5 frame)
> 3. evaluate the raw results with VOT protocol
> 4. find average EAO score
> 
> Although I'm already aware that stochastic methods such as dropout, random augmentation and initialization can lead fluctuation in terms of accuracy for each trial. The EAO range we made is too low to reach the reported one. How can I reproduce your work correctly? What am I missing?
> Thanks in advance.

Here is a trick! Before tracking, you'd better translate the VOT label to **### smaller** bbox like OTB.


import numpy as np


def convert_vot_anno_to_rect(vot_anno, type):
    if len(vot_anno) == 4:
        return vot_anno

    if type == 'union':
        x1 = min(vot_anno[0::2])
        x2 = max(vot_anno[0::2])
        y1 = min(vot_anno[1::2])
        y2 = max(vot_anno[1::2])
        return [x1, y1, x2 - x1, y2 - y1]
    elif type == 'preserve_area':
        if len(vot_anno) != 8:
            raise ValueError

        vot_anno = np.array(vot_anno)
        cx = np.mean(vot_anno[0::2])
        cy = np.mean(vot_anno[1::2])

        x1 = min(vot_anno[0::2])
        x2 = max(vot_anno[0::2])
        y1 = min(vot_anno[1::2])
        y2 = max(vot_anno[1::2])

        A1 = np.linalg.norm(vot_anno[0:2] - vot_anno[2: 4]) * np.linalg.norm(vot_anno[2: 4] - vot_anno[4:6])
        A2 = (x2 - x1) * (y2 - y1)
        s = np.sqrt(A1 / A2)
        w = s * (x2 - x1) + 1
        h = s * (y2 - y1) + 1

        x = cx - 0.5*w
        y = cy - 0.5*h
        return [x, y, w, h]
    else:
        raise ValueError

**Comment by jinwook00** [comment]
Thanks for the kind comment and reference code. A function(_construct_sequence) in 'votdataset.py' is modified to make a tighter BB for VOT2018 datasets using the 'preserve_area' option such as 'run_vot.py'. The scores are slightly higher as show in the following, but it's still not in the error bound toward 0.44x EAO 
![image](https://user-images.githubusercontent.com/56151017/66295283-e239a080-e925-11e9-9f00-3e7b9510c57c.png)

Q 1) Is there remaining sweet spots that I'm missing to reach the reported EAO? 
Q 2) And one more small thing; DiMP50 official raw results on VOT2018 in this web page have 4 points to describe a tracked bounding box. However, DiMP50 tracker in pytracking toolkit produces 2 points + BB width and height. Is it possible to make 4 points-tracked BB for DiMP50 tracker? I'm considering more accurate BB estimation. 

Thanks in advance.

**Comment by goutamgmb** [comment]
Hi @jinwook00 

As @DeepBrainsMe mentioned, converting the box using 'preserve_area' leads to slightly better results. I just evaluated the released model using the integration with vot toolkit (https://github.com/visionml/pytracking/tree/master/pytracking#vot-integration) and got ~0.425 over 15 runs. It's still lower than what we had with the model used for the paper. I will check if there has been some error introduced during the clean up of the code, but this might take some time. 

Regarding Q2, no. With the current version, we can only output axis-aligned bounding boxes (xywh). For the raw results, we just converted the xywh output to the 4 points format.

**Comment by jinwook00** [comment]
Hi @goutamgmb, thanks for the kind feedback.
With the trick @DeepBrainsMe mentioned, I got this table for 15 runs;
![image](https://user-images.githubusercontent.com/56151017/66361784-14e1a880-e9bb-11e9-9948-2e0a02bff1a3.png)
I'm going to keep diving into your awesome works to get insights more. Thanks again and see you in ICCV.

**Comment by DeepBrainsMe** [comment]
Hello , @goutamgmb @jinwook00 , I ' m happy to hear your results  improved .Hello are my results table, The  max EAO score  is  0.436(not average).  but it close to 0.440 . Hope to find the bugs .
![image](https://user-images.githubusercontent.com/38520637/66390165-aa515c80-e9fc-11e9-95f3-e9466fd867c6.png)

**Comment by DeepBrainsMe** [comment]
Hello ,     @goutamgmb @jinwook00 , I ' m happy to hear your results improved .Hello are my results table, The max EAO score is 0.436(not average). but it close to 0.440 . Hope to find the bugs .
![image](https://user-images.githubusercontent.com/38520637/66390566-86424b00-e9fd-11e9-803c-766dfc04b473.png)

**Comment by frank-chan-ck** [comment]
> Hi,
> Thanks to your great works and useful codes!
> I just ran and evaluated the model 'dimp50.pth' on VOT2018. As shown in the following tables containing 10 and 100 trials respectively, couldn't reach the reported EAO(0.440).
> 10 trials,
> ![image](https://user-images.githubusercontent.com/56151017/66193260-267e3400-e6cd-11e9-8779-f163a1751128.png)
> 100 trials,
> ![image](https://user-images.githubusercontent.com/56151017/66193387-634a2b00-e6cd-11e9-94de-8bf21a9f0216.png)
> 
> Here is a process to reproduce the reported EAO with your codes.
> 
> 1. download 'dimp50.pth' (from model Zoo and script your shared in 'install.sh')
> 2. run the tracker with $python run_experiment.py myexperiments dimp_vot
>    (with modified basetracker.py to handle VOT evaluation protocol such as skipping 5 frame)
> 3. evaluate the raw results with VOT protocol
> 4. find average EAO score
> 
> Although I'm already aware that stochastic methods such as dropout, random augmentation and initialization can lead fluctuation in terms of accuracy for each trial. The EAO range we made is too low to reach the reported one. How can I reproduce your work correctly? What am I missing?
> Thanks in advance.

>You said your third step is to  evaluate the raw results with VOT protocol, i met some problems in this step. Could you show your scripts to evaluate the raw results which are produced by running run_experiment.py. 
>
