### ISSUE TITLE
initialization problem

### ISSUE THREAD

**Issue by superkevingit** [visionml/pytracking#80]
https://github.com/visionml/pytracking/blob/62dd3db23d45e9c721ff3184f3b3bd523a5f32c5/ltr/models/bbreg/atom_iou_net.py#L53
In this part, you do some initialization for the network, but the self-defined "LinearBlock" is not belong to any part of data types in conditional statements, which including three structures. And these structures should not be initialized by specific method. So I wonder to know if there's a problem here or I missed some statements in the paper. Thank you !

**Comment by martin-danelljan** [comment]
Hi. The `self.modules()` goes through all modules recursively. So the internal layers in the `LinearBlock` will be return and initialized properly.

**Comment by superkevingit** [comment]
> Hi. The `self.modules()` goes through all modules recursively. So the internal layers in the `LinearBlock` will be return and initialized properly.

Thank you for reply, my mistakes, I debug this part and that's right.
