### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by zlj199502** [visionml/pytracking#82]
Hi, Sorry to bother you. when I use torch==0.4.1. There have a below  error.
![image](https://user-images.githubusercontent.com/31580553/66780120-50570800-eed0-11e9-89d7-669b34375636.png)

**Comment by goutamgmb** [comment]
Hi,

Have you tried with PyTorch 1.0 or above? It seems to be issue with cuda/pytorch installation, not related to pytracking (https://github.com/pytorch/pytorch/issues/21154, https://discuss.pytorch.org/t/cuda-runtime-error-11/30080)
