### ISSUE TITLE
Adaptive Fusion of Model Predictions in UPDT

### ISSUE THREAD

**Issue by ZZXin** [visionml/pytracking#84]
Hi，Thank for your awesome paper and code.
I am interested for Adaptive Fusion of Model Predictions between shallow and deep features in UPDT, Is it convenient to provide the corresponding code or pseudo code?

**Comment by goutamgmb** [comment]
Hi,

You can find the complete updt code at https://drive.google.com/file/d/1QZAwM-PooGvNM_2BpZRFr57lvH-yClVo/view

**Comment by ZZXin** [comment]
> Hi,
> 
> You can find the complete updt code at https://drive.google.com/file/d/1QZAwM-PooGvNM_2BpZRFr57lvH-yClVo/view

Thank you very much!
It's awesome!
