### ISSUE TITLE
ATOM-VID

### ISSUE THREAD

**Issue by withinnoitatpmet** [visionml/pytracking#86]
Hi,
Thank for your awesome work!
I noticed that you mentioned ATOM-VID in your ATOM paper, which is trained by imagine-vid. Is ATOM-VID learning schedule the same as the present one and we just need to replace the present datasets by imagenet-vid? If they are different, could you share your ATOM-VID learning settings?

**Comment by goutamgmb** [comment]
Hi,

We only replaced the datasets by imagenet-vid. All other settings were the same.
