### ISSUE TITLE
ATOM: specific code related question on update_memory

### ISSUE THREAD

**Issue by rambleramble** [visionml/pytracking#88]
Great work and thanks for sharing the code!
In the following link, (similar case  in also for ECO And DiMP), it seems the memory was not updated to the model, aka. the self.training_samples is not updated.

(https://github.com/visionml/pytracking/blob/d7203910bbdea9fcf4a64f946c725e7de077ab85/pytracking/tracker/atom/atom.py#L591)

Is it done so on purpose? Thanks for this clarification.

**Comment by martin-danelljan** [comment]
Thanks!
I am not sure what you mean. The line you posted is actually what updates the memory.

**Comment by rambleramble** [comment]
my bad, I get now
I was confused myself. 
thanks again and closing the issue.

**Comment by martin-danelljan** [comment]
In python, objects are copied by reference. So this line of code also changes `self.training_samples`.

**Comment by rambleramble** [comment]
got it, thanks so much for this clarification!
