### ISSUE TITLE
how to use the optional box?

### ISSUE THREAD

**Issue by lchunleo** [visionml/pytracking#89]
Hi
  i tried to run with the syntax run_video.py --optional_box 100,100,100,100 <trackername> <type> <path of the video> but unable to run up. 

 it mention   assert isinstance(optional_box, list, tuple) TypeError: isinstance expected 2 arguments, got 3. 

 i tried --optional_box [100,100,100,100] also can't work

 Any sample running commands how to indicate the optional_box in the command line? thanks

**Comment by serycjon** [comment]
--optional_box 100 100 100 100
