### ISSUE TITLE
Unknown issue with No module named 'dlframework.common.utils'

### ISSUE THREAD

**Issue by tsingqguo** [visionml/pytracking#90]
Hi, Martin

Thanks for your great works. I got a issue at the 'self.net = load_network(self.net_path)' when I tried the atom tracker and it reported: ModuleNotFoundError: No module named 'dlframework.common.utils'.  
My operation system is ubuntu 16.04 with python 3.6 and pytorch 1.0. I am not sure which part is going wrong.

**Comment by martin-danelljan** [comment]
Hi. This should not happen actually. Bu I have not tested for python 3.6. I pushed a changed that might fix it. Could you try if it works with the latest version?

**Comment by tsingqguo** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    Hi, Martin. Thanks for your reply.  I will try the lastest version and give you feedback.
    
      
    
        
            
    
        
        
            
                
                    Qing Guo
                    
 
    

    On 11/8/2019 17:32，Martin Danelljan<notifications@github.com> wrote： 


Hi. This should not happen actually. Bu I have not tested for python 3.6. I pushed a changed that might fix it. Could you try if it works with the latest version?
