### ISSUE TITLE
Multi-scale test to replace IOU-Net, How to set parameters?

### ISSUE THREAD

**Issue by songdejia** [visionml/pytracking#91]
Hi, martin.
If we use multi-scale test to replace IOU-Net, How to set parameters?
thanks in advance

**Comment by martin-danelljan** [comment]
Hi. I added such a [parameter file here](https://github.com/visionml/pytracking/blob/master/pytracking/parameter/atom/multiscale_no_iounet.py), which corresponds to the experiments we performed in the paper. The results will not be very good obviously. It can be improved by also including shallow features as in ECO.

**Comment by songdejia** [comment]
Thanks very much. 
In this setting, OPE dataset:OTB100, UAV... and VOT dataset should have different setting ?

**Comment by martin-danelljan** [comment]
I have never tried to run thin one on VOT. But it would definitely require some other settings to achieve decent performance there. I suggest you base that version on the ATOM VOT parameters and change the `use_iou_net` and `scale_factors` parameters as in the file above.

**Comment by songdejia** [comment]
Thanks, my problem is solved.
