### ISSUE TITLE
Multi-Object Tracking

### ISSUE THREAD

**Issue by jhxing** [visionml/pytracking#94]
Does this model approve multi-object tracking ? Thanks for anythone gives me the anwser and support.

**Comment by goutamgmb** [comment]
Please check the previous issue about multi-object tracking (https://github.com/visionml/pytracking/issues/8).

**Comment by jhxing** [comment]
> Please check the previous issue about multi-object tracking (#8).

Thank you ! I will have a look at the issue before, and try it.
