### ISSUE TITLE
Is there any alternative to the PreRoIPoolinng layer?

### ISSUE THREAD

**Issue by TCBocean** [visionml/pytracking#97]
I recently tried to build DiMP on TensorFlow, but I didn't find the TensorFlow implementation of the PreRoIPooling layer. Because I am not familiar with CUDA programming, I have no ability to write the TensorFlow implementation of the PreRoIPooling layer. So would like to ask if there are some alternatives? Can anyone give me some advice? Thank you.

**Comment by goutamgmb** [comment]
Unfortunately, we are not aware of any such alternative right now.

**Comment by martin-danelljan** [comment]
It should be possible to implement with Tensorflow layers (creating the integration mask that is differentiable with BB coordinates and then

**Comment by TCBocean** [comment]
I tried to replace PreRoIPooling with ROIAlign, because ROIAlign is relatively simple to implement on TensorFlow. I think the replacement using ROIAlign should be feasible, because the total loss of the DiMP network is constantly declining. I haven't tested how much impact the replacement has on tracking accuracy.
