### ISSUE TITLE
Integrate detector and tracker

### ISSUE THREAD

**Issue by lchunleo** [visionml/pytracking#99]
Any example how to use the sequences? 

thank you

**Comment by goutamgmb** [comment]
Could you further clarify the issue? 
https://github.com/visionml/pytracking/tree/master/pytracking#running-a-tracker describes how to run the tracker in different modes.

**Comment by lchunleo** [comment]
my apologies for the unclear question. i have modified my title of the question.

i wish to able to integrate my detector with the tracker. My detector is accepting a video file and output bounding box.
The current tracker accepts either sequences or video files as input. thus i think if it is a sequence, how can i able to feed it? Am i suppose to cut all the frames and index them in a directory (like those dataset mentioned) and provides to the tracker?
